### ISSUE TITLE
.JSON files missing

### ISSUE THREAD

**Issue by biohazardxxx** [john30/ebusd#10]
Hi,

there are several not met references to json files in the html.

![2016-01-13 15_37_15-ebusd](https://cloud.githubusercontent.com/assets/1370362/12297084/b31c00a6-ba0b-11e5-9db4-ca80a0d22bc5.png)

**Comment by john30** [comment]
yes I know. the HTTP port is still experimental and currently only support EHP with UIH and optionally RCC+MC2. More files are to be added some time in future, but before that, the automatism for placing entities in the HTML UI, connecting them, highlighting currently active tubes and so on needs to be finished.
John

**Comment by john30** [comment]
now covered by #33
