### ISSUE TITLE
Time fields when integrating with Home Assistant

### ISSUE THREAD

**Issue by PWSEBUS** [john30/ebusd#1006]
### Description

I want to integrate the timing setting for teh Hot Water Circuit in Home Assistant.
Looking with a mqqt client, the payload looks like:
{
     "startTime": {"value": "13:00"},
     "endTime": {"value": "15:00"},
     "slotTemp": {"value": 480}
}
In Home Assistant only the  slotTemp is discovered. I think it has someting to do with the mapping in the mqtt-hassio.cfg file. 
I see there:

# HA integration: skip string/date/time types completely
type_map-string =
type_map-date =
type_map-time =
type_map-datetime =

is this assumption correct? How can I get the time info in Home Assistant?

**Comment by pm90pl** [comment]
Hi there - any progress on that?

**Comment by john30** [comment]
obviously not.
you could adjust the mqtt-hassio.cfg similar to the other fields passing it and see if oyu can get it working

**Comment by pm90pl** [comment]
Would like to help but don't know where to even start? The configuration mqtt-hassio.cfg and mapping provided there - is it ebusd specific or there is somewhere a documentation to mqtt hassio?

**Comment by Xyaren** [comment]
I would like to request the same for date fields aswell.

```
[update notice] sent poll-read f43 HolidayStartPeriod QQ=31: 01.01.2007
[update notice] sent poll-read f43 HolidayEndPeriod QQ=31: 01.01.2008
```
