### ISSUE TITLE
Adpter v5 - problem with USR-ES1 module

### ISSUE THREAD

**Issue by zyzakin** [john30/ebusd#1010]
### Description

I have version 5 of the module, and I have to use an Ethernet connection because I am not getting a signal from the router via WiFi. Besides, I prefer a wired connection (as more reliable) than a radio connection.
Unfortunately, after connecting the module and setting the correct configuration, the module is not detected (it has the status not available).
After repeated attempts to reset and change the WiFi configuration ( switching on, off ) finally the module was "noticed" and it started to work somehow. The USR-ES1 module I am using is HanRun HR961160C 2315.
Unfortunately today it stopped and I decided it was best to report it. 

### Actual behavior

The USR-ES1 module is not detected by the adapter after being set to the correct confuguration as "Ethernet USR-ES1"

### Expected behavior

Correct detection of the USR-ES1 module

### ebusd version

23.2

### ebusd arguments

/usr/bin/ebusd -d ens:192.168.1.25:9999 --latency=80 --configlang=EN --scanconfig=full --configpath=http://cfg.ebusd.eu/ --log=bus error --log=main error --mqtthost=192.168.1.88 --mqttport=1883 --mqttjson -l /var/log/ebusd.log

### Operating system

Debian 11 (Bullseye) / Ubuntu 20-21 / Raspbian 11 / Raspberry Pi OS 11 (including lite)

### CPU architecture

x64

### Dockerized

None

### Hardware interface

adapter 5 via Ethernet

### Related integration

MQTT generic

### Logs

023-09-14 13:00:14.459 [bus error] unable to open 192.168.1.25:9999: ERR: generic I/O error
2023-09-14 13:00:22.523 [bus error] unable to open 192.168.1.25:9999: ERR: generic I/O error
2023-09-14 13:00:30.587 [bus error] unable to open 192.168.1.25:9999: ERR: generic I/O error
2023-09-14 13:00:38.651 [bus error] unable to open 192.168.1.25:9999: ERR: generic I/O error
2023-09-14 13:00:46.715 [bus error] unable to open 192.168.1.25:9999: ERR: generic I/O error
2023-09-14 13:00:54.779 [bus error] unable to open 192.168.1.25:9999: ERR: generic I/O error
2023-09-14 13:01:02.843 [bus error] unable to open 192.168.1.25:9999: ERR: generic I/O error
2023-09-14 13:01:10.907 [bus error
![Screenshot 2023-09-14 at 14-40-29 eBUS Adapter Shield](https://github.com/john30/ebusd/assets/31596535/6b532f57-c444-4291-8dec-0f98f9f24c4c)
] unable to open 192.168.1.25:9999: ERR: generic I/O error
2023-09-14 13:01:18.971 [bus error] unable to open 192.168.1.25:9999: ERR: generic I/O error

Logs via adapter
![Screenshot 2023-09-14 at 14-39-53 eBUS Adapter Shield](https://github.com/john30/ebusd/assets/31596535/0a42b2dc-d014-4a99-92bb-2
![Screenshot 2023-09-14 at 14-37-54 eBUS Adapter Shield](https://github.com/john30/ebusd/assets/31596535/2262e41e-a80c-4919-bd20-4634e5e79c7b)

![Screenshot 2023-09-14 at 14-39-14 eBUS Adapter Shield](https://github.com/john30/ebusd/assets/31596535/91c32be1-5bdf-4ac9-9a9c-3ccb04b4afa2)
4407000f57a)

**Comment by john30** [comment]
wrong repo, thus closed (this is the right one and please go on there: https://github.com/john30/ebusd-esp32)

anyway, the relevant part of the adapter log is not shown where the Ethernet module detection is done.
