### ISSUE TITLE
knx: OtShutdownLimit uses wrong datatype?

### ISSUE THREAD

**Issue by mivola** [john30/ebusd#1090]
### Description

in my knx.cfg I want to include OtShutdownLimit. I tried different associations (`mc/OtShutdownLimit/0`, `mc/OtShutdownLimit/desiredtemp`) and datatypes (9, 12) but it doesnt properly work.
- with DPT 9 I need to send 0.2 to set a temperature of 20
- with DPT 12 setting the temperature seems to work
- but when I change the value using `ebusctl write -c mc OtShutdownLimit 22`, no update is sent to the knx bus
- even if I send a read request to the knx bus, I get strange values such as:
```
2023-12-15 14:07:15.529,A_GroupValue_Read,1.1.2,7/4/11,00,0,,12,0,low,5,T_DATA_XXX_REQ,0
2023-12-15 14:07:15.709,A_GroupValue_Response,1.1.3,7/4/11,15,352321536,,12,0,low,5,T_DATA_XXX_REQ,0
```
so I wonder how I can properly use this field or if there is a bug in ebusd or the config?

the ebusd is started in docker with these env vars:

```
-e EBUSD_SCANCONFIG= \
-e EBUSD_DEVICE=/dev/ttyUSB0 \
-e EBUSD_VERSION=23.2 \
-e EBUSD_MQTTPORT=1883 \
-e EBUSD_MQTTHOST=mediaserver \
-e EBUSD_MQTTVAR="filter-direction=r|u|^w" \
-e EBUSD_MQTTINT=/etc/ebusd/mqtt-hassio.cfg \
-e EBUSD_MQTTJSON= \
-e EBUSD_KNXURL= \
-e EBUSD_KNXINT=/etc/ebusd/knx.cfg \
-e EBUSD_LOG=other:debug \
```

### Actual behavior

- cannot properly work with mc/OtShutdownLimit

### Expected behavior

- mc/OtShutdownLimit should work properly

### ebusd version

23.2

### ebusd arguments

see description

### Operating system

other

### CPU architecture

x64

### Dockerized

latest

### Hardware interface

other

### Related integration

TCP (cmdline client like ebusctl or netcat), MQTT generic, KNX

### Logs

n/a

**Comment by c-huetter** [comment]
Hi @mivola,

Would you please share the configuration CSV file that you're using? I would like to check the ebus data type and divider configured for the message OtShutdownLimit. If DPT-9 (2 byte float) works the message should probably be encoded as SIR with divisor 10.

Best
Christian

**Comment by john30** [comment]
desiredtemp is defined as UCH without divisor. as such, it is mapped to DPT 5.010 [according to the docs](https://github.com/john30/ebusd/wiki/3.4.-KNX-device#knx-data-types)

**Comment by mivola** [comment]
> desiredtemp is defined as UCH without divisor. as such, it is mapped to DPT 5.010 [according to the docs](https://github.com/john30/ebusd/wiki/3.4.-KNX-device#knx-data-types)

Thanks a lot for the clarification and the link to the doc. Just for my (and others) reference in the future: here is the missing link between desiredtemp and the UCH type: https://github.com/john30/ebusd-configuration/blob/4675cd03b2763867cf74bd12426b1990bebb6204/ebusd-2.1.x/de/_templates.csv#L13

Furthermore I want to state, that 5.010 seems to work fine in NodeRed & MQTT, only the logging in wiregate/eibd seems broken as it still shows incorrect decoded values:
`2024-09-20 09:15:44.790,A_GroupValue_Write,1.15.222,7/4/11,12,7.1,,5,0,low,5,T_DATA_XXX_REQ,0`
where `12` should not translate to `7.1` but to `18`.
