### ISSUE TITLE
Device '/dev/ttyAMA0' does not exist in eBUSd (2ad9b828_ebusd).

### ISSUE THREAD

**Issue by 1achy** [john30/ebusd#1091]
### Description

After update I have this error 👍 

Device '/dev/ttyAMA0' does not exist in eBUSd (2ad9b828_ebusd).

### Actual behavior

don't start up 

### Expected behavior

Device '/dev/ttyAMA0' does not exist in eBUSd (2ad9b828_ebusd).

### ebusd version

current source from git

### ebusd arguments

192.168.0.54:3333

### Operating system

Debian 12 (Bookworm) / Ubuntu 22-23 / Raspberry Pi OS 12 (including lite)

### CPU architecture

arm64

### Dockerized

None

### Hardware interface

adapter 2

### Logs

Device '/dev/ttyAMA0' does not exist in eBUSd (2ad9b828_ebusd).

**Comment by 1achy** [comment]
in other way if I change config I can't save . I have this error:

Impossibile salvare la configurazione del componente aggiuntivo, Device '/dev/ttyAMA0' does not exist in eBUSd (2ad9b828_ebusd). Got {'scanconfig': True, 'loglevel_all': 'notice', 'mqtttopic': 'ebusd', 'mqttint': '/etc/ebusd/mqtt-hassio.cfg', 'mqttjson': True, 'network_device': '192.168.0.54:3333', 'configpath': '/config/www/ebusd_mod_ctlv2/', 'device': '/dev/ttyAMA0', 'latency': 10, 'mode': 'enh'}

**Comment by 1achy** [comment]
config: 


scanconfig: true
loglevel_all: notice
mqtttopic: ebusd
mqttint: /etc/ebusd/mqtt-hassio.cfg
mqttjson: true
network_device: 192.168.0.54:3333
configpath: /config/www/ebusd_mod_ctlv2/
device: /dev/ttyAMA0
latency: 10



it is work 2 years

**Comment by john30** [comment]
no idea what this has to do with ebusd in the first place. if the device is missing, then certainly something goes quite wrong on the host system. so: check the syslog, check the devices, check dmesg

**Comment by 1achy** [comment]
hi, the device is connect network with ping it response 👍 


PING 192.168.0.54 (192.168.0.54): 56 data bytes
64 bytes from 192.168.0.54: icmp_seq=0 ttl=255 time=106.311 ms
64 bytes from 192.168.0.54: icmp_seq=1 ttl=255 time=46.641 ms
64 bytes from 192.168.0.54: icmp_seq=2 ttl=255 time=65.268 ms
64 bytes from 192.168.0.54: icmp_seq=3 ttl=255 time=166.363 ms
64 bytes from 192.168.0.54: icmp_seq=4 ttl=255 time=9.892 ms
64 bytes from 192.168.0.54: icmp_seq=5 ttl=255 time=26.092 ms
64 bytes from 192.168.0.54: icmp_seq=6 ttl=255 time=8.618 ms
^C
--- 192.168.0.54 ping statistics ---
7 packets transmitted, 7 packets received, 0.0% packet loss
round-trip min/avg/max/stddev = 8.618/61.312/166.363/53.389 ms
achy@Achys-MacBook-Pro ~ % ~~~~
achy@Achys-MacBook-Pro ~ % 



and it he work before update

**Comment by 1achy** [comment]
**Error at start moment:**

![Schermata 2023-12-23 alle 14 18 33](https://github.com/john30/ebusd/assets/6684654/3b3e8940-89f5-4e89-9c6c-e2df83c08540)


**Config 👍** 


![Schermata 2023-12-23 alle 14 22 03](https://github.com/john30/ebusd/assets/6684654/5216ec4f-e829-475c-9e19-ff7278a7729f)

**I try change config but I have error:**
![Schermata 2023-12-23 alle 14 25 07](https://github.com/john30/ebusd/assets/6684654/82dec3b4-261e-4a71-9110-84f671d2faa9)

**Comment by 1achy** [comment]
SOLVE:

disinstalla and reinstall OK
