### ISSUE TITLE
device status: missing enhanced byte 2

### ISSUE THREAD

**Issue by hryamzik** [john30/ebusd#1095]
### Description

I've just updated firmware to [Version 20221231](https://adapter.ebusd.eu/v31/firmware/20221231-offset.hex) and it stopped working.

### Actual behavior

`2023-12-17 22:12:11.162 [bus error] device status: missing enhanced byte 2`

### Expected behavior

no errors

### ebusd version

23.2

### ebusd arguments

 --foreground --mqtthost=core-mosquitto --mqttport=1883 --mqttuser=addons --mqttpass=*** --scanconfig --mqttjson --mqttint=/etc/ebusd/mqtt-hassio.cfg --mqtttopic=ebusd --device=enh:/dev/ttyUSB0 --log=all:notice

### Operating system

HAAS

### CPU architecture

arm on raspberry pi 2b

### Dockerized

same as ebusd version (running via [ha-addons](https://github.com/LukasGrebe/ha-addons))

### Hardware interface

adapter 3.0 USB

### Related integration

MQTT Home Assistant via mqtt-hassio.cfg

### Logs

2023-12-17 22:12:08.127 [bus notice] device status: resetting
2023-12-17 22:12:08.127 [bus notice] re-opened /dev/ttyUSB0
2023-12-17 22:12:11.162 [bus error] device status: missing enhanced byte 2

**Comment by john30** [comment]
did you check for the correct config via ebus PIC loader as stated in the [changelog](https://adapter.ebusd.eu/v31/picfirmware.en.html#versions)?

**Comment by hryamzik** [comment]
I did. I didn't get any issues after restarting the ebusd but I'm not confident with this setup now. Hopefully I'll have some time to adjust if needed once I get a chance to connect it to a heating system.

**Comment by john30** [comment]
ok, closing as unrelated for now
