### ISSUE TITLE
Mqtt default topic [ebusd] not defined

### ISSUE THREAD

**Issue by scantineau** [john30/ebusd#110]
Hi.

In ebusd command help :
--mqtttopic=TOPIC      Use MQTT TOPIC (prefix before /%circuit/%name or complete format) [ebusd]

In wiki : 
To enable MQTT support, a corresponding build is necessary and the MQTT port needs to be enabled (see --mqttport). The MQTT topic published to (and also subscribed to) can be adjusted by using the --mqtttopic option and defaults to "ebusd/%circuit/%name" where "%circuit" is replaced by the circuit name and "%name" by the message name.

But when you start ebusd without passing --mqtttopic=something no ebusd prefix is defined by default.

**Comment by john30** [comment]
thanks, fixed with 2adbe24
