### ISSUE TITLE
Xanthophyllum 23.3 not present in alpine linux repository

### ISSUE THREAD

**Issue by tjorim** [john30/ebusd#1108]
### Description

Similar issue to https://github.com/john30/ebusd/issues/958. Latest release notes (https://github.com/john30/ebusd/releases/tag/23.3)
suggest to run `apk --repository=http://dl-cdn.alpinelinux.org/alpine/edge/community add ebusd` for Alpine Linux. However, build is not present. Alpine repo still shows 'Tim' as developer but he said earlier he does not use or build it on alpine anymore.

### Actual behavior

Does not install ebusd 23.3, getting 23.2 instead.

### Expected behavior

Installs ebusd version 23.3.

### ebusd version

23.3

### ebusd arguments

n/a

### Operating system

other

### CPU architecture

x64

### Dockerized

None

### Hardware interface

adapter 5 via USB

### Logs

n/a

**Comment by john30** [comment]
I'll drop the line in the release notes until it is fixed

**Comment by piotrtobolski** [comment]
@john30 Users using Docker are waiting for ebusd to be available in Alpine repository. Do you think next version will be available soon?

I see there wasn't a lot of changes since 23.3 and it is already about half of a year since 23.3 was released. Maybe 23.3.1 can be released?

**Comment by john30** [comment]
why do docker user not simply use the docker devel image then?
`docker pull john30/ebusd:devel`

**Comment by apbarratt** [comment]
Please reopen and repair this.
Docker users can indeed simply use the devel image, but users of the HomeAssistant Add-On cannot rely on this as releasing a version that points to a development build would be irresponsible for the devs maintaining that work there to do.

**Comment by piotrtobolski** [comment]
HA addon creators don't need to use Alpine. I created HA addon based on ebusd-provided docker image: https://github.com/piotrtobolski/ha-addons/tree/master/ebusd

**Comment by apbarratt** [comment]
I feel there must be some story I'm missing here for why there is push back on releasing for Alpine when it's been included before.  What is it I'm not understanding for why this decision has been made this time but not on previous occasions? :/

**Comment by apbarratt** [comment]
For clarity, I've no idea why someone might choose to use Alpine over any other distro.  It just seems unusual that Alpine has been included in the past and LukasGrebe's project was well recommended and used frequently (i see yours is a fork of it, I'll give it a go, thank you!) And when it was noticed that this one had been missed, that sounds like it was just overlooked and not a deliberate error, it's then had quite a lot of push back on correcting that mistake.  It's that last bit I'm confused by.  What am I missing? :/

**Comment by apbarratt** [comment]
That addon of yours seems to be working like a charm, thank you muchly :)

**Comment by piotrtobolski** [comment]
I'm not expert at using Docker but if I understand it correctly, Alpine is often used because it is very small (in terms of MB) distribution. Here the problem was that the released version was for some reason incompatible with Alpine and it is already fixed but releasing it would require additional effort and @john30 decided it just isn't worth it. 23.4 (or whatever the next version will be called) should be working on Alpine as previously.

**Comment by john30** [comment]
merge request for 24.1 submitted: https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/74199

**Comment by john30** [comment]
merged in https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/74289
