### ISSUE TITLE
ebusfeed is broken in the latest (23.3) release

### ISSUE THREAD

**Issue by samm-git** [john30/ebusd#1111]
### Description

If ebusd is configured with `--with-ebusfeed` compilation fails with an error. It seems that ebusfeed.cpp was not updated with a latest changes to `ebusd::Device` class. As far as i could see - it now needs to be replaced with `SerialTransport` and `PlainCharDevice`.  As FreeBSD maintainer i will temporary disable `--with-ebusfeed` flag.

### Actual behavior

```
--- ebusfeed.o ---
In file included from ebusfeed.cpp:29:
../../src/lib/ebus/device.h:274:20: warning: 'notifyTransportStatus' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  virtual result_t notifyTransportStatus(bool opened);
                   ^
../../src/lib/ebus/device.h:138:20: note: overridden virtual function is here
  virtual result_t notifyTransportStatus(bool opened) {
                   ^
../../src/lib/ebus/device.h:306:8: warning: 'cancelRunningArbitration' overrides a member function but is not marked 'override' [-Winconsistent-missing-override]
  bool cancelRunningArbitration(ArbitrationState* arbitrationState);
       ^
../../src/lib/ebus/device.h:217:16: note: overridden virtual function is here
  virtual bool cancelRunningArbitration(ArbitrationState* arbitrationState);
               ^
ebusfeed.cpp:139:28: error: no member named 'create' in 'ebusd::Device'
  Device* device = Device::create(opt.device, 0, false);
                   ~~~~~~~~^
ebusfeed.cpp:161:17: error: no member named 'send' in 'ebusd::Device'
        device->send(byte);
        ~~~~~~  ^
2 warnings and 2 errors generated.
*** [ebusfeed.o] Error code 1
```

### Expected behavior

compilation of the ebusfeed or depreciation of that tool 

### ebusd version

23.3

### ebusd arguments

unrelated

### Operating system

other

### CPU architecture

x64

### Dockerized

None

### Hardware interface

adapter 5 via USB

### Related integration

other

### Logs

not relevant

**Comment by john30** [comment]
if someone is willing to maintain that, fine. I won't. as such, I'll remove it from the build scripts for now (again)
