### ISSUE TITLE
external access ip 162.252.x.x

### ISSUE THREAD

**Issue by Tomasonx** [john30/ebusd#1123]
### Description

I am on firmware version 2023-12-23 and the ebusd module tries "continuously" to access external IP xxx?

Why is this access needed?

1. Is it a "call home" for a reason?
2. Is it possible to stop this behavior and be 100% local without trying to access the internet?

### Actual behavior

Internet access

### Expected behavior

NO Internet access

### ebusd version

23.3

### ebusd arguments

-

### Operating system

Debian 12 (Bookworm) / Ubuntu 22-23 / Raspberry Pi OS 12 (including lite)

### CPU architecture

x64

### Dockerized

None

### Hardware interface

adapter 5 via USB

### Logs

-

**Comment by john30** [comment]
I guess you mean ebus adapter 5? then please use the appropriate repo for that one: https://github.com/john30/ebusd-esp32

anyway, the firmware does not connect anywhere besides your NTP server. can you record such a packet and give details about the port and protocol?
