### ISSUE TITLE
How to write one field?

### ISSUE THREAD

**Issue by biohazardxxx** [john30/ebusd#115]
Hi,

I couldn't find a way on the wiki to write to a field directly. Is that somehow possible?
For example I want to write only to hwc Timer.Monday from.0 
The write command would take from.0 as value since syntax is: write -c CIRCUIT NAME [VALUE[;VALUE]*]

**Comment by john30** [comment]
you always have to pass all fields of a write message for the time being. this is subject to be enhanced in future, but not on the roadmap yet as this implies reading the corresponding read message immediately before sending the write message, combining the current read values with the field(s) to set, and then sending the actual write message on the bus. somewhat complex and i'm not sure if its a good idea at all

**Comment by biohazardxxx** [comment]
Ok good to know that. Thanks for your reply and great work!
