### ISSUE TITLE
08.hmu.csv CurrentCompressorUtil

### ISSUE THREAD

**Issue by jirikral-desy** [john30/ebusd#1180]
### Description

The CurrentCompressorUtil parameter of 08.hmu.csv is more likely a D2C than D1B, at least on my system.
My system:
VWL 55/6 A 230V S2
VIH QW 190/6 E
VRC-720f

### Actual behavior

Overflows obviously with larger bit width than 8.
![comp_util](https://github.com/john30/ebusd/assets/90262152/5b2ae68d-1de7-4d5f-b4ac-4176868ce8ce)

### Expected behavior

Does not overflow when changed to D2C and shows reasonable values.
![com_util_D2C](https://github.com/john30/ebusd/assets/90262152/0094f04d-b60c-4384-90eb-207ef7789503)

### ebusd version

current source from git

### ebusd arguments

--scanconfig --configpath=somewhere/ebusd-config/latest/en -d ens:192.168.10.5:9999 --httpport=8082"

### Operating system

Debian 12 (Bookworm) / Ubuntu 22-23 / Raspberry Pi OS 12 (including lite)

### CPU architecture

x64

### Dockerized

None

### Hardware interface

Adapter Shield v5 via WiFi

### Related integration

HTTP

### Logs

N/A

**Comment by john30** [comment]
wrong repo, use [ebusd-configuration](https://github.com/john30/ebusd-configuration) for that
