### ISSUE TITLE
ebusd/contrib/etc/logrotate.d/ebusd error

### ISSUE THREAD

**Issue by modenet** [john30/ebusd#120]
I receive a daily logrotate error:
/etc/cron.daily/logrotate:
error: ebusd:prerotate, postrotate or preremove without endscript
error: found error in file ebusd, skipping

to resolve simply add the endscript command on bottom:
/var/log/ebusd*.log {
        rotate 7
        size 1M
        copytruncate
        compress
        missingok
        notifempty
        daily
        postrotate
                /usr/bin/killall -HUP ebusd
        endscript
}

**Comment by john30** [comment]
seems to be related to a newer logrotate version
