### ISSUE TITLE
Cannot set WLAN client 64 char password

### ISSUE THREAD

**Issue by BastelBaus** [john30/ebusd#1201]
### Description

Trying to configure my WLAN password but seams I cannot set a 64 char password (only 63 chars)
![grafik](https://github.com/john30/ebusd/assets/44684710/50687abc-ba05-4328-8d1b-be5f0d43b8a5)
![grafik](https://github.com/john30/ebusd/assets/44684710/295c4013-35bc-4277-91c0-7a5aac4c4420)

Build: 20240106

### Actual behavior

can only use 63 chars

### Expected behavior

64 chars should still be OK

### ebusd version

current source from git

### ebusd arguments

used 

### Operating system

Debian 12 (Bookworm) / Ubuntu 22-23 / Raspberry Pi OS 12 (including lite)

### CPU architecture

ESP32

### Dockerized

None

### Hardware interface

Adapter Shield v5 via USB

### Logs

n/a

**Comment by BastelBaus** [comment]
My quick fix was using repl command and set the nvs values manually ...
![grafik](https://github.com/john30/ebusd/assets/44684710/47e62910-246b-447e-b0ab-2e9a6d054b75)

but quickfix did not work. trying to reconnect (sta) i got the error "error: unable to load from NVS".  So I fear also the internal password variables are short by one byte ...

**Comment by john30** [comment]
wrong repo. moved to https://github.com/john30/ebusd-esp32/issues/50
