### ISSUE TITLE
ebusctl's returning code

### ISSUE THREAD

**Issue by modenet** [john30/ebusd#122]
Hi, is possible to have a valid return code in case of ebusctl's connection error?
it could be useful to diagnose connection error.
thanks

root@vps:# ebusctl -p 7778
error connecting to localhost:7778
root@vps# echo $?
0

it should be 1 instead.
thanks

**Comment by john30** [comment]
not yet

**Comment by john30** [comment]
it is a valid and potentially useful extension, though.
Thus, re-opened for later implementation.

**Comment by modenet** [comment]
thanks, maybe will be useful also an option to define connection timeout when not available (now is more than 2 minutes). es ebusctl -s <wrong ip>
