### ISSUE TITLE
unit of measurement 'None' in device class ('temperature')

### ISSUE THREAD

**Issue by wiedwo** [john30/ebusd#1224]
### Description

Hello John,
opened an issue on Github (integration mqtt) as adviced (see below) and got following answer:

Seems an issue with the ebusd and you are probably using https://github.com/john30/ebusd
Please address this issue on that repository as this is not an issue with the MQTT integration or Home Assistant.

Please have a look...

### Actual behavior

Got following Warning :
WARNING (MainThread) [homeassistant.components.sensor] Entity sensor.ebusd_heating_aktuelle_aussentemperatur_00_000_value (<class 'homeassistant.components.mqtt.sensor.MqttSensor'>) is using native unit of measurement 'None' which is not a valid unit for the device class ('temperature') it is using; expected one of ['°C', '°F', 'K']; Please update your configuration if your entity is manually configured, otherwise create a bug report at https://github.com/home-assistant/core/issues?q=is%3Aopen+is%3Aissue+label%3A%22integration%3A+mqtt%22

### Expected behavior

--

### ebusd version

current source from git

### ebusd arguments

-

### Operating system

Debian 12 (Bookworm) / Ubuntu 22-23 / Raspberry Pi OS 12 (including lite)

### CPU architecture

x64

### Dockerized

None

### Hardware interface

Adapter Shield v5 via Ethernet

### Related integration

MQTT Home Assistant via mqtt-hassio.cfg

### Logs

--

**Comment by john30** [comment]
where do you get the configs from? seems to be an under-defined message that misses the unit. if using the config repo, then address it here please [ebusd-configuration](https://github.com/john30/ebusd-configuration). if using own definitions, then add the unit
