### ISSUE TITLE
Wrong default name template in entites MQTT autodiscovery in HA

### ISSUE THREAD

**Issue by xjols** [john30/ebusd#1228]
### Description

In the entites created by MQTT autodiscovery, the default name, and entity ID, in some cases is created by the fields NAME and "TYPE TEMPLATE" defined in .csv or .inc files.
![imatge](https://github.com/john30/ebusd/assets/105730921/82a43a87-e632-4f6a-b128-5a3d6d040a54)
![imatge](https://github.com/john30/ebusd/assets/105730921/b388a4fd-9f99-4e1b-bc0f-4353324fed69)

### Actual behavior

In some cases the definition in HA is very confused, in entities with multiple outpus, like Status01 or Status02 multiple sensors are created with the same name not showing the real definition in the name by default:
i.e (Status01):

ID: sensor.ebusd_bai_statenumber
NAME: ebusd bai Status01 pumpstate

ID: sensor.ebusd_bai_status01_temp1
NAME: ebusd bai Status01 temp1

ID: sensor.ebusd_bai_status01_temp1_2
NAME: ebusd bai Status01 temp1

ID: sensor.ebusd_bai_status01_temp1_3
NAME: ebusd bai Status01 temp1

ID: sensor.ebusd_bai_status01_temp1_4
NAME: ebusd bai Status01 temp1

ID: sensor.ebusd_bai_status01_temp1_5
NAME: ebusd bai Status01 temp1

### Expected behavior

I think that the best definition may be the NAME and COMENT fields:
i.e (Status01):

ID: sensor.ebusd_bai_status01_temp_heating_flow
NAME: ebusd bai Status01 Temp heating flow

ID: sensor.ebusd_bai_status01_temp_heating_return
NAME: ebusd bai Status01 Temp heating return

ID: sensor.ebusd_bai_status01_outsidetemperature
NAME: ebusd bai Status01 Outsidetemperature

ID: sensor.ebusd_bai_status01_temp_warm_water
NAME: ebusd bai Status01 Temp warm water

ID: sensor.ebusd_bai_tanktemperture
NAME: ebusd bai Status01 Tanktemperture

ID: sensor.ebusd_bai_pump_Status
NAME: ebusd bai Status01 Pump Status

I think that modifying mqtt-hassio.cfg can solve this. Another option is creating multiple templates, one for each entity with the deried name, not "yesno" "temp" "temp1" "temp2"...

### ebusd version

23.3

### ebusd arguments

 ebusd --foreground --mqtthost=core-mosquitto --mqttport=1883 --mqttuser=addons --mqttpass=XXXXXXX --scanconfig --mqttjson --configpath=/config/ebusd/ebusd-configuration --latency=20 --accesslevel=* --pollinterval=5 --mqttint=/config/ebusd/mqtt-hassio.cfg --mqtttopic=ebusd --device=192.168.1.70:3333 --log=all:info --log=main:info --log=bus:info --log=update:info --log=network:info --log=other:debug

### Operating system

other

### CPU architecture

x64

### Dockerized

same as ebusd version

### Hardware interface

other

### Related integration

MQTT Home Assistant via mqtt-hassio.cfg

### Logs

2024-03-15 11:21:42.285 [mqtt debug] publish homeassistant/sensor/ebusd_bai_Flame_0/config {
  "unique_id":"ebusd_bai_Flame_0",
  "name":"ebusd bai Flame ",
  "device":{
   "identifiers":"ebusd_bai",
   "manufacturer":"ebusd.eu",
   "name":"ebusd bai",
   "via_device":"ebusd",
   "sw_version":"23.2",
   "suggested_area":"Heating"
  },
  "value_template":"{{value_json[\"0\"].value}}",
  "state_topic":"ebusd/bai/Flame",
  "device_class":"enum",
  "options":["on","off"]
 }
2024-03-15 11:21:42.286 [mqtt debug] publish homeassistant/binary_sensor/ebusd_bai_Fluegasvalve_onoff/config {
  "unique_id":"ebusd_bai_Fluegasvalve_onoff",
  "name":"ebusd bai Fluegasvalve onoff",
  "device":{
   "identifiers":"ebusd_bai",
   "manufacturer":"ebusd.eu",
   "name":"ebusd bai",
   "via_device":"ebusd",
   "sw_version":"23.2",
   "suggested_area":"Heating"
  },
  "value_template":"{{value_json[\"onoff\"].value}}",
  "state_topic":"ebusd/bai/Fluegasvalve",
  "payload_on":"on",
  "payload_off":"off",
  "state_class":"measurement"
 }
2024-03-15 11:23:18.505 [mqtt debug] publish homeassistant/sensor/ebusd_bai_FlowTempDesired_temp/config {
  "unique_id":"ebusd_bai_FlowTempDesired_temp",
  "name":"ebusd bai FlowTempDesired temp",
  "device":{
   "identifiers":"ebusd_bai",
   "manufacturer":"ebusd.eu",
   "name":"ebusd bai",
   "via_device":"ebusd",
   "sw_version":"23.2",
   "suggested_area":"Heating"
  },
  "value_template":"{{value_json[\"temp\"].value}}",
  "state_topic":"ebusd/bai/FlowTempDesired",
  "unit_of_measurement":"°C",
  "state_class":"measurement",
  "device_class":"temperature"
 }

**Comment by john30** [comment]
this is due to the absence of reasonable names in the message definition and clearly needs to be solved there in the first place:
https://github.com/john30/ebusd-configuration/blob/d12b9d119402a54d63eaf3c6f006aea30ebdd833/ebusd-2.1.x/de/vaillant/hcmode.inc#L12
