### ISSUE TITLE
Vaillant VMS SolPumpPower reported in kW instead of % in Home Assistant (MQTT) 

### ISSUE THREAD

**Issue by madmat17** [john30/ebusd#1229]
### Description

The data point SolPumpPower which is indicating the performance of the solar pump in 7-100% (see line 16 of configuration file `https://github.com/john30/ebusd-configuration/blob/master/ebusd-2.1.x/de/vaillant/06.pms.csv`) is reported to Home Assistant as kW measure instead of a relative percentage measure.
The cause of that seems to be that in the mentioned configuration the datatype/template `power` is being applied which in turn is leading to a wrong type is being applied in the MQTT / HA integration (see lines 176 and 190 in the file `https://github.com/john30/ebusd/blob/master/contrib/etc/ebusd/mqtt-hassio.cfg`)

### Actual behavior

Wrong data type / measure being reported via MQTT to HA (kW instead of %)

### Expected behavior

The data type / measure should be reported in %

### ebusd version

23.2

### ebusd arguments

ebusd --foreground --httpport=8889 --mqtthost=core-mosquitto --mqttport=1883 --mqttuser=addons --mqttpass=xxx --scanconfig --mqttjson --latency=10 --mqttint=/etc/ebusd/mqtt-hassio.cfg --mqtttopic=ebusd --device=enh:ebus-sensor.lan:9999 --log=all:notice

### Operating system

other

### CPU architecture

x64

### Dockerized

same as ebusd version

### Hardware interface

Adapter Shield v5 via WiFi

### Related integration

MQTT Home Assistant via mqtt-hassio.cfg

### Logs

n/a

**Comment by john30** [comment]
obiously a message definition issue rather than ebusd. adding the appropriate unit to https://github.com/john30/ebusd-configuration/blob/d12b9d119402a54d63eaf3c6f006aea30ebdd833/ebusd-2.1.x/de/vaillant/06.pms.csv#L16 would fix it, so please open an issue or even better a PR on https://github.com/john30/ebusd-configuration instead
