### ISSUE TITLE
Since update to Build: 20240317 : Lots of Warnings : host: errors: protocol

### ISSUE THREAD

**Issue by vbueschken** [john30/ebusd#1237]
### Description

Since update to Build: 20240317 : Lots of Warnings : host: errors: protocol

Configuration:
scanconfig: true
loglevel_all: notice
mqtttopic: ebusd
mqttint: /etc/ebusd/mqtt-hassio.cfg
mqttjson: true
network_device: ens:192.168.178.98:9999
latency: 10
accesslevel: "\"*\""
configpath: https://cfg.ebusd.eu/
mqttvar: filter-direction=r|u|^w

### Actual behavior

In Addition to the warnings in the adapter Log File aobout 50% of the Sensors from ebusd700 are 'not available' anymore
Sensors from ebusd bai looks OK

### Expected behavior

Sensor data should be available

### ebusd version

23.3

### ebusd arguments

see description

### Operating system

other

### CPU architecture

x64

### Dockerized

None

### Hardware interface

Adapter Shield v5 via WiFi

### Related integration

TCP (cmdline client like ebusctl or netcat)

### Logs

Adapter Log FIle:
Warning: host: errors: protocol (~every 30 sec)

Some Error Messages from the Home Assistant AddOn:
2024-03-25 15:24:02.096 [bus error] poll bai CounterStartAttempts3 failed: ERR: wrong symbol received
2024-03-25 15:23:44.117 [bus error] poll 700 z3ValveStatus failed: ERR: wrong symbol received
2024-03-25 15:23:26.101 [bus error] poll 700 z3QuickVetoTemp failed: ERR: SYN received
2024-03-25 15:23:14.069 [bus error] poll 700 z3OpMode failed: ERR: SYN received
2024-03-25 15:22:56.139 [bus error] poll 700 z3DayTemp failed: ERR: wrong symbol received
2024-03-25 15:23:02.085 [bus error] poll 700 z3HolidayTemp failed: ERR: SYN received
[bus error] poll bai ModulationTempDesired failed: ERR: wrong symbol received

**Comment by asoffe** [comment]
I am having the same issue. It only started to occur for me after updating to the latest firmware. This issue didn't exist for me before the upgrade.

**Comment by john30** [comment]
obviously no ebusd issue in the first place, so closing here. feel free to open in https://github.com/john30/ebusd-esp32 .
would help to know which version you were running before the update
