### ISSUE TITLE
Feature request: Accept multiple identical configuration lines that differs only for the master address

### ISSUE THREAD

**Issue by wrongisthenewright** [john30/ebusd#1248]
### Description

I'm using Ebusd with an Ariston Group hybrid system. Ariston uses a non standard version of the eBus protocol. In my reverse engineering of the various messages I have discovered that multiple masters can send the same kind of information on the bus using the same PBSB and command code sequence. but, obviously with different master address. Eg. these lines 

```
70fe203110========REDACTED==========0101 = 79
03fe203110========REDACTED==========0015 = 56
13fe203110========REDACTED==========000e = 134
37fe203110========REDACTED==========0100 = 138
7ffe203110========REDACTED==========000b = 96
```

should cast on the bus the serial number of the various component of the system (boiler, HP, energy manager, wifi bridge etc)

I have these lines in my config, but I can't enable them at the same time because eBusd gives an error of duplicate entry, duplicate ID.
```
#r,broadcast,hp_serial_number,HPSerial,13,fe,2031,,,m,STR:14
#r,broadcast,boiler_serial_number,BoilerSerial,37,fe,2031,,,m,STR:14
#r,broadcast,gw_serial_number,GWSerial,70,fe,2031,,,m,STR:14
#r,broadcast,sensys_serial_number,SystemSerial,7f,fe,2031,,value,m,STR:14
```
The error is present even if I set different circuit, one for every line.

Is it possible/adviable to enable a feature that allows this kind of use case? ATM the lines are related to parameters not that important so if the effort to support this is too high or it breaks something else then you can freely close this feature request.

Thank you all for your effort, in particular to John :)

**Comment by john30** [comment]
the issue is the definition of the messages. per se, a broadcast message is not supposed to be in the "readable" section as you can't actively read it at all. switching from the type=r to the usual type=b (for broadcast) solves it
