### ISSUE TITLE
Docker build error: version `GLIBCXX_3.4.21' not found

### ISSUE THREAD

**Issue by hvorragend** [john30/ebusd#125]
Hi, I cannot run new docker containers with the current build.
The following error appears:

`ebusd: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ebusd)`

In #82 you pointed to the development branch, but there is just one branch at the moment. I know that this was different in the past. Looks like you merged them. 

Do you have an idea?

**EBUSD_ARCH amd64**

**Comment by hvorragend** [comment]
Ah, I got it. In #82 you are talking about the Docker tags/branches.

I am now using john30/ebusd:devel and it works fine now.

**Comment by john30** [comment]
solved with 57f2b76
