### ISSUE TITLE
reload discards loaded config files but doesn't reload

### ISSUE THREAD

**Issue by jonathanschneider** [john30/ebusd#1283]
### Description

When I issue the command `reload` ebusd discards the currently loaded config files but doesn't actually reload (pick) config files. I had already started a discussion in #1281 and for another user ebusd behaves as expected.

### Actual behavior

Issuing `info` after `reload` shows that the addresses are (still) scanned but no config files are loaded:

```
localhost: info
version: ebusd 23.3.23.3-5-g47d2a3aa
device: ebus-adapter.fritz.box:9999, TCP, enhanced, firmware 1.1[451a].1[451a]
signal: acquired
symbol rate: 23
max symbol rate: 98
min arbitration micros: 2
max arbitration micros: 10
min symbol latency: 6
max symbol latency: 26
scan: finished
reconnects: 0
masters: 3
messages: 460
conditional: 0
poll: 6
update: 10
address 03: master #11
address 08: slave #11, scanned "MF=Vaillant;ID=BAI00;SW=0518;HW=7401", loaded "vaillant/bai.0010003886.inc", "vaillant/08.bai.csv"
address 10: master #2
address 15: slave #2, scanned "MF=Vaillant;ID=47000;SW=0128;HW=6002", loaded "vaillant/15.470.csv"
address 31: master #8, ebusd
address 36: slave #8, ebusd

localhost: reload
done

localhost: info
version: ebusd 23.3.23.3-5-g47d2a3aa
update check: revision 23.3 available
device: ebus-adapter.fritz.box:9999, TCP, enhanced, firmware 1.1[451a].1[451a]
signal: acquired
symbol rate: 23
max symbol rate: 98
min arbitration micros: 2
max arbitration micros: 11
min symbol latency: 6
max symbol latency: 26
scan: finished
reconnects: 0
masters: 3
messages: 13
conditional: 0
poll: 0
update: 4
address 03: master #11
address 08: slave #11, scanned
address 10: master #2
address 15: slave #2, scanned
address 31: master #8, ebusd
address 36: slave #8, ebusd
```

The only way I get ebusd to load the config files again is by restarting the service.

### Expected behavior

After `reload` the correct config files get loaded.

### ebusd version

23.3

### ebusd arguments

EBUSD_OPTS="--scanconfig --configpath=/home/pi/ebusd-configuration/latest/de -d ens:ebus-adapter.fritz.box:9999 --mqtthost=localhost --mqttport=1883 --configlang=DE --pollinterval=60"

### Operating system

Debian 9 (Stretch) / Ubuntu 16-17 / Raspbian 9 / Raspberry Pi OS 9 (including lite)

### CPU architecture

x64

### Dockerized

None

### Hardware interface

Adapter Shield v5 via USB

### Logs

Nothing relevant

**Comment by john30** [comment]
indeed, good spot!
