### ISSUE TITLE
MQTT reconnect

### ISSUE THREAD

**Issue by john30** [john30/ebusd#130]
automatically reconnect to broker when disconnected

**Comment by J0EK3R** [comment]
...would be very helpful!
In my homeautomation mosquitto is running as microservice (docker container with bridged network) on my NAS. The mosquitto MQTT-Broker is the glue between the different parts (ebusd, FHEM, ioBroker,...) of my homeautomation.
If I stop/start/restart the MQTT-Broker - till now - I have to restart ebusd too...
