### ISSUE TITLE
raspi:8889/data: SyntaxError: JSON.parse: bad control character in string literal at line 5636 column 19 of the JSON data

### ISSUE THREAD

**Issue by WSchimi** [john30/ebusd#1304]
### Description

ioBroker (and browser) cannot interpret json-data from ebusd and shows no actual data since 10.07.2024 08:48.
The problem is:
"global": {
  "version": "23.3.23.3",
  "updatecheck": "
OK, vaillant/08.bai.csv: different version available, vaillant/bai.0010010674.inc: different version available",

The problem is the LINEFEED <0x0a> befor OK, vaillant/... in JSON-data of "updatecheck":

### Actual behavior

After restart of ebusd it is working for ~3 minutes till the "updatecheck": is in JSON context with the wrong data (linefeed) befor the string "OK" (see Description)

### Expected behavior

working as 10.07.2024 befor 08:48 MESZ

### ebusd version

23.3

### ebusd arguments

EBUSD_OPTS="--scanconfig --device=ens:192.168.2.78:9999 --configpath=/home/pi/ebusd-configuration/ebusd-2.1.x/de --log=all:error --httpport=8889"

### Operating system

Debian 10 (Buster) / Ubuntu 18-19 / Raspbian 10 / Raspberry Pi OS 10 (including lite)

### CPU architecture

armv7l

### Dockerized

None

### Hardware interface

Adapter Shield v5 via WiFi

### Logs

there are no relevant logs for this problem

**Comment by WSchimi** [comment]
adding ebusd argument "--updatecheck=off" fixed this problem.

**Comment by dibman** [comment]
got the same problem, thx for this hint/workaround -> works
in result its an issue with the update check of ebusd?

**Comment by WSchimi** [comment]
I think so. But I can't find the reason where the line feed is placed before the "OK". The Version of my ebusd executable is unchanged.
