### ISSUE TITLE
How to use the experimental HTML based front-end

### ISSUE THREAD

**Issue by absalom-muc** [john30/ebusd#131]
Hi,
Could you give me a hint how to use the experimental HTML based front-end mentioned [here](https://github.com/john30/ebusd/wiki/7.-Integrations)?
Thank you!

**Comment by john30** [comment]
currently only EHP, UIH, and MC2 are supported for display in the HTML UI. You can activate it by using --httpport=PORT and placing the files from contrib/html into /var/ebusd/html and then open a webbrowser pointing at your ebusd host and the specified PORT.

**Comment by absalom-muc** [comment]
o.k. - thank you!
