### ISSUE TITLE
RecoVAIR SetBoostMode activate "Stoßlüften" but it canceled after 30sec

### ISSUE THREAD

**Issue by rICTx-T1D** [john30/ebusd#1313]
### Description

Hi folks,

when I activate the BoostMode on my recoVAIR it start full power ventilation but stopped after 30sec. In device display it shown speed down after boost mode.

When I activate it on VRC720, the boost mode run for 15min. How can I transmit the time for boost mode?

I tried:
 ebusctl w -c recov SetVentBoost
 ebusctl w -c recov SetVentBoost 600
^^ 600sek = 10min

Nothing works longer as 30sec.

Has anyone an idea?

### Actual behavior

no

### Expected behavior

no

### ebusd version

current source from git

### ebusd arguments

-

### Operating system

Debian 12 (Bookworm) / Ubuntu 22-23 / Raspberry Pi OS 12 (including lite)

### CPU architecture

x64

### Dockerized

devel

### Hardware interface

Adapter Shield v5 via USB

### Related integration

TCP (cmdline client like ebusctl or netcat)

### Logs

-

**Comment by john30** [comment]
not an ebusd issue but configuration. please check/reopen on
https://github.com/john30/ebusd-configuration

**Comment by amoledwatchfaces** [comment]
@rICTx-T1D Did you eventually solve this issue?
