### ISSUE TITLE
[mqtt error] received unmatchable topic ebusd/22420/room/temperature/set

### ISSUE THREAD

**Issue by wseifert** [john30/ebusd#1321]
### Description

publish raw value of 30.0 to write enabled topic ebusd/22420/room/temperature/set, result in ebusd.log: 
`2024-08-07 15:35:05.525 [mqtt error] received unmatchable topic ebusd/22420/room/temperature/set`

publish same value to same topic with ebusctl (ebusctl write -c 22420 room/temperature/set 30.0) result in ebusdlog:
`2024-08-07 15:35:29.447 [update notice] sent write 22420 room/temperature/set QQ=31: 30.0`

definition in /etc/ebusd/15.22420.HW0102.SW0502.csv:
`r1,,room/temperature,00-001 Aktuelle Raumtemperatur,,,,0081004a,,,param,,,,,,tempt,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
w,,room/temperature/set,00-001 Aktuelle Raumtemperatur,,,,0081004a,,,tempt,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,`

### Actual behavior

publishing value via MQTT results in `error received unmatchable topic ebusd/22420/room/temperature/set` in ebusd.log
publishing value via ebusctl results in `[update notice] sent write 22420 room/temperature/set QQ=31: 30.0` in ebusd.log

### Expected behavior

publishing value via MQTT results in `[update notice] sent write 22420 room/temperature/set QQ=31: 30.0` in ebusd.log

### ebusd version

23.3

### ebusd arguments

EBUSD_OPTS="--scanconfig --configpath=/etc/ebusd -d ens:/dev/ttyAMA0 --latency=20000 --mqtthost=192.168.0.24 --mqttport=1883 --enablehex --accesslevel=*"

### Operating system

Debian 12 (Bookworm) / Ubuntu 22-23 / Raspberry Pi OS 12 (including lite)

### CPU architecture

armv7l

### Dockerized

None

### Hardware interface

Adapter Shield v5 via Raspberry GPIO

### Related integration

MQTT generic

### Logs

2024-08-07 15:35:05.525 [mqtt error] received unmatchable topic ebusd/22420/room/temperature/set
2024-08-07 15:35:29.447 [update notice] sent write 22420 room/temperature/set QQ=31: 30.0

**Comment by john30** [comment]
answered in https://github.com/john30/ebusd/discussions/1320#discussioncomment-10552772
