### ISSUE TITLE
Deprecated option used in mqtt publish action call

### ISSUE THREAD

**Issue by ErikCoen** [john30/ebusd#1327]
### Description

Deprecated option used in mqtt publish action call
This stops working in version 2025.2.0. Please address before upgrading.
Deprecated payload_template option used in MQTT publish action call to topic ebusd/hmu/Statuscode/get from payload template ?1. Use the payload option instead. In automations templates are supported natively. Update the automation or script to use the payload option instead and restart Home Assistant to fix this issue.

Warning - 8/15/2024

Also for another sensors like:
ebusd/hmu/CurrentConsumedPower/get
ebusd/hmu/CurrentYieldPower/get
ebusd/hmu/CurrentConsumedPower/get
...

It is seen when home assistant on Raspberry Pi has been updated to 2024.8.x for HA core with operating system 13.0.

### Actual behavior

See description

### Expected behavior

A proper format is required.

### ebusd version

current source from git

### ebusd arguments

not relevant

### Operating system

Debian 12 (Bookworm) / Ubuntu 22-23 / Raspberry Pi OS 12 (including lite)

### CPU architecture

x64

### Dockerized

None

### Hardware interface

Adapter Shield v5 via Raspberry GPIO

### Logs

See description

**Comment by john30** [comment]
this is not related to ebusd from my point of view as there is no trace of an "payload_template" in the HA intergation file.
pleaes check your HA configuration and especially the component that issues the mqtt message (obviously not ebusd)
