### ISSUE TITLE
after the fix of issue 132, no master and slaves are listed

### ISSUE THREAD

**Issue by Erikwout** [john30/ebusd#134]
Hi,
 Thanks for the quick action...
 compiled the latest version, now it does not hang and it seems to decode some messages, but when i now ask for info in ebusctl i only see the ebusd device itself, and it thinks there is no signal, in the main screen i see a lot of traffic

localhost: i
 version: ebusd 3.0.p20171119
 update check: revision v3.0 available, broadcast.csv: different version available, memory.csv: different version available
 signal: no signal
 reconnects: 0
 masters: 1
 messages: 11
 conditional: 0
 poll: 0
 update: 4
 address 31: master #8, ebusd
 address 36: slave #8, ebusd

**Comment by john30** [comment]
to be honest, using ebusd on cygwin is highly experimental and I lack the time of supporting another environment. please consider using the [docker image](https://hub.docker.com/r/john30/ebusd/) instead.
