### ISSUE TITLE
Ignoring invalid option received on topic 

### ISSUE THREAD

**Issue by pascalwinters** [john30/ebusd#1350]
### Description

Warnings below happens a lot in HomeAssistant:

```
Ignoring invalid option received on topic 'ebusd/hmu/State', got '129', allowed: off, on
Ignoring invalid option received on topic 'ebusd/hmu/State', got '8', allowed: ready, heating, error, cooling, heating_water
Ignoring invalid option received on topic 'ebusd/hmu/State', got '128', allowed: off, on
Ignoring invalid option received on topic 'ebusd/basv/MultiRelaySetting', got '4', allowed: circulation, dryer, zone, legiopump
Ignoring invalid option received on topic 'ebusd/hmu/SetMode', got '23', allowed: auto, off, water
```

### Actual behavior

integration: MQTT

### Expected behavior

No errors

### ebusd version

current source from git

### ebusd arguments

.

### Operating system

other

### CPU architecture

x64

### Dockerized

latest

### Hardware interface

Adapter Shield v5 via WiFi

### Related integration

MQTT Home Assistant via mqtt-hassio.cfg

### Logs

NA

**Comment by uneart** [comment]
I can confirm this issue. Seeing similar errors such as 
`Ignoring invalid option received on topic 'ebusd/bai/HcPumpMode', got '3', allowed: post run, permanent, winter`

- ebusd version 23.3
- Home Assistant 2024.10.2
- Home Assistant OS 13.2
- MQTT integration

**Comment by john30** [comment]
not an ebusd issue, but realted to [ebusd-configuration](https://github.com/john30/ebusd-configuration) and obviously needed adjustment of the corresponding message definition, thus closing
