### ISSUE TITLE
C6 shield with HTTP auth: SyntaxError: Unexpected token 'o', "not authorized" is not valid JSON

### ISSUE THREAD

**Issue by Commifreak** [john30/ebusd#1352]
### Description

When enable http auth and cancel authentication, the website displays an api error. I think it should display the retrieved api error string only? Not a big deal but wanted to share.

![grafik](https://github.com/user-attachments/assets/d76a9aa2-21dd-4c70-91f3-a0414add3add)

### Actual behavior

API error

### Expected behavior

Nice error string

### ebusd version

current source from git

### ebusd arguments

-

### Operating system

other

### CPU architecture

x64

### Dockerized

latest

### Hardware interface

Adapter Shield v5 via USB

### Logs

-

**Comment by john30** [comment]
moved to https://github.com/john30/ebusd-esp32/issues/76
