### ISSUE TITLE
senden über mqtt an den ebusd (ebusctl r -f FlowTemp)

### ISSUE THREAD

**Issue by derAuge** [john30/ebusd#136]
Hallo John,

ich nutze den ebusd zusammen mit ioBroker
http://forum.iobroker.net/viewtopic.php?f=23&t=9322

nun stellt sich mir die Frage wie ich über MQTT abfragen senden kann
`ebusctl r -f FlowTemp`

ist das angedacht / möglich ?

Gruß

**Comment by john30** [comment]
> ich nutze den ebusd zusammen mit ioBroker

ich auch :-)
ja, [siehe hier](https://github.com/john30/ebusd/wiki/3.3.-MQTT-client)
