### ISSUE TITLE
HA Addon ebusd / MQTT Daten werden nicht vollständig angelegt im HA

### ISSUE THREAD

**Issue by heasti** [john30/ebusd#1362]
### Description

Die Daten welche mittels 15.ctlv2.csv abgefragt werden, werden nicht vollständig im HA per MQTT angezeigt. Es fehlen z.b. z1Name1 sowie die gesamten Zeitprogramme für Warmwasser Zirkulationspumpe und Zone 1-3.

### Actual behavior

Die Daten werden im MQTT-Explorer angezeigt, werden aber nicht automatisch im HA angelegt und angezeigt. 

### Expected behavior

Eine Vollständige Darstellung aller Daten die über MQTT ankommen werden automatisch als Entitäten erstellt.

### ebusd version

23.2

### ebusd arguments

-

### Operating system

other

### CPU architecture

x64

### Dockerized

latest

### Hardware interface

Adapter Shield v5 via WiFi

### Related integration

MQTT Home Assistant via mqtt-hassio.cfg

### Logs

-

**Comment by jan666** [comment]
check the `mqtt-hassio.cfg` file for `filter-...` and adjust for your needs. And maybe see https://github.com/john30/ebusd/issues/1357

**Comment by heasti** [comment]
@jan666  Thanks for the hint. After some searching I found the possibility in the EBUSD addon
![grafik](https://github.com/user-attachments/assets/c01bc977-604b-4938-b343-b60642a42a38)
