### ISSUE TITLE
24.1 does not follow symlink to device anymore

### ISSUE THREAD

**Issue by jan666** [john30/ebusd#1374]
### Description

I just updated to 24.1 and was unable to start with my old config:

`EBUSD_OPTS="--scanconfig -d ens:/dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_xx:xx:xx:xx:xx:xx-if00 [...]`

I had to change it to 

`EBUSD_OPTS="--scanconfig -d ens:/dev/ttyACM0 [...]`

to get it running again.

I don't know if it was supposed to work like this before, but it worked in 23.3. Feel free to just close this issue if it was never supposed to work like this.

### Actual behavior

ebusd does not start

### Expected behavior

ebusd should start(?)

### ebusd version

24.1

### ebusd arguments

--scanconfig -d ens:/dev/serial/by-id/usb-Espressif_USB_JTAG_serial_debug_unit_xx:xx:xx:xx:xx:xx-if00

### Operating system

Debian 12 (Bookworm) / Ubuntu 22-23 / Raspberry Pi OS 12 (including lite)

### CPU architecture

arm64

### Dockerized

None

### Hardware interface

Adapter Shield v5 via USB

### Related integration

other

### Logs

...

**Comment by john30** [comment]
good spot, thanks!
it does follow symlinks but only as long as the link does not contain colons.
workaround is indeed using the non-symlinked device or adjust the udev rules accordingly
