### ISSUE TITLE
Mixer status and movement

### ISSUE THREAD

**Issue by pascalwinters** [john30/ebusd#1402]
### Description

Is it possible to add the mixerstatus and mixermovement to the mqtt entities in HA with the usage of mqtt-hassio.cfg?
Proposed solutions:

1. Add those properties to the existing created entity (sensor.ebusd_basv_hc1actualflowtempdesired_value)
2. Add separate entities for those properties

Example data from mqtt explorer:
```
{
  "ftstatus": {
    "value": "on"
  },
  "ftdesired": {
    "value": 28
  },
  "mixerstatus": {
    "value": "on"
  },
  "mixermovement": {
    "value": 5
  }
}
```

**Comment by john30** [comment]
1. not an ebusd issue if those are part of a message for which the [definition does not include it](https://github.com/john30/ebusd-configuration/blob/b8acf157f677286c0e8cf492eb4c34e41e4e829b/src/vaillant/15.700.tsp#L624)

2. don't know where those should come from, but anyway also an ebusd-config issue if missing
