### ISSUE TITLE
MQTT-HASS: Invalid value for number.sensocomfort_outsidetempavg_tempv: -0.0078125 (range 0.0 - 100.0)

### ISSUE THREAD

**Issue by jan666** [john30/ebusd#1405]
### Description

(Maybe a duplicate of #1188 but maybe this is a different case?)

I noticed this error in my hass log:

`2024-12-02 07:36:22.529 ERROR (MainThread) [homeassistant.components.mqtt.number] Invalid value for number.sensocomfort_outsidetempavg_tempv: -0.0078125 (range 0.0 - 100.0)`

and indeed it was never updated below 0.0. I already checked `mqtt-hassio.cfg` but I can't find anything to change.

### Actual behavior

homeassistant.components.mqtt.number is not updated when the value is < 0

### Expected behavior

The range should be something like -100.0 - 100.0 or it should be just no range?

### ebusd version

24.1

### ebusd arguments

--scanconfig -d ens:/dev/ttyACM0 -c /home/pi/git/ebusd-configuration/ebusd-2.1.x/de/ --log=all:error --httpport=8080 --mqtthost xxx --mqttport 1883 --mqttuser ... --mqttpass ... --mqttint=/etc/ebusd/mqtt-hassio.cfg 

### Operating system

Debian 12 (Bookworm) / Ubuntu 22-23 / Raspberry Pi OS 12 (including lite)

### CPU architecture

arm64

### Dockerized

None

### Hardware interface

Adapter Shield v5 via USB

### Logs

nothing

**Comment by john30** [comment]
pretty much the same as in #1188, as for EXP types it does not make sense to put in the possible min/max in the first place. instead ebusd would need to be extended to support explicit min/max values per message field
