### ISSUE TITLE
Docker: cannot run daemon on Synology NAS

### ISSUE THREAD

**Issue by andig** [john30/ebusd#147]
See below:

	sudo docker run --rm -it -p 8888 john30/ebusd -d 192.168.0.46:9999 --scanconfig --latency=20000
	ebusd: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ebusd)

This is with the latest container. If you need any info from inside the container or access please let me know.

Just an idea- is this docker image for the wrong architecture? Missing `libstdc++6` (https://stackoverflow.com/questions/42464873/docker-compose-libstdc-so-6-glibcxx-3-4-21-not-found)?

**Comment by andig** [comment]
I can confirm that adding `libstdc++6` to the runtime docker image fixes the problem for running on Synology NAS.

**Comment by john30** [comment]
interesting, it was part of the base container for quite some time, but of course it doesn't hurt to add it.

**Comment by john30** [comment]
is this really independant of using stretch-slim instead of jessie?

**Comment by andig** [comment]
> is this really independant of using stretch-slim instead of jessie?

Yes. This issue was raised for the official ebusd docker image. I had the problem with jessie (plain, not slim) already and therefore split stretch-slim into separate container.

**Comment by john30** [comment]
I see, good.

**Comment by john30** [comment]
solved with latest commits (57f2b76)
