### ISSUE TITLE
3.0 version in ebusd-3.1_armhf-jessie_mqtt1.deb

### ISSUE THREAD

**Issue by mike-bike** [john30/ebusd#153]
Hi John, firstly many thanks for your continuous effort to maintain the ebusd package. 
Again I do have issues to get the latest version on my Raspberry 1 installed which I'd like to use with http and mqtt (unfortunately I cannot use mqtt alone yet).
/usr/bin/ebusd --version gives different results in jessie (3.0pre) and wheezy (3.1) packages:

- [ebusd-3.1_armhf-jessie_mqtt1.deb](https://github.com/john30/ebusd/releases/download/v3.1/ebusd-3.1_armhf-jessie_mqtt1.deb): ebusd --version gives ebusd 3.0pre.bbc4d04
- [ebusd-3.1_armhf-wheezy.deb](https://github.com/john30/ebusd/releases/download/v3.1/ebusd-3.1_armhf-wheezy.deb): ebusd --version gives ebusd 3.1.v3.0-35-gb0e20b7

Did I do something wrong?

Thanks
Michael

**Comment by john30** [comment]
no, this is a known flaw of that release and will be fixed with the next release (commit 88e4c7eec7d85aac44ccae6ea6454106960bdaa9)
