### ISSUE TITLE
ebusd-3.1_armhf-jessie_mqtt1.deb does not generate a logfile

### ISSUE THREAD

**Issue by PLCHome** [john30/ebusd#161]
Hello,

I have a problem with the logfile in the "ebusd-3.1_armhf-jessie_mqtt1.deb" on my PI
If I use the "ebusd-3.1_armhf-jessie.deb", a logfile is created and described, as soon as you use the "ebusd-3.1_armhf-jessie_mqtt1.deb", no logfile will be created.
Parameters at ebusd-3.1_armhf-jessie_mqtt1.deb:
--enablehex --scanconfig --configpath = / opt / ebus.conf / ebusd2 --loglevel = info --mqtthost = 192.168.2.10 --mqttport = 1883 --mqttjson --mqttuser = * --mqttpass = * - mqtttopic = ebusd /% circuit /% name /% field
Parameters at ebusd-3.1_armhf-jessie.deb:
--enablehex --scanconfig --configpath = / opt / ebus.conf / ebusd2 --loglevel = info

Also adding the parameter --logfile = / opt / ebus.log / ebusd.log teaches "ebusd-3.1_armhf-jessie_mqtt1.deb" unsuccessful. The "ebusd-3.1_armhf-jessie.deb" writes the log file properly.

**Comment by john30** [comment]
please ensure that only a single ebusd process is running at the same time, as it sounds like you're starting two of them and in this case only one will be able to write the log file. Or use a different log file with the command line params to be sure (and don't put spaces between / when specifying paths!).

**Comment by PLCHome** [comment]
Sorry its using the stdout ...

cat /var/log/supervisor/ebusd-stdout---supervisor-bbX1jn8.log

**Comment by john30** [comment]
why don't you use the ebusd docker image?
