### ISSUE TITLE
I can't start daemon

### ISSUE THREAD

**Issue by szczukot** [john30/ebusd#166]
Hi
I installed ebusd:
git clone https://github.com/john30/ebusd.git
cd ebusd
./autogen.sh
make 
sudo make install

pi@raspberrypi:/usr/bin $ sudo ebusd -f -d /dev/ttyUSB2 --scanconfig
2018-02-15 18:13:27.033 [main notice] ebusd 3.1.v3.1-22-gdaf771e started with auto scan
2018-02-15 18:13:27.054 [bus notice] bus started with own address 31/36
2018-02-15 18:13:27.104 [bus notice] signal acquired
2018-02-15 18:13:37.962 [bus notice] new master 03, master count 2
2018-02-15 18:13:46.982 [bus notice] scan 08: ;Vaillant;BAI00;0518;7401
2018-02-15 18:13:46.983 [update notice] store 08 ident: done
2018-02-15 18:13:46.984 [update notice] sent scan.08  QQ=31: Vaillant;BAI00;0518;7401
2018-02-15 18:13:46.985 [bus notice] scan 08: ;Vaillant;BAI00;0518;7401
2018-02-15 18:13:47.014 [main notice] read common config file /etc/ebusd/vaillant/general.csv
2018-02-15 18:13:47.016 [main notice] read common config file /etc/ebusd/vaillant/scan.csv
2018-02-15 18:13:47.021 [main notice] read common config file /etc/ebusd/vaillant/broadcast.csv
2018-02-15 18:13:47.029 [main notice] read scan config file /etc/ebusd/vaillant/08.bai.csv for ID "bai00", SW0518, HW7401
2018-02-15 18:13:47.114 [bus error] send to 08: ERR: read timeout, retry
2018-02-15 18:13:47.713 [update notice] sent scan.08 id QQ=31:
2018-02-15 18:13:47.949 [update notice] sent scan.08 id QQ=31:
2018-02-15 18:13:48.120 [update notice] sent scan.08 id QQ=31:
2018-02-15 18:13:48.295 [update notice] sent scan.08 id QQ=31: 21;10;40;0010003869;3100;005327;N7
2018-02-15 18:13:48.383 [main notice] found messages: 200 (0 conditional on 23 conditions, 0 poll, 9 update)
2018-02-15 18:13:48.516 [update notice] sent scan.08 id QQ=31: 21;10;40;0010003869;3100;005327;N7
2018-02-15 18:13:49.426 [update notice] sent scan.08 id QQ=31: 21;10;40;0010003869;3100;005327;N7
2018-02-15 18:15:47.814 [main notice] update check: revision v3.1-1-g60a18d1 available, broadcast.csv: different version available, memory.csv: different version available, vaillant/bai.0010003857.inc: different version available, vaillant/broadcast.csv: different version available, vaillant/errors.inc: different version available, vaillant/general.csv: different version available, vaillant/hcmode.inc: different version available

sudo systemctl enable ebusd
i get "Failed to execute operation: No such file or directory"
I can't run ebusd as daemon

and many times, when i start ebusd in foreground i get only:
2018-02-15 18:18:41.820 [main notice] ebusd 3.1.v3.1-22-gdaf771e started with auto scan
2018-02-15 18:18:41.845 [bus notice] bus started with own address 31/36
2018-02-15 18:18:41.862 [bus notice] signal acquired
and nothing else

regards
Fantom

**Comment by john30** [comment]
please provide the full output of "sudo systemctl enable ebusd" as well "ls -la lib/systemd/system/"

**Comment by szczukot** [comment]
pi@raspberrypi:~ $ sudo systemctl enable ebusd
Failed to execute operation: No such file or directory

pi@raspberrypi:~ $ sudo ls -la /lib/systemd/system
total 836
drwxr-xr-x 24 root root 36864 Feb  9 16:54 .
drwxr-xr-x  8 root root  4096 Jul 25  2017 ..
-rw-r--r--  1 root root   476 Jul 17  2014 alsa-restore.service
-rw-r--r--  1 root root   526 Jul 17  2014 alsa-state.service
-rw-r--r--  1 root root   373 Jul 17  2014 alsa-store.service
lrwxrwxrwx  1 root root     9 Jul 17  2014 alsa-utils.service -> /dev/null
lrwxrwxrwx  1 root root    14 May  7  2017 autovt@.service -> getty@.service
-rw-r--r--  1 root root  1044 Apr 18  2015 avahi-daemon.service
-rw-r--r--  1 root root   874 Apr 18  2015 avahi-daemon.socket
-rw-r--r--  1 root root   524 May  7  2017 basic.target
drwxr-xr-x  2 root root  4096 May 27  2016 basic.target.wants
-rw-r--r--  1 root root   338 May 27  2016 bluetooth.service
-rw-r--r--  1 root root   379 May  7  2017 bluetooth.target
lrwxrwxrwx  1 root root     9 May  7  2017 bootlogd.service -> /dev/null
lrwxrwxrwx  1 root root     9 May  7  2017 bootlogs.service -> /dev/null
lrwxrwxrwx  1 root root     9 May  7  2017 bootmisc.service -> /dev/null
lrwxrwxrwx  1 root root     9 May  7  2017 checkfs.service -> /dev/null
lrwxrwxrwx  1 root root     9 May  7  2017 checkroot-bootclean.service -> /dev/null
lrwxrwxrwx  1 root root     9 May  7  2017 checkroot.service -> /dev/null
-rw-r--r--  1 root root   770 May  7  2017 console-getty.service
-rw-r--r--  1 root root   741 May  7  2017 console-shell.service
-rw-r--r--  1 root root   783 May  7  2017 container-getty@.service
-rw-r--r--  1 root root   251 Sep  5  2015 cron.service
lrwxrwxrwx  1 root root     9 May  7  2017 cryptdisks-early.service -> /dev/null
lrwxrwxrwx  1 root root     9 May  7  2017 cryptdisks.service -> /dev/null
-rw-r--r--  1 root root   394 May  7  2017 cryptsetup-pre.target
-rw-r--r--  1 root root   366 May  7  2017 cryptsetup.target
lrwxrwxrwx  1 root root    13 May  7  2017 ctrl-alt-del.target -> reboot.target
lrwxrwxrwx  1 root root    25 May  7  2017 dbus-org.freedesktop.hostname1.service -> systemd-hostnamed.service
lrwxrwxrwx  1 root root    23 May  7  2017 dbus-org.freedesktop.locale1.service -> systemd-localed.service
lrwxrwxrwx  1 root root    22 May  7  2017 dbus-org.freedesktop.login1.service -> systemd-logind.service
lrwxrwxrwx  1 root root    24 May  7  2017 dbus-org.freedesktop.machine1.service -> systemd-machined.service
lrwxrwxrwx  1 root root    25 May  7  2017 dbus-org.freedesktop.timedate1.service -> systemd-timedated.service
-rw-r--r--  1 root root   366 Jan 15  2017 dbus.service
-rw-r--r--  1 root root   106 Jan 15  2017 dbus.socket
drwxr-xr-x  2 root root  4096 Apr 22  2017 dbus.target.wants
-rw-r--r--  1 root root   402 May  7  2017 debian-fixup.service
-rw-r--r--  1 root root  1010 May  7  2017 debug-shell.service
lrwxrwxrwx  1 root root    16 May  7  2017 default.target -> graphical.target
-rw-r--r--  1 root root   636 May  7  2017 dev-hugepages.mount
-rw-r--r--  1 root root   590 May  7  2017 dev-mqueue.mount
-rw-r--r--  1 root root   241 Oct 17  2015 dhcpcd.service
-rw-r--r--  1 root root   986 May  7  2017 emergency.service
-rw-r--r--  1 root root   431 May  7  2017 emergency.target
-rw-r--r--  1 root root   353 Mar 16  2015 fake-hwclock.service
-rw-r--r--  1 root root   440 May  7  2017 final.target
lrwxrwxrwx  1 root root     9 May  7  2017 fuse.service -> /dev/null
-rw-r--r--  1 root root  1536 May  7  2017 getty@.service
-rw-r--r--  1 root root   342 May  7  2017 getty-static.service
-rw-r--r--  1 root root   460 May  7  2017 getty.target
drwxr-xr-x  2 root root  4096 Jul 25  2017 getty.target.wants
-rw-r--r--  1 root root   490 May  7  2017 graphical.target
drwxr-xr-x  2 root root  4096 Jul 25  2017 graphical.target.wants
-rw-r--r--  1 root root   565 May  7  2017 halt-local.service
lrwxrwxrwx  1 root root     9 May  7  2017 halt.service -> /dev/null
-rw-r--r--  1 root root   487 May  7  2017 halt.target
drwxr-xr-x  2 root root  4096 May 27  2016 halt.target.wants
-rw-r--r--  1 root root   271 Feb 16  2017 hciuart.service
-rw-r--r--  1 root root   447 May  7  2017 hibernate.target
lrwxrwxrwx  1 root root     9 May  7  2017 hostname.service -> /dev/null
lrwxrwxrwx  1 root root     9 May  7  2017 hwclockfirst.service -> /dev/null
-rw-r--r--  1 root root   398 May  7  2017 hwclock-save.service
lrwxrwxrwx  1 root root     9 May  7  2017 hwclock.service -> /dev/null
-rw-r--r--  1 root root   468 May  7  2017 hybrid-sleep.target
-rw-r--r--  1 root root   380 May  7  2017 ifup@.service
-rw-r--r--  1 root root   630 May  7  2017 initrd-cleanup.service
-rw-r--r--  1 root root   553 May  7  2017 initrd-fs.target
-rw-r--r--  1 root root   790 May  7  2017 initrd-parse-etc.service
-rw-r--r--  1 root root   526 May  7  2017 initrd-root-fs.target
-rw-r--r--  1 root root   640 May  7  2017 initrd-switch-root.service
-rw-r--r--  1 root root   691 May  7  2017 initrd-switch-root.target
drwxr-xr-x  2 root root  4096 May 27  2016 initrd-switch-root.target.wants
-rw-r--r--  1 root root   671 May  7  2017 initrd.target
-rw-r--r--  1 root root   664 May  7  2017 initrd-udevadm-cleanup-db.service
-rw-r--r--  1 root root   501 May  7  2017 kexec.target
drwxr-xr-x  2 root root  4096 May 27  2016 kexec.target.wants
lrwxrwxrwx  1 root root     9 May  7  2017 killprocs.service -> /dev/null
lrwxrwxrwx  1 root root    28 May  7  2017 kmod.service -> systemd-modules-load.service
-rw-r--r--  1 root root   675 May  7  2017 kmod-static-nodes.service
-rw-r--r--  1 root root   395 May  7  2017 local-fs-pre.target
-rw-r--r--  1 root root   507 May  7  2017 local-fs.target
drwxr-xr-x  2 root root  4096 Jul 25  2017 local-fs.target.wants
-rw-r--r--  1 root root   405 May  7  2017 machine.slice
-rw-r--r--  1 root root   473 May  7  2017 mail-transport-agent.target
lrwxrwxrwx  1 root root    28 May  7  2017 module-init-tools.service -> systemd-modules-load.service
lrwxrwxrwx  1 root root     9 May  7  2017 motd.service -> /dev/null
lrwxrwxrwx  1 root root     9 May  7  2017 mountall-bootclean.service -> /dev/null
lrwxrwxrwx  1 root root     9 May  7  2017 mountall.service -> /dev/null
lrwxrwxrwx  1 root root     9 May  7  2017 mountdevsubfs.service -> /dev/null
lrwxrwxrwx  1 root root     9 May  7  2017 mountkernfs.service -> /dev/null
lrwxrwxrwx  1 root root     9 May  7  2017 mountnfs-bootclean.service -> /dev/null
lrwxrwxrwx  1 root root     9 May  7  2017 mountnfs.service -> /dev/null
-rw-r--r--  1 root root   492 May  7  2017 multi-user.target
drwxr-xr-x  2 root root  4096 Jul 25  2017 multi-user.target.wants
drwxr-xr-x  2 root root  4096 Jul 25  2017 networking.service.d
-rw-r--r--  1 root root   464 May  7  2017 network-online.target
-rw-r--r--  1 root root   461 May  7  2017 network-pre.target
-rw-r--r--  1 root root   480 May  7  2017 network.target
-rw-r--r--  1 root root   514 May  7  2017 nss-lookup.target
-rw-r--r--  1 root root   473 May  7  2017 nss-user-lookup.target
-rw-r--r--  1 root root   261 Aug  3  2016 owfs.service
-rw-r--r--  1 root root   215 Aug  3  2016 owftpd.service
-rw-r--r--  1 root root   239 Aug  3  2016 owhttpd.service
-rw-r--r--  1 root root   241 Aug  3  2016 owserver.service
-rw-r--r--  1 root root   142 Aug  3  2016 owserver.socket
-rw-r--r--  1 root root   354 May  7  2017 paths.target
-rw-r--r--  1 root root   329 Nov 23  2014 plymouth-halt.service
-rw-r--r--  1 root root   343 Nov 23  2014 plymouth-kexec.service
lrwxrwxrwx  1 root root    27 Nov 23  2014 plymouth-log.service -> plymouth-read-write.service
-rw-r--r--  1 root root   338 Nov 23  2014 plymouth-poweroff.service
-rw-r--r--  1 root root   194 Nov 23  2014 plymouth-quit.service
-rw-r--r--  1 root root   202 Nov 23  2014 plymouth-quit-wait.service
-rw-r--r--  1 root root   244 Nov 23  2014 plymouth-read-write.service
-rw-r--r--  1 root root   333 Nov 23  2014 plymouth-reboot.service
lrwxrwxrwx  1 root root    21 Nov 23  2014 plymouth.service -> plymouth-quit.service
-rw-r--r--  1 root root   449 Nov 23  2014 plymouth-start.service
-rw-r--r--  1 root root   291 Nov 23  2014 plymouth-switch-root.service
-rw-r--r--  1 root root   500 May  7  2017 poweroff.target
drwxr-xr-x  2 root root  4096 Jul 25  2017 poweroff.target.wants
-rw-r--r--  1 root root   377 May  7  2017 printer.target
lrwxrwxrwx  1 root root    22 May  7  2017 procps.service -> systemd-sysctl.service
-rw-r--r--  1 root root   693 May  7  2017 proc-sys-fs-binfmt_misc.automount
-rw-r--r--  1 root root   603 May  7  2017 proc-sys-fs-binfmt_misc.mount
-rw-r--r--  1 root root   635 May  7  2017 quotaon.service
-rw-r--r--  1 root root   633 May  7  2017 rc-local.service
lrwxrwxrwx  1 root root    16 May  7  2017 rc.local.service -> rc-local.service
lrwxrwxrwx  1 root root     9 May  7  2017 reboot.service -> /dev/null
-rw-r--r--  1 root root   493 May  7  2017 reboot.target
drwxr-xr-x  2 root root  4096 Jul 25  2017 reboot.target.wants
-rw-r--r--  1 root root   396 May  7  2017 remote-fs-pre.target
-rw-r--r--  1 root root   498 May  7  2017 remote-fs.target
-rw-r--r--  1 root root   954 May  7  2017 rescue.service
-rw-r--r--  1 root root   486 May  7  2017 rescue.target
drwxr-xr-x  2 root root  4096 Jul 25  2017 rescue.target.wants
lrwxrwxrwx  1 root root     9 May  7  2017 rmnologin.service -> /dev/null
-rw-r--r--  1 root root   500 May  7  2017 rpcbind.target
-rw-r--r--  1 root root   348 Apr 11  2016 rpi-display-backlight.service
-rw-r--r--  1 root root   188 Feb 24  2014 rsync.service
-rw-r--r--  1 root root   290 Jan 24  2016 rsyslog.service
lrwxrwxrwx  1 root root    15 May  7  2017 runlevel0.target -> poweroff.target
lrwxrwxrwx  1 root root    13 May  7  2017 runlevel1.target -> rescue.target
drwxr-xr-x  2 root root  4096 Jul 25  2017 runlevel1.target.wants
lrwxrwxrwx  1 root root    17 May  7  2017 runlevel2.target -> multi-user.target
drwxr-xr-x  2 root root  4096 Jul 25  2017 runlevel2.target.wants
lrwxrwxrwx  1 root root    17 May  7  2017 runlevel3.target -> multi-user.target
drwxr-xr-x  2 root root  4096 Jul 25  2017 runlevel3.target.wants
lrwxrwxrwx  1 root root    17 May  7  2017 runlevel4.target -> multi-user.target
drwxr-xr-x  2 root root  4096 Jul 25  2017 runlevel4.target.wants
lrwxrwxrwx  1 root root    16 May  7  2017 runlevel5.target -> graphical.target
drwxr-xr-x  2 root root  4096 Jul 25  2017 runlevel5.target.wants
lrwxrwxrwx  1 root root    13 May  7  2017 runlevel6.target -> reboot.target
lrwxrwxrwx  1 root root     9 Nov 21 19:01 samba.service -> /dev/null
lrwxrwxrwx  1 root root     9 May  7  2017 sendsigs.service -> /dev/null
-rw-r--r--  1 root root  1038 May  7  2017 serial-getty@.service
-rw-r--r--  1 root root   402 May  7  2017 shutdown.target
drwxr-xr-x  2 root root  4096 May 27  2016 shutdown.target.wants
-rw-r--r--  1 root root   362 May  7  2017 sigpwr.target
lrwxrwxrwx  1 root root     9 May  7  2017 single.service -> /dev/null
-rw-r--r--  1 root root   420 May  7  2017 sleep.target
-rw-r--r--  1 root root   403 May  7  2017 -.slice
-rw-r--r--  1 root root   409 May  7  2017 slices.target
-rw-r--r--  1 root root   380 May  7  2017 smartcard.target
-rw-r--r--  1 root root   356 May  7  2017 sockets.target
drwxr-xr-x  2 root root  4096 Jul 25  2017 sockets.target.wants
-rw-r--r--  1 root root   380 May  7  2017 sound.target
-rw-r--r--  1 root root   404 Nov 18 11:52 ssh.service
-rw-r--r--  1 root root   196 Nov 18 11:52 ssh@.service
-rw-r--r--  1 root root   216 Nov 18 11:50 ssh.socket
-rw-r--r--  1 root root   310 Dec 20  2016 sshswitch.service
lrwxrwxrwx  1 root root     9 May  7  2017 stop-bootlogd.service -> /dev/null
lrwxrwxrwx  1 root root     9 May  7  2017 stop-bootlogd-single.service -> /dev/null
-rw-r--r--  1 root root   272 Aug  8  2017 sudo.service
-rw-r--r--  1 root root   441 May  7  2017 suspend.target
-rw-r--r--  1 root root   353 May  7  2017 swap.target
-rw-r--r--  1 root root   681 May  7  2017 sys-fs-fuse-connections.mount
-rw-r--r--  1 root root   518 May  7  2017 sysinit.target
drwxr-xr-x  2 root root  4096 Jul 25  2017 sysinit.target.wants
-rw-r--r--  1 root root   719 May  7  2017 sys-kernel-config.mount
-rw-r--r--  1 root root   662 May  7  2017 sys-kernel-debug.mount
-rw-r--r--  1 root root  1328 May  7  2017 syslog.socket
-rw-r--r--  1 root root   646 May  7  2017 systemd-ask-password-console.path
-rw-r--r--  1 root root   653 May  7  2017 systemd-ask-password-console.service
-rw-r--r--  1 root root   407 Nov 23  2014 systemd-ask-password-plymouth.path
-rw-r--r--  1 root root   384 Nov 23  2014 systemd-ask-password-plymouth.service
-rw-r--r--  1 root root   574 May  7  2017 systemd-ask-password-wall.path
-rw-r--r--  1 root root   681 May  7  2017 systemd-ask-password-wall.service
-rw-r--r--  1 root root   776 May  7  2017 systemd-backlight@.service
-rw-r--r--  1 root root  1011 May  7  2017 systemd-binfmt.service
-rw-r--r--  1 root root   725 May  7  2017 systemd-fsck-root.service
-rw-r--r--  1 root root   678 May  7  2017 systemd-fsck@.service
-rw-r--r--  1 root root   544 May  7  2017 systemd-halt.service
-rw-r--r--  1 root root   501 May  7  2017 systemd-hibernate.service
-rw-r--r--  1 root root   710 May  7  2017 systemd-hostnamed.service
-rw-r--r--  1 root root   519 May  7  2017 systemd-hybrid-sleep.service
-rw-r--r--  1 root root   480 May  7  2017 systemd-initctl.service
-rw-r--r--  1 root root   524 May  7  2017 systemd-initctl.socket
-rw-r--r--  1 root root  1090 May  7  2017 systemd-journald-dev-log.socket
-rw-r--r--  1 root root  1049 May  7  2017 systemd-journald.service
-rw-r--r--  1 root root   842 May  7  2017 systemd-journald.socket
-rw-r--r--  1 root root   698 May  7  2017 systemd-journal-flush.service
-rw-r--r--  1 root root   557 May  7  2017 systemd-kexec.service
-rw-r--r--  1 root root   691 May  7  2017 systemd-localed.service
-rw-r--r--  1 root root  1165 May  7  2017 systemd-logind.service
-rw-r--r--  1 root root   795 May  7  2017 systemd-machined.service
-rw-r--r--  1 root root  1025 May  7  2017 systemd-modules-load.service
-rw-r--r--  1 root root   936 May  7  2017 systemd-networkd.service
-rw-r--r--  1 root root   685 May  7  2017 systemd-networkd-wait-online.service
-rw-r--r--  1 root root   605 May  7  2017 systemd-nspawn@.service
-rw-r--r--  1 root root   553 May  7  2017 systemd-poweroff.service
-rw-r--r--  1 root root   681 May  7  2017 systemd-quotacheck.service
-rw-r--r--  1 root root   769 May  7  2017 systemd-random-seed.service
-rw-r--r--  1 root root   841 May  7  2017 systemd-readahead-collect.service
-rw-r--r--  1 root root   638 May  7  2017 systemd-readahead-done.service
-rw-r--r--  1 root root   635 May  7  2017 systemd-readahead-done.timer
-rw-r--r--  1 root root   555 May  7  2017 systemd-readahead-drop.service
-rw-r--r--  1 root root   753 May  7  2017 systemd-readahead-replay.service
-rw-r--r--  1 root root   548 May  7  2017 systemd-reboot.service
-rw-r--r--  1 root root   824 May  7  2017 systemd-remount-fs.service
-rw-r--r--  1 root root   686 May  7  2017 systemd-resolved.service
-rw-r--r--  1 root root   758 May  7  2017 systemd-rfkill@.service
-rw-r--r--  1 root root   271 May  7  2017 systemd-setup-dgram-qlen.service
-rw-r--r--  1 root root   475 May  7  2017 systemd-shutdownd.service
-rw-r--r--  1 root root   528 May  7  2017 systemd-shutdownd.socket
-rw-r--r--  1 root root   497 May  7  2017 systemd-suspend.service
-rw-r--r--  1 root root   707 May  7  2017 systemd-sysctl.service
-rw-r--r--  1 root root   655 May  7  2017 systemd-timedated.service
-rw-r--r--  1 root root  1032 May  7  2017 systemd-timesyncd.service
-rw-r--r--  1 root root   665 May  7  2017 systemd-tmpfiles-clean.service
-rw-r--r--  1 root root   450 May  7  2017 systemd-tmpfiles-clean.timer
-rw-r--r--  1 root root   770 May  7  2017 systemd-tmpfiles-setup-dev.service
-rw-r--r--  1 root root   750 May  7  2017 systemd-tmpfiles-setup.service
-rw-r--r--  1 root root   578 May  7  2017 systemd-udevd-control.socket
-rw-r--r--  1 root root   575 May  7  2017 systemd-udevd-kernel.socket
-rw-r--r--  1 root root   826 May  7  2017 systemd-udevd.service
-rw-r--r--  1 root root   823 May  7  2017 systemd-udev-settle.service
-rw-r--r--  1 root root   715 May  7  2017 systemd-udev-trigger.service
-rw-r--r--  1 root root   757 May  7  2017 systemd-update-utmp-runlevel.service
-rw-r--r--  1 root root   821 May  7  2017 systemd-update-utmp.service
-rw-r--r--  1 root root   588 May  7  2017 systemd-user-sessions.service
-rw-r--r--  1 root root   433 May  7  2017 system.slice
-rw-r--r--  1 root root   652 May  7  2017 system-update.target
-rw-r--r--  1 root root   355 May  7  2017 timers.target
drwxr-xr-x  2 root root  4096 Jul 25  2017 timers.target.wants
-rw-r--r--  1 root root   395 May  7  2017 time-sync.target
-rw-r--r--  1 root root   661 May  7  2017 tmp.mount
-rw-r--r--  1 root root   217 May  7  2017 udev-finish.service
lrwxrwxrwx  1 root root    21 May  7  2017 udev.service -> systemd-udevd.service
lrwxrwxrwx  1 root root     9 May  7  2017 umountfs.service -> /dev/null
lrwxrwxrwx  1 root root     9 May  7  2017 umountnfs.service -> /dev/null
lrwxrwxrwx  1 root root     9 May  7  2017 umountroot.service -> /dev/null
-rw-r--r--  1 root root   417 May  7  2017 umount.target
lrwxrwxrwx  1 root root    27 May  7  2017 urandom.service -> systemd-random-seed.service
-rw-r--r--  1 root root   150 Aug 18  2014 usb_modeswitch@.service
-rw-r--r--  1 root root   497 May  7  2017 user@.service
-rw-r--r--  1 root root   392 May  7  2017 user.slice
-rw-r--r--  1 root root   244 Oct 16 12:41 wpa_supplicant.service
lrwxrwxrwx  1 root root     9 May  7  2017 x11-common.service -> /dev/null

**Comment by john30** [comment]
oh I see, since you didn't use a release package but built it yourself, you'll have to copy the https://github.com/john30/ebusd/blob/master/contrib/debian/default/ebusd and https://github.com/john30/ebusd/blob/master/contrib/debian/systemd/ebusd.service to the right folders (/etc/default for default/ebusd, /lib/systemd/system for ebusd.service).

**Comment by szczukot** [comment]
No i have:

pi@raspberrypi:~ $ sudo systemctl enable ebusd
pi@raspberrypi:~ $ sudo chkconfig ebusd on
ebusd: unknown service

**Comment by john30** [comment]
what do you mean by that? did you copy the files already?

**Comment by szczukot** [comment]
ls /etc/default
....
-rw-r--r-- 1 pi   pi   1372 Feb 17 11:12 ebusd
....

ls /lib/systemd/system
...
-rw-r--r-- 1 pi   pi    309 Feb  9 16:57 ebusd.service
....

**Comment by john30** [comment]
does ebusd appear in `systemctl list-units`?

**Comment by szczukot** [comment]
After reeboot, i see:

> systemctl list-units
> ebusd.service         loaded active     running         ebusd, the daemon for communication with eBUS

still
pi@raspberrypi:~ $ sudo chkconfig ebusd on
ebusd: unknown service

ps ax
 842 ?        Ds     0:00 /usr/bin/ebusd --scanconfig -d /dev/ttyUSB1

and

pi@raspberrypi:~ $ tail /var/log/ebusd.log -f
2018-02-17 15:12:42.123 [main notice] ebusd 3.1.v3.1-22-gdaf771e started with auto scan
and nothing else

**Comment by john30** [comment]
your OS is systemd based, consequently usign chkconfig does not make sense if you've installed the systemd file. use systemctl instead

**Comment by szczukot** [comment]
thanks
