### ISSUE TITLE
Cannot run docker on raspi3 - please add arm build

### ISSUE THREAD

**Issue by andig** [john30/ebusd#168]
This happens:

	pi@ebus2:~ $ sudo docker run john30/ebusd
	Unable to find image 'john30/ebusd:latest' locally
	latest: Pulling from john30/ebusd
	723254a2c089: Pull complete
	fb30d9e9be5b: Pull complete
	840892f6e7c7: Pull complete
	aa49144da917: Pull complete
	15d48e829feb: Pull complete
	d3d382abe717: Pull complete
	abfed5a15f06: Pull complete
	Digest: sha256:24337cacac622d3cfca3e125b9c2bba34e2f285f173a5b743bf7d11136646aae
	Status: Downloaded newer image for john30/ebusd:latest
	standard_init_linux.go:195: exec user process caused "exec format error"

Seems the build process does not (yet) produce an arm build :)

**Comment by andig** [comment]
Thinking about it an ARM build might not be too beneficial, at least not for Raspbian since ebus already provides installation packages. Closing for time being.

**Comment by john30** [comment]
sure, the builds are all based on amd64, so that wouldn't work anyway

**Comment by semenoh** [comment]
this is exactly my case. I'm trying to setup ebusd in HomeAssistant using docker but I can not because of amd64 architecture. Is it possible to make arm version beside amd ?

**Comment by john30** [comment]
arm is available now as well in the docker images
