### ISSUE TITLE
Write error : ERR: element not found

### ISSUE THREAD

**Issue by minscof** [john30/ebusd#180]
I try this command
`ebusctl write -c bai SetMode "132;0.5;4.0;0;0;0;0;0;0;0"`

and I get this error
`ERR: element not found`

and these logs
2018-04-01 20:56:20.604 [bus error] prepare message part 0: ERR: element not found
2018-04-01 20:56:20.604 [main error] write bai SetMode: ERR: element not found

however, if I do
`ebusctl f -w`

the reply shows that SetMode exists

bai clearerrorhistory = no data stored
bai DSNOffset = no data stored
bai FlowsetHcMax = no data stored
bai FlowsetHwcMax = no data stored
bai SetFactoryValues = no data stored
bai SetFlowTempMax = no data stored
bai SetFlowTempMin = no data stored
bai SetMode1 = no data stored
**bai SetMode = no data stored**
bai SetTempDesired = no data stored
broadcast id = no data stored
broadcast queryexistence = no data stored
memory eeprom = no data stored
memory ram = no data stored

this is the SetMode definition in the included 08.bai.csv 
`r;w,,SetMode,Operation Mode,,,,00,,,hcmode,,,,flowtempdesired,,temp1,,,,hwctempdesired,,temp1,,,,hwcflowtempdesired,,temp0,,,,,,IGN:1,,,,disablehc,,BI0,,,,disablehwctapping,,BI1,,,,disablehwcload,,BI2,,,,,,IGN:1,,,,remoteControlHcPump,,BI0,,,,releaseBackup,,BI1,,,,releaseCooling,,BI2,,,,`

What I have to do ?

Thanks

**Comment by john30** [comment]
already answered here #179
