### ISSUE TITLE
Update to last git and ERR: invalid position for

### ISSUE THREAD

**Issue by tikismoke** [john30/ebusd#185]
Hi John,

I just update to last git version and for somes value i get this now:
```
ebusctl find 
boiler circuit_pressure = 1.0 (ERR: invalid position for 331506210400970040 / 0a17800d18ff7f00800a00)

```

my csv looks like this:
```
 ebusctl find -f
r1,boiler,circuit_pressure,,,15,0621,00970040,ign,s,IGN:8,,,,Circuit pressure,s,SIN,10,bar,,ign,s,IGN:*,,,


I got value before update but not remember the version number of ebusd i was using.
It do this only for somes value not all.

It's a TEM111.CSV

```

**Comment by tikismoke** [comment]
All the reverse engineering search to get value is here:
https://github.com/john30/ebusd-configuration/issues/27

**Comment by john30** [comment]
the definition is not valid for the received slave data. the data is 10 bytes long, 8 bytes are skipped with the first IGN field, then the two bytes with the actual value follow. but your definition contains another ignored field with variable length and for that one, not a single byte is left in the data, which is not allowed (any field needs to cover at least one byte or bit). so by removing the last field from the definition everything should be fine

**Comment by semenoh** [comment]
Hi, I have similar issue:
`ebusctl f` prints out a lot of fields but almost all of them are `no data stored` but I noticed that after I try to read it next time i run `ebusctl f` it contains some data. So I created simple script that reads all the fields one by one and now most of them contain some values. But there are a lot of them that contain `(ERR: invalid position for ...)`
here they are:
```
bai AccessoriesOne =  (ERR: invalid position for 3108b509030d4b04 / 00)
bai AccessoriesTwo =  (ERR: invalid position for 3108b509030d4c04 / 00)
bai BlockTimeHcMax =  (ERR: invalid position for 3108b509030d0904 / 00)
bai DCFTimeDate =  (ERR: invalid position for 3108b509030de500 / 07361f0000000000)
bai EBusHeatcontrol =  (ERR: invalid position for 3108b509030d0004 / 00)
bai externalFlowTempDesired =  (ERR: invalid position for 3108b509030d2500 / 00)
bai ExtFlowTempDesiredMin =  (ERR: invalid position for 3108b509030d6e04 / 00)
bai FanSpeedOffsetMax =  (ERR: invalid position for 3108b509030d2504 / 00)
bai FanSpeedOffsetMin =  (ERR: invalid position for 3108b509030d2404 / 00)
bai FlowsetHwcMax =  (ERR: invalid position for 3108b509030d0f04 / 00)
bai FlowSetPotmeter =  (ERR: invalid position for 3108b509030df003 / 00)
bai HcPumpMode =  (ERR: invalid position for 3108b509030d4904 / 00)
bai HoursTillService =  (ERR: invalid position for 3108b509030d2004 / 00)
bai HwcPostrunTime =  (ERR: invalid position for 3108b509030d1104 / 00)
bai HwcSetPotmeter =  (ERR: invalid position for 3108b509030df103 / 00)
bai HwcTempDesired =  (ERR: invalid position for 3108b509030dea03 / 00)
bai HwcTempMax =  (ERR: invalid position for 3108b509030d4304 / 00)
bai PartloadHcKW =  (ERR: invalid position for 3108b509030d0704 / 00)
bai PartloadHwcKW =  (ERR: invalid position for 3108b509030d0804 / 00)
bai ReturnRegulation =  (ERR: invalid position for 3108b509030d0c04 / 00)
bai SecondPumpMode =  (ERR: invalid position for 3108b509030d0b04 / 00)
bai SolarPostHeat =  (ERR: invalid position for 3108b509030d7304 / 00)
bai Status16 =  (ERR: invalid position for 3108b5040116 / 00)
bai Status =  (ERR: invalid position for 3108b5110103 / 00)
bai StorageLoadTimeMax =  (ERR: invalid position for 3108b509030d1204 / 00)
bai StoragereleaseClock =  (ERR: invalid position for 3108b509030d4704 / 00)
bai ValveMode =  (ERR: invalid position for 3108b509030d2a04 / 00)
bai VortexFlowSensor =  (ERR: invalid position for 3108b509030dd500 / 00)
bai WarmstartOffset =  (ERR: invalid position for 3108b509030d1004 / 00)
bai WPPostrunTime =  (ERR: invalid position for 3108b509030df703 / 00)
```
So should I remove all of them from some config file ? How do I know which file ? Is there a reason to create a separate file that suets model of my boiler better and make a pull request ?

**Comment by john30** [comment]
a script for reading all messages is already in [contrib/scripts/readall.sh](https://github.com/john30/ebusd/blob/master/contrib/scripts/readall.sh).
It seems the device is not willing to answer the queries, as the answer has zero length in your examples.
you can remove them from the bai config file. you "ebuscl info" output will tell you more about which file to look for
