### ISSUE TITLE
docker support

### ISSUE THREAD

**Issue by scantineau** [john30/ebusd#189]
Hi John,

Do you think it is possible to create a docker image ?

**Comment by john30** [comment]
already there: https://hub.docker.com/r/john30/ebusd/

**Comment by scantineau** [comment]
Ok thanks. Could be nice to define an ENV variable to choose if we want English or German configuration files :-)

**Comment by john30** [comment]
this will be available automatically once the config files were switched to ebusd 3 version to support multiple languages
