### ISSUE TITLE
Feature request: command history in ebusctl

### ISSUE THREAD

**Issue by Dinth** [john30/ebusd#193]
Just a small suggestion, it would be very helpful to have a "bash-like" command history in ebusctl. When im troubleshooting ebus or writing a Home Automation script sometimes i run same or almost same ebusctl commands hundreds of times, for example to check if my script has worked. Right now i need to retype a command each time i want to rerun it, it would be very nice to be able to scroll through recent commands using arrows.

**Comment by andig** [comment]
I‘m using thr bash history for that purpose.

**Comment by john30** [comment]
me too, it's a lot of effort implementing such behaviour in ebusctl and there are other ways to achieve the same result
