### ISSUE TITLE
What is the problem with the esera Ethernet adapter?

### ISSUE THREAD

**Issue by Qowy** [john30/ebusd#200]
On March 11th it was added to the wiki that this adapter is known to not work reliably. However several people seem to have connected to it with something like -d 192.168.1.2:5000

What prompted labeling it as unreliable / not supported since much of the logic should be the same as the USB one (According to the company after an inquiry).

It would be an easier solution for me than USB + RaPi

**Comment by john30** [comment]
one of the main issues is the potentiometer, as the slightest incorrect adjustment will lead to not communicating correctly. the second thing is the buffering in the network variant and the latency of the used serial-to-ethernet adapter which will also lead to wrong communcation.
