### ISSUE TITLE
Hc1SFMode writing

### ISSUE THREAD

**Issue by z1mEk** [john30/ebusd#203]
I have a CalorMatic 470. I set in the configuration file [15.470.csv]: "r,w,,Hc1SFMode,HC_1SFMode,,,...", and now I can set values from 0 to 6 (e.g. ebusd w -c 470 Hc1SFMode 3). Why can not I set 7 and 8? I get the message 'done' but the value goes back to 'none'.

**Comment by john30** [comment]
this is an [ebusd-configuration](https://github.com/john30/ebusd-configuration) issue rather than an ebusd one.
anyway, if your device is not willing to accept the higher values, I would assume that it just does not support these.
