### ISSUE TITLE
.deb release for Raspbian Stretch

### ISSUE THREAD

**Issue by mivola** [john30/ebusd#216]
Hi,

is there a plan to offer a binary release for Raspbian Strech on RaspberryPi/armhf? Or should the "ebusd-3.2_armhf-jessie.deb" be sufficient?

Thanks,
Michael

**Comment by john30** [comment]
at some point, yes. gor the time being, the jessie release should potentially work as well

**Comment by mivola** [comment]
Thank you for the quick response. I'll give it a try ...

**Comment by mivola** [comment]
I just did the installation and it seems to be working fine. Now I just need to understand & get the new ebus-configuration up & running ...

**Comment by Dinth** [comment]
>is there a plan to offer a binary release for Raspbian Strech on RaspberryPi/armhf? Or should the "ebusd-3.2_armhf-jessie.deb" be sufficient?

Ive been using it for a while without any problem
