### ISSUE TITLE
docker image for raspberry pi

### ISSUE THREAD

**Issue by lukicsl** [john30/ebusd#221]
Currently on docker there is an image which supports amd64. 
Would it be possible to have manifest support and and add arm achitecture too?
Seen the issue [https://github.com/john30/ebusd/issues/168](url), which was closed by the requester.

`# docker run mplatform/mquery john30/ebusd
Image: john30/ebusd
 * Manifest List: No
 * Supports: amd64/linux
`

**Comment by lukicsl** [comment]
Would it be possible to get the Dockerfile, so I could create my own image.
Or put the docker project to the repository

**Comment by john30** [comment]
https://github.com/john30/ebusd/tree/master/contrib/docker
