### ISSUE TITLE
Possible issue with Ebus write

### ISSUE THREAD

**Issue by kolibrie-eric** [john30/ebusd#228]
I am trying to determine whether a write to the Ebus is correct or not. The issue can be explained as follows:

I receive a bus notice from the thermostat that looks like this:

1. _[bus notice] <1008b5100900006effffff0600007c0001019a00_

Which translates using the message definition in hcmode.inc (slightly altered wrt to the original definition. I made it an active write and change the first IGN:1 into temp0):

2. _[update notice] received write hmu SetMode QQ=10: auto;55.0;-;-;-;0;1;1;0;0;0_

When I write that same message back to the bus, the message becomes (new master):

3. _[update notice] sent write hmu SetMode QQ=31: auto;55.0;-;-;-;0;1;1;0;0;0_

So far so good. The bus notice is:

4. _[bus notice] >3108b5100900006effffff06000029<0001019a>00_

Notice the brackets <> around the slave part. Are those really written to the bus or are they indicating something else? Can't find any clues in the documentation.

Thanks for your help,
Eric

**Comment by john30** [comment]
the bracket indicates the direction of the bytes following the bracket, so ">3108b5100900006effffff06000029<0001019a>00" means:
1. ebusd sent 3108b5100900006effffff06000029
2. the slave answered 0001019a
3. ebusd acknowledged with 00
The last byte of what ebusd sent initially is different to the original message, as this is the CRC which also includes the master source address (first byte).
[see here for more details about the message structure.](https://github.com/john30/ebusd/wiki/eBUS-background)
