### ISSUE TITLE
http force read on the bus

### ISSUE THREAD

**Issue by scantineau** [john30/ebusd#233]
Hi John,

Could be nice if we had an option to force ebusd to read on the bus.

When I use ebusctl r something the value is updated but if I use the http way, it's not.

**Comment by john30** [comment]
use [maxage](https://github.com/john30/ebusd/wiki/3.2.-HTTP-client#introduction) request parameter with value 0

**Comment by joergensen70** [comment]
Hi, this is actually what I was looking for. But maxage=0 seems not to work for me.
I try to read all the devices from the bus with every request. I tried to poll just the data points I need but these many requests took too long. It's easier to make a complete request and decode the data afterwards.
Doing this the request command looks like this xhr.open("GET", "/data?maxage=0");
I'm getting the expected data but many datapoints very outdated.
Can you help?

**Comment by john30** [comment]
by intention it only works when querying a single message, but not for ranges like all messages or all messages of a certain device
