### ISSUE TITLE
Intermittent consecutive read errors

### ISSUE THREAD

**Issue by stefaanv** [john30/ebusd#238]
I use ebusd to read selected parameters from my heater and thermostat and store the received values in a database.  This usually works fine but from time to time I get strings of **'ERR: element not found'** responses.  Once this behaviour starts, it usually lasts for a couple of seconds and resolves automatically.
This is obviously not a life and death situation but I'm curious to know more about why this happens and if it can be solved by tweaking some of the ebusd run parameters.

My program is written in node.js, opens a TCP connection to ebusd using **net.createConnection()** and sends requests in the form ```read -f -c <circuit> <parameter>```.  A next request is sent immediately after reception of the previous answer unless all requests have been sent, in which case the connection is closed.  This cycle is repeated every 30 seconds.

By the way, many thanks for this great application, I really love it.  It's running on a Synology NAS within a docker container.

Below is log output of two cycles where things go wrong in the seonds cycle.
> CycleCounter = 2681
> connected to the ebusd server
> RoomTemp --> 23.25
> hc1heatcurve --> 1.5
> OutsideTemp --> -1.31
> FlowTempDesired --> 0
> FlowTemp --> 46.38
> Flame --> off
> ReturnTemp --> 46.19
> disconnected from server
> Data succesfully written to database
> 
> CycleCounter = 2682
> connected to the ebusd server
> Received 'ERR: element not found' for RoomTemp
> Received 'ERR: element not found' for hc1heatcurve
> Received 'ERR: element not found' for OutsideTemp
> Received 'ERR: element not found' for FlowTempDesired
> Received 'ERR: element not found' for FlowTemp
> Received 'ERR: element not found' for Flame
> Received 'ERR: element not found' for ReturnTemp
> disconnected from server

The startup parameters are **"-f -s -d 192.168.0.36:5000 --enabledefine --accesslevel '*'"**
I'm using a [esera thernet ebus koppler](https://www.esera.de/produkte/ebus/142/ebus-koppler-ethernet) a bus coupler.

Below is the result of **ebusctl info**
>root@ebus:/# ebusctl info                                                                         
>version: ebusd 3.2.v3.2                                                                           
>update check: revision v3.2-25-gc475e6c available                                                 
>access: *                                                                                         
>signal: acquired                                                                                  
>symbol rate: 101                                                                                  
>max symbol rate: 118                                                                              
>min arbitration micros: 21                                                                        
>max arbitration micros: 298                                                                       
>min symbol latency: 6                                                                             
>max symbol latency: 22                                                                            
>reconnects: 0                                                                                     
>masters: 3                                                                                        
>messages: 433                                                                                     
>conditional: 3                                                                                    
>poll: 1                                                                                           
>update: 9                                                                                         
>address 03: master #11                                                                            
>address 08: slave #11, scanned "MF=Vaillant;ID=BAI00;SW=0414;HW=7401", loaded "vaillant/bai.308523
.inc" ([HW=7401]), "vaillant/08.bai.csv"                                                          
>address 10: master #2                                                                             
>address 15: slave #2, scanned "MF=Vaillant;ID=F4700;SW=0114;HW=6102", loaded "vaillant/15.f47.csv"
>address 31: master #8, ebusd                                                                      
>address 36: slave #8, ebusd

**Comment by john30** [comment]
you'd have to look at the ebusd.log file and check the answer from the slave for invalid/short answer.

**Comment by john30** [comment]
closed due to inactivity
