### ISSUE TITLE
The error about installing eBus SDK in Ubuntu

### ISSUE THREAD

**Issue by nicaima** [john30/ebusd#24]
Hello,
When I install the eBUS SDK in Ubuntu14.04 64bit LTS,the ebUniversalProForEthernet-x86_64.ko cannot be build seccesful,the error is :/opt/pleora/ebus_sdk/Ubuntu-14.04-x86_64/module/ebUniversalProForEthernet/OS_KMLNetwork.c:96:2: error: too many arguments to function ‘sock_sendmsg’
lReturn = sock_sendmsg( lSocket, &lMessage, lTotalSize );
^
Thank a lot!
![error1](https://cloud.githubusercontent.com/assets/17984181/19334428/7a2ef352-912e-11e6-95cc-be8b728a9206.png)

**Comment by john30** [comment]
This is the wrong project!
ebusd is about heating control
