### ISSUE TITLE
--mqttchanges is always enabled

### ISSUE THREAD

**Issue by peti69** [john30/ebusd#241]
Hi John,

values from messages arriving on the bus are only forwarded to MQTT if they have changed. Looks like that the option -mqttchanges has no effect. 

I think the option --mqttchanges is always enabled since the global variable g_onlyChanges is initailzed to true. 

Kind regards,
Peter

**Comment by andig** [comment]
That would not be what the readme says: https://github.com/john30/ebusd/search?q=mqttchanges&unscoped_q=mqttchanges

**Comment by john30** [comment]
too bad, thanks for finding and reporting!
