### ISSUE TITLE
Ebusd logfile does not rotate

### ISSUE THREAD

**Issue by klaasdc** [john30/ebusd#245]
I installed ebusd from the package ebusd-3.2_armhf-jessie_mqtt1.deb on a raspberry pi. I recently noticed that the logfile /var/log/ebusd.log had become >250MB. Digging further, the logrotate script seems to be ignored because of an error:
`error: Ignoring ebusd because of bad file mode - must be 0644 or 0444.`

II have not touched this file after installing the package. Could it be that the installscript left this file executable? Manually changing the mode of /etc/logrotate.d/ebusd to be non-executable made the logs rotate as expected.

**Comment by john30** [comment]
thanks for spotting this!
