### ISSUE TITLE
Problem with hex command of ebusctl

### ISSUE THREAD

**Issue by TheEPIX** [john30/ebusd#248]
I'm just a noob with ebus, but sometimes the fog ist clearing....
So I'm just trying to find out the communication of my WTC25 (weishaupt)
The actual problem is also the hex-writing:

I don't know how to use the "hex" command :-(

A example in Fhem uses
`ebusctl write -h 0850030126 `
to get some answers

I tried this example and also 
```
ebusctl write -h hex0850030126 --enablehex
ebusctl write -h hex 0850030126 --enablehex
ebusctl write -h 0850030126 --enablehex
ebusctl write -hex0850030126 --enablehex
```
nothing bit the "usage-information" of ebusctl...

Any hint (if possibile "simple" for a noob)

_Originally posted by @TheEPIX in https://github.com/_render_node/MDEyOklzc3VlQ29tbWVudDQ1MTI0NDI1NQ==/timeline/issue_comment#issuecomment-451244255_

**Comment by john30** [comment]
`--enablehex` needs to be added to /etc/default/ebusd, not to the actual query. see [here](https://github.com/john30/ebusd/wiki/2.-Run#daemon-options)
after the hex command is enabled, you need to restart ebusd. then you can start querying using e.g. `ebusctl hex 0850030126`
