### ISSUE TITLE
Meaning of --pollinterval and definition of poll cycles

### ISSUE THREAD

**Issue by peti69** [john30/ebusd#250]
Hi, is my understanding correct that --pollinterval PollInterval defines the time interval between two successive poll-reads? That is, after PollInterval seconds the next poll-read message is sent and when all messages marked with type r1 have been processed the next poll-cycle starts. A message with type r1 will therefore be triggered each "PollInterval * (number of r1 messages)" seconds.

**Comment by john30** [comment]
read the [wiki](https://github.com/john30/ebusd/wiki/4.1.-Message-definition#message-definition):

> When appending a digit 1-9 to the normal "read" type, the master-slave read message will be polled in regular intervals. The appended digit is the polling priority, i.e. messages with priority 1 are polled in each poll cycle, priority 2 messages only in every second poll cycle and so on.

**Comment by peti69** [comment]
Thanks. I have read the before posting my question. From the wiki I understood that ALL read-messages marked with r1 are fired every PollInterval seconds. But later I discovered that this is not the case and that only one read-message is sent within PollInterval seconds.
