### ISSUE TITLE
CMake: Test HAVE_DIRECT_FLOAT_FORMAT - Failed

### ISSUE THREAD

**Issue by andr2000** [john30/ebusd#254]
Trying to cross-compile with cmake produces the following errors during configuration:
```
-- Performing Test HAVE_DIRECT_FLOAT_FORMAT
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   HAVE_DIRECT_FLOAT_FORMAT_EXITCODE (advanced)
For details see /home/a2k/projects/vaillant/sources/ebusd-build/TryRunResults.cmake
-- Performing Test HAVE_DIRECT_FLOAT_FORMAT - Failed
-- Configuring incomplete, errors occurred!
```
The issues seems to be that CMake tries to run target code on host and fails

**Comment by john30** [comment]
the cmake is not desired to used for cross compilation yet. I wonder how one can determine availability of certain compiler features in such an environment then...

**Comment by andr2000** [comment]
This is no problem when used with Yocto which is my case.
Yocto also provides cross-SDK, so there is no worry about the environment as well

**Comment by john30** [comment]
but that does not solve the problem, right?

**Comment by andr2000** [comment]
Exactly, because the CMakeLists is written in a way it requires the cross-compiled test to run on the host which is obviously not possible

**Comment by john30** [comment]
exactly. so you can't cross compile right now, as said before

**Comment by andr2000** [comment]
Hm, but it can be fixed.
I can cross-compile using autotools, but not CMake

**Comment by john30** [comment]
then please go ahead.
the autotools do the testing for compiler features on the build machine as well and not using the cross compiler, otherwise they'd fail as well

**Comment by andr2000** [comment]
Pardon me, but by saying "go ahead" you mean what?

**Comment by john30** [comment]
if you can fix it, then please do so, as I wouldn't know how that should be possible
