### ISSUE TITLE
Docker image rather big

### ISSUE THREAD

**Issue by lukicsl** [john30/ebusd#258]
I have built a docker image from ebusd/contrib/docker/release for armhf.
I was suprised how big the resulting image is: 150MB

looking at the Dockerfile I see that possibly to much is installed at the start off:

```
RUN apt-get update && apt-get install -y \
    logrotate libmosquitto1 libstdc++6 libc6 libgcc1 \
    curl \
    && rm -rf /var/lib/apt/lists/*
```

is `libstdc++6 libc6 libgcc1 curl `needed for runtime?

**Comment by john30** [comment]
the libs are needed for running the binary.
curl is needed for downloading the binary from git
