### ISSUE TITLE
Problem with read on VR 700

### ISSUE THREAD

**Issue by madito** [john30/ebusd#261]
Hi,

I have problems getting the values ​​from the VR700 automatically.

My config is:

> EBUSD_OPTS="--scanconfig --mqtthost=IP --mqttport=1883 --mqttjson --mqttlog --httpport=8080 --configlang=en"

If I make an ebusctl info, I get:

> root@raspberrypi:~# ebusctl info
> version: ebusd 3.3.v3.3-12-g5af41df
> update check: revision v3.3-4-g212b22d available, broadcast.csv: different version available, vaillant/15.700.csv: different version available, vaillant/broadcast.csv: different version available, vaillant/errors.inc: different version available, vaillant/hcmode.inc: different version available
> signal: acquired
> symbol rate: 37
> max symbol rate: 131
> min arbitration micros: 817
> max arbitration micros: 864
> min symbol latency: 5
> max symbol latency: 6
> reconnects: 0
> masters: 5
> messages: 475
> conditional: 0
> poll: 0
> update: 9
> address 00: master #1
> address 03: master #11
> address 08: slave #11, scanned "MF=Vaillant;ID=HMU01;SW=0305;HW=8802", loaded "vaillant/08.hmu.csv"
> address 10: master #2
> address 15: slave #2, scanned "MF=Vaillant;ID=70000;SW=0510;HW=6403", loaded "vaillant/15.700.csv"
> address 31: master #8, ebusd
> address 36: slave #8, ebusd
> address 52: slave, scanned "MF=Vaillant;ID=VR_70;SW=0109;HW=2903", loaded "vaillant/52.vr_70.csv"
> address 71: master #9
> address 76: slave #9, scanned "MF=Vaillant;ID=VWZIO;SW=0111;HW=0103"
> address e8: slave, scanned "MF=Vaillant;ID=FMU00;SW=0203;HW=6502"

However I do not get any data from the VR700, if I force the reading with the command: 

> root@raspberrypi:~# ebusctl read -c 700 Hc1HeatCurve
> 2

I get the result and it is updated from the JSON, but it is not updated.

In the ebusd.log I get a lot of unknown messages and none of the VR700.

Thanks for your great job!

**Comment by john30** [comment]
what do you mean with "I do not get any data from the VR700" exactly?
and what is "... it is updated from the JSON, but it is not updated" supposed to tell me?

**Comment by madito** [comment]
Hi John,

The ebusd detect de VR700 but no read any parameters all marqued like unknow.

But I execute "ebusctl read" and read the value correct, and the json show this value. The json show nulls values if not update the values manually, executing the ebusctl on command line.

Is like if the ebusd not process the data of VR 700 "automaticaly"

**Comment by madito** [comment]
You need the ebusd.log?? 

Thanksss

**Comment by john30** [comment]
ebusd is not intended to query all messages by itself. however, you can change the config to make ebusd query within the pollinterval (see start parameters) and you can also dynamcially change the poll priority of messages during runtime.
