### ISSUE TITLE
Docker Image not run on Raspberry Pi 3

### ISSUE THREAD

**Issue by SandnerSoft** [john30/ebusd#267]
Hi,

i change the Dockerfile to build on a RaspPi 3.

`FROM debian:stretch

RUN apt-get update && apt-get install -y \
    logrotate libmosquitto1 libstdc++6 libc6 libgcc1 \
    curl \
    && rm -rf /var/lib/apt/lists/*

LABEL maintainer "ebusd@ebusd.eu"

ENV EBUSD_VERSION 3.3
ENV EBUSD_ARCH armhf

LABEL version "${EBUSD_VERSION}-${EBUSD_ARCH}"

RUN curl -SL https://github.com/john30/ebusd/releases/download/v${EBUSD_VERSION}/ebusd-${EBUSD_VERSION}_${EBUSD_ARCH}-stretch_mqtt1.deb > ebusd.deb

RUN dpkg -i ebusd.deb

RUN rm ebusd.deb

EXPOSE 8888

COPY docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["-f", "--scanconfig"]`

my start command:
`sudo docker run -it --rm --name=ebusd --device=/dev/ttyebus -p 8888 nightstorm99/ebusd -f --scanconfig -d /dev/ttyebus --mqttport=1883 --mqtthost=192.168.1.66`

but then comes a error:
standard_init_linux.go:190: exec user process caused "exec format error"

any idea???
(sorry for my english)

greetings

**Comment by john30** [comment]
no idea, try google

**Comment by dkuschmierz** [comment]
Hi @SandnerSoft,

your script is almost working, but you forgot to set the right FROM ...

Here is a for me working Dockerfile:

```
FROM balenalib/raspberrypi3

RUN apt-get update && apt-get install -y \
    logrotate libmosquitto1 libstdc++6 libc6 libgcc1 \
    curl \
    && rm -rf /var/lib/apt/lists/*

RUN apt-get update && apt-get install -y \
    autoconf automake g++ make git \
    libmosquitto-dev \
    && rm -rf /var/lib/apt/lists/*

LABEL maintainer "ebusd@ebusd.eu"

ENV EBUSD_VERSION 3.4
ENV EBUSD_ARCH armhf
ENV UDEV=1

LABEL version "${EBUSD_VERSION}-${EBUSD_ARCH}-devel"

WORKDIR /build

RUN (curl -SL https://github.com/john30/ebusd/archive/master.tar.gz \
    | tar xz --strip-components=1) \
    && ./autogen.sh \
    && make install-strip

WORKDIR /

RUN rm -rf /build

EXPOSE 8888

COPY release/docker-entrypoint.sh /
ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["-f", "--scanconfig"]
```

@john30 
Would it be possible to build also this Docker-Image when you release new versions. Currently I change my home-assistant installation completely to docker-images and this one is missing
