### ISSUE TITLE
Integration with Domoticz

### ISSUE THREAD

**Issue by guillaumezin** [john30/ebusd#282]
Hello,

Would you add in https://github.com/john30/ebusd/wiki/7.-Integrations a link to https://github.com/guillaumezin/DomoticzEbusd which allows an easy integration with ebusd?

Thank you.

**Comment by john30** [comment]
could you provide a screenshot or something alike so that a user gets a first impression of what this is good for?
your readme points to port 8888 primarily (especially in the firewall section) but the python script also uses the JSON port 8889. hence my question:
why do you need the JSON port at all? the same data is also retrievable via telnet port (or did I miss something here?)

**Comment by guillaumezin** [comment]
I use JSON to parse exact message type, this way I can tell Domoticz if the message is a temperature, a selector switch, etc. It's the only way I managed to do it easily.

For the firewall, I suggest to protect port 8888 because this is the telnet port and you can read AND write messages, the JSON port is a read only port, so I didn't bother protecting it.

![DomoticzEbusdCapture1](https://user-images.githubusercontent.com/541581/57181523-359a5500-6e95-11e9-8029-72a5c32e62ed.png)

![DomoticzEbusdCapture2](https://user-images.githubusercontent.com/541581/57181522-3501be80-6e95-11e9-870d-401191dcf7ee.png)

![DomoticzEbusdCapture3](https://user-images.githubusercontent.com/541581/57181521-33d09180-6e95-11e9-9e6c-0859a78545e3.png)

![DomoticzEbusdCapture4](https://user-images.githubusercontent.com/541581/57181520-3337fb00-6e95-11e9-803c-432d03f70ae9.png)

![DomoticzEbusdCapture5](https://user-images.githubusercontent.com/541581/57181519-3337fb00-6e95-11e9-8a3e-6e7b0e50a5ed.png)

![DomoticzEbusdCapture6](https://user-images.githubusercontent.com/541581/57181518-3337fb00-6e95-11e9-88fb-24e62cf6f29c.png)

![DomoticzEbusdCapture7](https://user-images.githubusercontent.com/541581/57181517-329f6480-6e95-11e9-8305-0d87f84df77d.png)

![DomoticzEbusdCapture8](https://user-images.githubusercontent.com/541581/57181667-0ab10080-6e97-11e9-84c1-779f078a1b5a.png)

**Comment by john30** [comment]
done
