### ISSUE TITLE
Not responding after starting ebusd scanconfig

### ISSUE THREAD

**Issue by diamond95** [john30/ebusd#284]
Hi John, 

I have WRSol2.1 and after installation on debian, I'm trying to run:
cd ebusd
sudo ebusd -f -d /dev/ttyUSB0 --scanconfig
...
[main notice] ebusd 3.1 ... started with auto scan

After that message, nothing shows up, even after 30 minutes.
Am I missing something? 
I also tried to check ebusd status, and get this: https://imgur.com/a/FVP7zAZ

Best regards

**Comment by john30** [comment]
the status is ok. is your adapter connected to /dev/ttyUSB0?

**Comment by diamond95** [comment]
Yes it is..
Like this: 
https://imgur.com/a/ycRiOip

**Comment by john30** [comment]
this adapter is unknown to me and probably does not forward the raw data to the serial device

**Comment by diamond95** [comment]
Which one do you suggest? 
On photo you can see I have some sort of converter called Ebus, from device to pc, but didnt work out.. :/

**Comment by john30** [comment]
see the wiki https://github.com/john30/ebusd/wiki/6.-Hardware
