### ISSUE TITLE
also Problems with Kernel 4.19.42-v7+

### ISSUE THREAD

**Issue by SailingTom** [john30/ebusd#285]
Hi John,

i am also having Problems since i have updated my Raspi 3 to Kernel 4.19.42-v7+
The ebus ( with rpi-adapter from reinhart ) starts as normal, but aquires no signal.

#EBUSD_OPTS="--scanconfig -d /dev/ttyebus -c http://ebusd.eu/config/ -l var/log/ebusd.log"

Any Options ??

Best Wishes

Tom

**Comment by john30** [comment]
duplicate of #283
