### ISSUE TITLE
Not sure if my ebus interface is working properly

### ISSUE THREAD

**Issue by juanjoqg** [john30/ebusd#299]
Hi,

I've an esera ebus USB adapter on my vaillant arotherm instalation. I'm getting some correct messages as:

> received read hmu Status01 QQ=10: 18.0;18.0;-;-;-;off
> received update-write hmu SetMode QQ=10: auto;0.0;-;-;1;1;1;0;0;0
> received update-read broadcast vdatetime QQ=10: 22:41:19;15.10.2019
> received update-read broadcast outsidetemp QQ=10: 12.188

but I see a lot of:

> received unknown MS cmd: 1008xxx
> received unknown MS cmd: 1076xxx

When stating the ebusd I get this messages:

> 2019-10-15 22:41:56.689 [main notice] ebusd 3.3.v3.3 started with auto scan
> 2019-10-15 22:41:57.489 [bus notice] bus started with own address 31/36
> 2019-10-15 22:41:57.528 [bus notice] signal acquired
> 2019-10-15 22:41:57.817 [bus notice] new master 71, master count 2
> 2019-10-15 22:41:57.860 [bus notice] new master 03, master count 3
> 2019-10-15 22:41:57.860 [update notice] received unknown MS cmd: 7108b5110107 / 050000000001
> 2019-10-15 22:41:59.613 [update notice] received unknown MS cmd: 03e8b512060b0000000000 / 0b0000000001ffffffffff00
> 2019-10-15 22:42:01.143 [update notice] received unknown MS cmd: 7108b507030bffff / 0100
> 2019-10-15 22:42:01.819 [bus notice] new master 10, master count 4
> 2019-10-15 22:42:01.880 [update notice] received unknown MS cmd: 1008b5110101 / 0924240080ffff0000ff
> 2019-10-15 22:42:02.145 [update notice] received unknown MS cmd: 1076b5110101 / 09ffffd400ffff000036
> 2019-10-15 22:42:02.408 [update notice] received unknown MS cmd: 1076b512030f0001 / 07008002b001ff01
> 2019-10-15 22:42:02.675 [update notice] received unknown MS cmd: 1008b51009000000ffffff070000 / 0101
> 2019-10-15 22:42:02.937 [update notice] received unknown MS cmd: 1076b51009000000ffffff050000 / 0101
> 2019-10-15 22:42:05.930 [update notice] received unknown MS cmd: 7108b5110107 / 050000000001
> 2019-10-15 22:42:07.629 [bus notice] scan 08: ;Vaillant;HMU01;0304;8802
> 2019-10-15 22:42:07.629 [update notice] store 08 ident: done
> 2019-10-15 22:42:07.629 [update notice] sent scan-read scan.08  QQ=31: Vaillant;HMU01;0304;8802
> 2019-10-15 22:42:07.629 [bus notice] scan 08: ;Vaillant;HMU01;0304;8802
> 2019-10-15 22:42:08.113 [main notice] read common config file vaillant/scan.csv
> 2019-10-15 22:42:08.232 [main notice] read common config file vaillant/general.csv
> 2019-10-15 22:42:08.347 [main notice] read common config file vaillant/broadcast.csv
> 2019-10-15 22:42:08.578 [main notice] read scan config file vaillant/08.hmu.csv for ID "hmu01", SW0304, HW8802
> 2019-10-15 22:42:08.826 [main notice] found messages: 59 (0 conditional on 0 conditions, 0 poll, 9 update)
> 2019-10-15 22:42:08.948 [update notice] sent unknown MS cmd: 3108b5090124 / 09003231313732333030
> 2019-10-15 22:42:09.111 [update notice] sent scan-read scan.08 id QQ=31:
> 2019-10-15 22:42:09.274 [update notice] sent scan-read scan.08 id QQ=31:
> 2019-10-15 22:42:09.437 [update notice] sent scan-read scan.08 id QQ=31: 21;17;23;0010014567;1610;005224;N7
> 2019-10-15 22:42:09.437 [bus notice] scan 08: ;21;17;23;0010014567;1610;005224;N7
> 2019-10-15 22:42:09.776 [update notice] received unknown MS cmd: 03e8b512060b0000000000 / 0b0000000001ffffffffff00
> 2019-10-15 22:42:10.038 [bus notice] max. symbols per second: 103
> 2019-10-15 22:42:11.265 [update notice] received unknown MS cmd: 7108b507030bffff / 0100
> 2019-10-15 22:42:11.539 [main error] scan config 15: ERR: read timeout
> 2019-10-15 22:42:12.271 [update notice] received read hmu Status01 QQ=10: 18.0;18.0;-;-;-;off
> 2019-10-15 22:42:12.535 [update notice] received unknown MS cmd: 1076b5110101 / 09ffffd400ffff000036
> 2019-10-15 22:42:12.799 [update notice] received unknown MS cmd: 1076b512030f0001 / 07008002b001ff01
> 2019-10-15 22:42:13.066 [update notice] received update-write hmu SetMode QQ=10: auto;0.0;-;-;1;1;1;0;0;0
> 2019-10-15 22:42:13.327 [update notice] received unknown MS cmd: 1076b51009000000ffffff050000 / 0101
> 2019-10-15 22:42:13.653 [bus notice] scan 76: ;Vaillant;VWZIO;0111;0103

2019-10-15 22:42:14.428 [bus notice] scan 76: ;21;17;26;0020117049;0082;006854;N6
2019-10-15 22:42:14.545 [main error] unable to load scan config 76: no file from vaillant with prefix 76 found
2019-10-15 22:42:14.545 [main error] scan config 76: ERR: element not found

2019-10-15 22:42:17.312 [bus notice] scan e8: ;21;17;23;0010014567;1610;005224;N7
2019-10-15 22:42:17.434 [main error] unable to load scan config e8: no file from vaillant with prefix e8 found
2019-10-15 22:42:17.435 [main error] scan config e8: ERR: element not found

Could someone tell me if it working fine?

Thanks.

**Comment by john30** [comment]
it is working fine. only for some messages and some devices there are no "translation" definitions available
