### ISSUE TITLE
MQTT: Possibility to get fielddefs and comments

### ISSUE THREAD

**Issue by bumaas** [john30/ebusd#301]
Hi John, I'm looking for a way to get through MQTT to the field definitions and the comments of a message.
So similar to the HTTP way:
`http://192.168.178.82:8080/data/bai/dcfState?def&verbose`

Is there a way I have missed?

Thank you!

Burkhard

**Comment by john30** [comment]
this is not (yet) supported

**Comment by bumaas** [comment]
Thanks. No Problem. I will use the HTTP way to get the needed information.

**Comment by john30** [comment]
meanwhile with --mqttverbose units and comments are included in the JSON format
