### ISSUE TITLE
Vaillant VR920

### ISSUE THREAD

**Issue by christesting** [john30/ebusd#305]
I am a newbie in the area of EEBus - so maybe my question is stupid...but I will try it.

I got a new heating system from Vaillaint. 
Vaillant installed the VR920 to connect the VRC 700 to the LAN / Internet. The connection between the VR920 and VRC 700 is the EEBus.

Vaillant wrote me, that it is possible to use the VR920 as "interface" to the EEBus and I don´t need extra equipment to connect to the EEBus. 

The VR920 has an open port: 4500

Is it possible to use ebusd to interact with the VR920 (and the VRC 700) via LAN?

thx

**Comment by andig** [comment]
Ebusd is about ebus. Afaik Eebus is something different. See https://www.eebus.org/ - is that what Vaillant told you?

**Comment by christesting** [comment]
they told me, that I can find everything at https://www.eebus.org and that I don´t have to buy extra equipment to "talk" to the VRC 700 ...

The principle is shown here (I have different euqipment):
[https://www.vaillant.de/heizung/produkte/vernetzte-systeme/eebus/](url)

ok - now I unterstand why I am confused: ebus vs eebus......

**Comment by john30** [comment]
eebus seems to be a complete new protocol defined from scratch, so this is not related to ebusd at all

**Comment by koen-lee** [comment]
The VR921 is connected and reads/writes to the ebus too (in addition to eebus). After all, the various apps use it to set things in the thermostat, so it has all required hardware to work as a ebus<>ethernet bridge. One could try to install a MITM proxy, or just sniff the traffic with Wireshark, to work out the communication between the VR921 and the Vaillant cloud/app so see how feasible it is to use it with open source software.
