### ISSUE TITLE
gcc compiler warning

### ISSUE THREAD

**Issue by dwarning** [john30/ebusd#316]
It is not really an issue but perhaps a potential overflow problem. This I got compiling on a RPi 3 on actual git master branch:
mainloop.cpp: In member function ‘ebusd::result_t ebusd::MainLoop::executeFind(const std::vector<std::__cxx11::basic_string<char> >&, const string&, std::ostringstream*)’: mainloop.cpp:1464:46: warning: ‘-’ directive output may be truncated writing 1 byte into a region of size between 0 and 16 [-Wformat-truncation=] snprintf(str+len, sizeof(str)-len, ", lastup=%04d-%02d-%02d %02d:%02d:%02d", ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ mainloop.cpp:1464:19: note: ‘snprintf’ output between 29 and 81 bytes into a destination of size 32 snprintf(str+len, sizeof(str)-len, ", lastup=%04d-%02d-%02d %02d:%02d:%02d", ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ td.tm_year+1900, td.tm_mon+1, td.tm_mday, ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ td.tm_hour, td.tm_min, td.tm_sec); ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by john30** [comment]
indeed not an issue, as the result of the snprintf cannot be longer than 31 characters.
