### ISSUE TITLE
Translation of the states (on/off)

### ISSUE THREAD

**Issue by MatthiasKunze** [john30/ebusd#331]
Hello, I would like to translate the names of the states from English to German.

In the file bai.0010006101.inc I managed to translate the status of the flame.
r,,Flame,Flammensignal,,,,"0500",,,UCH,240=off;15=on,,Flammensignal
r,,Flame,Flammensignal,,,,"0500",,,UCH,240=Aus;15=An,,Flammensignal

In my file 38.v32.csv, which I created myself, I was unable to translate the status of the frost protection.
r,recov,FrostProtection,Frostschutzelement aktiv,,,,29f10c,,,onoff,,,
r,recov,FrostProtection,Frostschutzelement aktiv,,,,29f10c,,,AnAus,,,
With "AnAus" the status can no longer be read out.
Do you have an idea why?

**Comment by john30** [comment]
the field type "onoff" refers to a template defined in one of the _templates.csv files. So if you want to have that translated, you need to find the onoff template there and change the value list assignments in the definition
