### ISSUE TITLE
Vaillant VWS 36/4.1 230V neue Wärmepumpe wird nicht mit autscan erkannt

### ISSUE THREAD

**Issue by MineWater** [john30/ebusd#332]
Hallo,
ich arbeite mit der Wärmepumpe  VWS 36/4.1 230V  von Vaillant. Leider werden die Parameter nicht erkannt. 
Ich würde mich freuen wenn Sie mir weiterhelfen können. Ich hab unten mal ein paar nicht erkannte Felder angehangen sowie das ergebnis des Scans für die Wärmepumpe.
Sollten Sie weitere Informationen benötigen, kann ich Ihnen die gern zur Verfügung stellen

`scan.08 id 0 21;19;05;0010022462;0001;005016;N4`

```
localhost: grab result
1008b507010a / 037a7a03 = 4
1008b5110100 / 09f801136400090001c8 = 256
10feb505025c00 = 254
10feb510020601 = 50
1008b507020946 / 02a102 = 256
1008b512020000 / 00 = 51
1008b512020464 / 0101 = 51
1008b513020528 / 0101 = 51
ave #8, ebusd
```
Vielen dank für eine Antwort.

**Comment by john30** [comment]
die Ausgabe von "ebusctl info" wäre noch hilfreich, um den HW/SW Stand zu bekommen

**Comment by john30** [comment]
closed due to inactivity
