### ISSUE TITLE
Generic write command

### ISSUE THREAD

**Issue by tammycutzet** [john30/ebusd#342]
Hi,

many thanks for this project! Im already have comms to a Wolf CGB2 and also a good ammount of data tags / decoded tags.

My question is more generic: I would like to send a command to the boiler or the operator panel to put the boiler into standby. But I dont know in generel if the operator panel is just sending setpoints to the boiler, or also the mode the boiler should be in?

So is there a good way to write something to the boiler or operator panel thru ebus to set the heating system into standby?

Sorry for beeing so generic!

**Comment by john30** [comment]
I'm afraid I can't answer this question. There might be CSV definitions for Wolf somewhere (even in ebusd-configuration repo), but you'll have to check yourself.

**Comment by john30** [comment]
closed due to inactivity
