### ISSUE TITLE
find -f (csv) does not escape double quotes properly

### ISSUE THREAD

**Issue by HLFCode** [john30/ebusd#351]
Hi
Great project - many thanks for the hard work!
csv output format from "find" does not escape double quotes (or double double-quote) properly
e.g.
`ebusctl find -f -e -c ehp TimeBetweenTwoCompStartsMin`
responds with
`r,ehp,TimeBetweenTwoCompStartsMin,Min. Pausenzeit Kompressor,,08,b509,0de800,seconds,s,ULG,2,s,"calculated from menu item "compressor starts per hour" in 0,5s steps"`
Note the embedded double quotes are not escaped or doubled
This means csv parsers break the last column into 2 either side of the comma in '0,5 steps'
e.g. from Python csv.reader
`['r', 'ehp', 'TimeBetweenTwoCompStartsMin', 'Min. Pausenzeit Kompressor', '', '08', 'b509', '0de800', 'seconds', 's', 'ULG', '2', 's', 'calculated from menu item compressor starts per hour" in 0', '5s steps"']`
Maybe a it should return
`...item \"compressor starts per hour\" in...`
or 
`...item ""compressor starts per hour"" in...`
Thanks again

[edit]
The source of the config which is giving me this problem is [here](https://github.com/john30/ebusd-configuration/blob/master/ebusd-2.1.x/en/vaillant/08.ehp.csv) at line 177 in the last "comment" column
Changing the embedded double quotes to double double-quotes would be a part fix.
There may be other config files (which I do not use) which could give other users this problem though

**Comment by john30** [comment]
solved with 02d284587881ebd547fd7d81fe485075b6b1c04f

**Comment by john30** [comment]
closed as it seems to be fixed
