### ISSUE TITLE
Poll priority is not changing the actual poll intervall

### ISSUE THREAD

**Issue by Eraser-1** [john30/ebusd#360]
Hi,

I have set the poll intervall in the /etc/default/ebusd in the following way:
`EBUSD_OPTS="--scanconfig -d /dev/ttyebus --pollinterval=10"`

When I now start a read request with `ebustl read -p 6 -f HwcStorageTemp` I thought I will get this value polled every 10s*6=60s.
Unfortunately, it still gets polled every 10 seconds.

`2020-09-28 07:45:14.108 [update notice] sent poll-read 700 HwcStorageTemp QQ=31: 31`
`2020-09-28 07:45:25.104 [update notice] sent poll-read 700 HwcStorageTemp QQ=31: 31`
`2020-09-28 07:45:36.106 [update notice] sent poll-read 700 HwcStorageTemp QQ=31: 31`
`2020-09-28 07:45:47.491 [update notice] sent poll-read 700 HwcStorageTemp QQ=31: 31`
`2020-09-28 07:45:58.117 [update notice] sent poll-read 700 HwcStorageTemp QQ=31: 31`
`2020-09-28 07:46:09.105 [update notice] sent poll-read 700 HwcStorageTemp QQ=31: 31`
`2020-09-28 07:46:20.102 [update notice] sent poll-read 700 HwcStorageTemp QQ=31: 31`
`2020-09-28 07:46:31.143 [update notice] sent poll-read 700 HwcStorageTemp QQ=31: 31`

Is there a misunderstanding of the poll priority from my side? Did I miss something?

If I change the --pollinterval to 60, then the polling is done every 60 seconds and it doesn't matter again which -p value I use at the ebusctl read.

Thanks for the help
Wolfgang

**Comment by john30** [comment]
it is a poll priority not a factor to the time. so when there is no other entry with higher priority (with 1 being the highest), then the next prios will be traversed.
