### ISSUE TITLE
Ebusctl - "find" problem.

### ISSUE THREAD

**Issue by ikavior** [john30/ebusd#366]
Hi, 
I have got fully working ebusd deamon till today.

Now I cant read any values from Vaillant Eco Tec. Ebusd installed on RPi, and connected with Esera Ebus adapter - was working.

Today after command: "ebusctl" 
localhost: find
scan.08  = Vaillant;BAI00;0104;7803
scan.15  = Vaillant;70000;0613;6903
scan.ec  = Vaillant;SOL00;0613;6903

I cant see any parameters to read.

Any help?

**Comment by john30** [comment]
thanks for the hint, that seems to have happened due to http->https redirection. can you check again please?

**Comment by ikavior** [comment]
now its working

**Comment by john30** [comment]
thanks
