### ISSUE TITLE
Help needed for Synology Docker to run ebusd

### ISSUE THREAD

**Issue by tanker11** [john30/ebusd#367]
Hello,

I have a Wemos running ebus adapter 2.0 connected via an ebus interface to my heater.
I googled a lot of commands how to run the daemon on Synology, and once it is run the wifi adapter says: ebus connected: yes.
But I could not figure out, what configuration folders and files to be placed and where on Synology NAS in order that ebusd finds them and start reading out. I got "invalid configpath" or "error reading config files" error messages.
Could I receive a little bit of help how/where to place the files on Synology and refer to them?
Also what exactly I should place there from the folder (English version)?

Thanks in advance.

**Comment by john30** [comment]
you need to start ebusd with the right options. if you plan to use the webservice on ebusd.eu for getting the config files, you need to add "--scanconfig" to the ebusd start parameters.

**Comment by john30** [comment]
closed due to inactivity

**Comment by pepsonEL** [comment]
Hi @tanker11 
Can you write step by step how run daemon ebusd on Synology? Thanks

**Comment by tanker11** [comment]
Hello,

Sorry I gave up, and took no notes on this, so now I cannot help. :(

pepsonEL ***@***.***> ezt írta (időpont: 2021. dec. 17., P,
21:03):

**Comment by pepsonEL** [comment]
Ok no problem. I run it and works ok. Thanks
