### ISSUE TITLE
Double MQTT-answer after sending a "/get"-request

### ISSUE THREAD

**Issue by Eraser-1** [john30/ebusd#369]
Hello

If I send a MQTT-message over Node-Red to the RPI (which has the ebusd and Mosquitto), then I always get a double answer.

For example:

-) 14:45:51.53     I send "**ebusd/700/HwcTempDesired/get**"
-) 14:45:52:53     I get "**ebusd/700/HwcTempDesired**" with the value 46
-) 14:45:56:53     I get "**ebusd/700/HwcTempDesired**" with the value 46.0

This is happening with all "/get"-requests.

What is the cause for this?
Is this avoidable or how do you handle this?

**Comment by john30** [comment]
this is due to the updates being sent to MQTT as well as the answer to the request itself

**Comment by Eraser-1** [comment]
OK thanks
