### ISSUE TITLE
ECOTec 428 DHW mode

### ISSUE THREAD

**Issue by jackthom** [john30/ebusd#372]
When a VR65 is connected it can send commands to fire the boiler in DHW mode when the hot water cylinder demands it. Can anyone identify the ebusd commands that could be used to get the boiler into and out of this mode so I can ditch the VR65?

I have tried monitoring the communications between boiler and VR65 but all traffic is initiated from the boiler master (03) to the VR65 slave (64) with a reply which presumably tells the boiler the desired status.

With DHW ON demand I see in the log (in raw logging mode) this every 5 seconds or so....

[update notice] unknown MS cmd: 0364b512020264 / 0664010080ffff
Which corresponds to....
[update notice] update v65 State QQ=03: water;water;yes;-

When DHW is satisfied this changes to a regular...

[update notice] unknown MS cmd: 0364b5120202fe / 06fe000080ffff
Which is..
[update notice] update v65 State QQ=03: standby;standby;no;-

What I can't see, after separately powering up the VR65, is the process of the VR65 initially telling the boiler that it is actually present on the bus and somehow initiating this regular polling to confirm the current and required status of the boiler.

**Comment by john30** [comment]
this is more a topic for ebusd-configuration btw

**Comment by john30** [comment]
closed due to inactivity and wrong area
