### ISSUE TITLE
"invalid configpath without scanconfig"

### ISSUE THREAD

**Issue by RhineDelta** [john30/ebusd#374]
Installation:
Rasberry Pi 3B+/Buster with working MQTT broker (already in use for connecting Sonoff/Node Red/Domoticz)
Brink Allure B16 air heater and Brink Thermostat communicating over ebus

Tapping into ebus works fine:
![image](https://user-images.githubusercontent.com/47078360/98791411-4ff7ac00-2405-11eb-9f56-16a76c2ed6be.png)

Guess there are no configuration files for my heater. Am I correct in assuming that missing a configuration file will have any attempt to configure ebusd run into "invalid configpath without scanconfig"? So I don't seem to be able to configure the ebusd MQTT function.

For now I have a limited objective of simply listening in to the communication between Thermostat and airheater and get both the "set" and the actual temperature from the thermostat.

ebusd.log is filling up continuously but somehow I can't read the data because it is not UTF coded. Guess the raw data bytes are causing this.

Is there a way to circumvent the "invalid configpath without scanconfig" blockade and to get the raw data to MQTT so I can explore what's coming in?

**Comment by RhineDelta** [comment]
This circuit is used to tap into the ebus:
![P1030600](https://user-images.githubusercontent.com/47078360/98793785-a7e3e200-2408-11eb-9542-10bc57330d49.JPG)
 Circuit obtained from:
https://gitlab.com/fromeijn/ebuzzz-adapter/-/tree/master

**Comment by RhineDelta** [comment]
With Filezilla ebusd.log to PC and opened in EXCELL. 
Reboot Raspberry gives this record:
[Ebusd log at restart.xlsx](https://github.com/john30/ebusd/files/5531461/Ebusd.log.at.restart.xlsx)

My guess:
"Econ"=air heater
"Kromschroeder"=thermostat

So it works, but how to circumvent scanconfig blocking MQTT configuration?
![image](https://user-images.githubusercontent.com/47078360/98959894-0cd03280-2504-11eb-8ef7-11166dbb0e46.png)

**Comment by john30** [comment]
you need to configure the path to the config files using the ebusd "-c" parameter

**Comment by RhineDelta** [comment]
Thanks for the hint!

Guess you mean like this:
![image](https://user-images.githubusercontent.com/47078360/99398664-fdc2f900-28e4-11eb-8641-ac73bb8bb558.png)

This doesn't seem to work. Alas.

Please correct me if I am wrong:
- ebusd performs an initial scan to identify the type of equipment it is connect to and subsequently loads the applicable configuration file from the path specified.
- So if the equipment Brink Allure air heater (https://www.brinkclimatesystems.de/Warmluftheizung.html) is **not known**, what will ebusd do?
- Looking at the log file it seems any unknown command is logged. 

So if I use a rudimentary logfile **which at least will enable me to have the equipment recognized**, then I may be able:
1) to configure MQTT?
2) use the logfile to start constructing a more extensive configuration file by adding unrecognized commands from the logfile to the configuration file?

**Comment by RhineDelta** [comment]
Note: I am fully aware that importing in Excell the data is wrongly interpreted as characters while the data actually has to be interpreted in line with the coding formats supplied in the ebus specification. Anyway the file only demonstrates the regular ebus communication is intercepted.

**Comment by RhineDelta** [comment]
If my assumptions are correct you may have a rudimentary config file template?

**Comment by RhineDelta** [comment]
Guess I may have to develop my own csv file.
The spec_prot_7_v1_6_3_d.pdf page 38: Abfrage der unterstutzten Befehle (07h 02h).

Could that be useful to identify which commands are in use?
How can I ebusd order to issue such command?

**Comment by john30** [comment]
as you can see [here](https://github.com/john30/ebusd-configuration), we currently don't have any Kromschroeder config, so you'd have to create it yourself
using message 0702 will only reveal those that are specified in the eBUS spec, but not the vendor specific ones. But most of the configs are vendor specific
BTW: this is not an ebusd issue, but an ebusd-configuration

**Comment by p-bakker** [comment]
@RhineDelta did you ever get things going with your Brink Allure? 

I'm looking into options to control a Brink Allure B40 remotely instead of just locally through the [proprietary thermostat ](https://www.brinkclimatesystems.nl/documenten/brink-clock-thermostat-ebus-installation-instructions-gb-fr-de-nl-611972.pdf)
