### ISSUE TITLE
ebusd does not load csv files

### ISSUE THREAD

**Issue by TobiasBonhoeffer** [john30/ebusd#375]
For some reason I can not get ebusd to load the csv files

Here is what I get:

![image](https://user-images.githubusercontent.com/65175251/99198876-b0874000-279b-11eb-8eec-4f8d8ba6efbb.png)

This is the line  in the /etc/default/ebusd file

![image](https://user-images.githubusercontent.com/65175251/99198806-38207f00-279b-11eb-9254-43d64b5702ce.png)

Can somebody help?
Thanks in advance!

**Comment by john30** [comment]
have a look at the log file in /var/log/ebusd

**Comment by john30** [comment]
closed due to inactivity
