### ISSUE TITLE
Changing mode names Hc1SFMode

### ISSUE THREAD

**Issue by Dinth** [john30/ebusd#376]
Hi. 
My ebusd is hooked up to my instance of Home Assistant through MQTT protocol. Its generally working very well, except of ebusd/f47/Hc1SFMode, which returns "none" as one of the options. Unfortunately, HA template engine treats "none" not as a string, but as Null value and that breaks the templates. 
Is there any way of changing values which ebusd is reporting from HC1SFMode to MQTT?

**Comment by john30** [comment]
by adjusting the CSV in [ebusd-configuration](https://github.com/john30/ebusd-configuration).
not an ebusd issue
