### ISSUE TITLE
[update] How to update.

### ISSUE THREAD

**Issue by ikavior** [john30/ebusd#377]
Hi.
I saw update on git source v3.5. So I decided to:
>git clone https://github.com/john30/ebusd.git
cd ebusd
./autogen.sk
make
make install
sudo cp contrib/debian/systemd/ebusd.service /etc/systemd/system/
sudo reboot

on Rpi zero with latest Debian. 
When finished I tried:
>ebusctl info

and I get:

>version: ebusd 3.4.v3.4-83-gab75329
update check: revision v3.4 available

What Im doing wrong?
Thanks for help.

**Comment by john30** [comment]
there is no 3.5 yet
