### ISSUE TITLE
Setmode custom files

### ISSUE THREAD

**Issue by ThingThingHub** [john30/ebusd#378]
Hi,

I've been spending more then 30hours to get my setup working but I think I'm at a loss how to do it.
I just can't get my ebusd to write setmode because argument doesn't exist. This argument is needed so that my loxone can write to a setmode.php file that contains the setmode arguments for ebusd.

Used hardware & software
1) Loxberry with ebusdplugin (raspberry)
2) Ebus esera adapter (ebus-usb)
3) Vaillant ecotecplus-vc-w-be-5-5
4) with the default config I can see and write all basic values. Just the SETMODE value is not working.
Setup this far:

Setup arguments = --scanconfig --accesslevel=* --configpath=/etc/ebusd/
Copied the whole Vaillant folder from github to the ebusd location.
Changed bai.308523.inc file (my heating system)

I've added this setmode command to the mentioned file:

wi,BAI,SetModeOverride,Vaillant,,08,B510,00,hcmode,,UCH,,,,flowtempdesired,,D1C,,,,hwctempdesired,,D1C,,,,hwcflowtempdesired,,UCH,,,,,,IGN:1,,,,disablehc,,BI0,,,,disablehwctapping,,BI1,,,,disablehwcload,,BI2,,,,,,IGN:1,,,,remoteControlHcPump,,BI0,,,,releaseBackup,,BI1,,,,releaseCooling,,BI2

Everything is located in /etc/ebusd/Vaillant

Problems:

1) Ebusd won't load the correct custom config files. Without the --configpath the boiler files are load correctly.
2) Setmode is not a variable that I can use because of problem 1.

I don't want to use the standard Vaillant setup -> out the windows please.
Could somebody please assist me to get the setup working? I'm willing to pay for the time.

**Comment by john30** [comment]
please have a look at the instructions [here](https://github.com/john30/ebusd-configuration#installation-on-up-to-date-ebusd-20-or-higher)

**Comment by john30** [comment]
closed due to inactivity
