### ISSUE TITLE
Mosquitto version 2

### ISSUE THREAD

**Issue by mozzarelka** [john30/ebusd#380]
Hi, 
after updating mosquitto version from 1.6 to 2.0 on ubuntu server I lost mqtt connection with ebusd.

[mqtt error] invalid mosquitto version 2 instead of 1
[main error] error registering data handlers

Rafal

**Comment by john30** [comment]
can you try commenting lines 302-305 in src/ebusd/mqtthandler.cpp and see if this works?

**Comment by kyle-mge** [comment]
> can you try commenting lines 302-305 in src/ebusd/mqtthandler.cpp and see if this works?

Hi @john30,

had the same issue and tried your suggestion of commenting the mentioned lines. Without checking the major version it works. mqtt messages are flying in.

Thanks
Matthias.

**Comment by dreamdancer27** [comment]
had the same issue today, everything is up to date, anny suggestions for debian packages?

**Comment by john30** [comment]
try upgrading libmosquitto
