### ISSUE TITLE
Docker john30/ebusd:rpi-latest cannot start - `GLIBC_2.28' not found 

### ISSUE THREAD

**Issue by stevoh6** [john30/ebusd#390]
HI, I was trying to run latest ebusd on "NanoPi neo plus2" with  "Ubuntu 16.04.6 LTS", means "armhf" architecture. I got following error. 
> root@NanoPi-NEO-Plus2:/var/docker-containers/ebusd-dev# docker run --rm -it --device=/dev/ttyUSB0:/dev/ttyUSB0 -p 8888 john30/ebusd:rpi-latest
> Unable to find image 'john30/ebusd:rpi-latest' locally
> rpi-latest: Pulling from john30/ebusd
> cc11be355171: Pull complete
> c7765c2405e2: Pull complete
> 346e83cd4d1d: Pull complete
> 342ba6097142: Pull complete
> bb03a62953be: Pull complete
> bb71ab366af0: Pull complete
> 786acf2cba9a: Pull complete
> d85572022cf0: Pull complete
> 254bf62f105b: Pull complete
> f02532a41be1: Pull complete
> b0fcb50c1236: Pull complete
> d854d78db1f6: Pull complete
> 8a69a0ad93e8: Pull complete
> a32d7ccb782b: Pull complete
> 83daa2a0e8d8: Pull complete
> 1033c1c851d8: Pull complete
> cf97a4313546: Pull complete
> 858f06134773: Pull complete
> 26af9360b377: Pull complete
> 53e803aab872: Pull complete
> 6e7f6cebc795: Pull complete
> 0a7854975dfb: Pull complete
> 747467271911: Pull complete
> 12332f715246: Pull complete
> Digest: sha256:8401bfa975e26c6bb639c868878b2b983390b3899017a0f5aaa9f89c9fc10c69
> Status: Downloaded newer image for john30/ebusd:rpi-latest
> ebusd: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by ebusd)

Problem is that "libc6 with version 2.28" is only on "balenalib/raspberrypi3:buster" version. 
Logs from docker build  with changed Dockerfile: "FROM balenalib/raspberrypi3:buster" 

> root@NanoPi-NEO-Plus2:/var/docker-containers/ebusd-dev# docker build -t ebusd:rpi-latest-fix-buster-v0.1 .
> Sending build context to Docker daemon  4.096kB
> Step 1/13 : FROM balenalib/raspberrypi3:buster
>  ---> 9b5d8655c5d4
> Step 2/13 : RUN install_packages     logrotate libmosquitto1 libstdc++6 libc6 libgcc1     curl
>  ---> Running in eac8614d3588
> Here are a few details about this Docker image (For more information please visit https://www.balena.io/docs/reference/base-images/base-images/):
> Architecture: ARM v7
> OS: Debian Buster
> Variant: run variant
> Default variable(s): UDEV=off
> Extra features:
>  Easy way to install packages with `install_packages <package-name>` command
>  Run anywhere with cross-build feature  (for ARM only)
>  Keep the container idling with `balena-idle` command
>  Show base image details with `balena-info` command
> Reading package lists...
> Building dependency tree...
> Reading state information...
> curl is already the newest version (7.64.0-4+deb10u1).
> The following package was automatically installed and is no longer required:
>   libidn11
> Use 'apt autoremove' to remove it.
> The following additional packages will be installed:
>   cron gcc-8-base libpopt0 sensible-utils
> Suggested packages:
>   anacron checksecurity glibc-doc libc-l10n locales
> Recommended packages:
>   default-mta | mail-transport-agent bsd-mailx | mailx
> The following NEW packages will be installed:
>   cron libmosquitto1 libpopt0 logrotate sensible-utils
> The following packages will be upgraded:
>   gcc-8-base libc6 libgcc1 libstdc++6
> 4 upgraded, 5 newly installed, 0 to remove and 31 not upgraded.
> Need to get 3184 kB of archives.
> After this operation, 1659 kB of additional disk space will be used.
> Get:1 http://deb.debian.org/debian buster/main armhf sensible-utils all 0.0.12 [15.8 kB]
> Get:2 http://deb.debian.org/debian buster/main armhf cron armhf 3.0pl1-134+deb10u1 [95.3 kB]
> Get:3 http://archive.raspbian.org/raspbian buster/main armhf gcc-8-base armhf 8.3.0-6+rpi1 [191 kB]
> Get:4 http://deb.debian.org/debian buster/main armhf libpopt0 armhf 1.16-12 [46.3 kB]
> Get:5 http://deb.debian.org/debian buster/main armhf logrotate armhf 3.14.0-4 [60.2 kB]
> Get:6 http://deb.debian.org/debian buster/main armhf libmosquitto1 armhf 1.5.7-1+deb10u1 [57.8 kB]
> Get:7 http://archive.raspbian.org/raspbian buster/main armhf libgcc1 armhf 1:8.3.0-6+rpi1 [36.5 kB]
> Get:8 http://archive.raspbian.org/raspbian buster/main armhf libstdc++6 armhf 8.3.0-6+rpi1 [326 kB]
> Get:9 http://archive.raspbian.org/raspbian buster/main armhf libc6 armhf 2.28-10+rpi1 [2355 kB]
> debconf: delaying package configuration, since apt-utils is not installed
> Fetched 3184 kB in 6s (544 kB/s)
> (Reading database ... 10103 files and directories currently installed.)
> Preparing to unpack .../gcc-8-base_8.3.0-6+rpi1_armhf.deb ...
> Unpacking gcc-8-base:armhf (8.3.0-6+rpi1) over (8.3.0-6) ...
> Setting up gcc-8-base:armhf (8.3.0-6+rpi1) ...
> (Reading database ... 10103 files and directories currently installed.)
> Preparing to unpack .../libgcc1_1%3a8.3.0-6+rpi1_armhf.deb ...
> Unpacking libgcc1:armhf (1:8.3.0-6+rpi1) over (1:8.3.0-6) ...
> Setting up libgcc1:armhf (1:8.3.0-6+rpi1) ...
> (Reading database ... 10103 files and directories currently installed.)
> Preparing to unpack .../libstdc++6_8.3.0-6+rpi1_armhf.deb ...
> Unpacking libstdc++6:armhf (8.3.0-6+rpi1) over (8.3.0-6) ...
> Setting up libstdc++6:armhf (8.3.0-6+rpi1) ...
> (Reading database ... 10103 files and directories currently installed.)
> Preparing to unpack .../libc6_2.28-10+rpi1_armhf.deb ...
> Unpacking libc6:armhf (2.28-10+rpi1) over (2.28-10) ...
> dpkg: warning: old libc6:armhf package post-removal script subprocess was killed by signal (Illegal instruction), core dumped
> dpkg: trying script from the new package instead ...
> dpkg: error processing archive /var/cache/apt/archives/libc6_2.28-10+rpi1_armhf.deb (--unpack):
>  new libc6:armhf package post-removal script subprocess was killed by signal (Illegal instruction), core dumped
> dpkg: error while cleaning up:
>  installed libc6:armhf package pre-installation script subprocess was killed by signal (Illegal instruction), core dumped
> Errors were encountered while processing:
>  /var/cache/apt/archives/libc6_2.28-10+rpi1_armhf.deb
> E: Sub-process /usr/bin/dpkg returned an error code (1)
> apt failed, retrying
> Illegal instruction (core dumped)
> apt failed, retrying
> Illegal instruction (core dumped)
> The command '/bin/sh -c install_packages     logrotate libmosquitto1 libstdc++6 libc6 libgcc1     curl' returned a non-zero code: 132

Logs from docker build  with changed Dockerfile: "FROM balenalib/raspberrypi3:jessie"

> root@NanoPi-NEO-Plus2:/var/docker-containers/ebusd-dev# docker build -t ebusd:rpi-latest-fix-jessie-v0.1 .
> Sending build context to Docker daemon  4.096kB
> Step 1/13 : FROM balenalib/raspberrypi3:jessie
>  ---> 95368f51e4f2
> Step 2/13 : RUN install_packages     logrotate libmosquitto1 libstdc++6 libc6 libgcc1     curl
>  ---> Using cache
>  ---> 1e40b2865b05
> Step 3/13 : LABEL maintainer "ebusd@ebusd.eu"
>  ---> Using cache
>  ---> 8845406df503
> Step 4/13 : ENV EBUSD_VERSION 21.1
>  ---> Using cache
>  ---> 20443bcd1062
> Step 5/13 : ENV EBUSD_ARCH armhf
>  ---> Using cache
>  ---> 6723f391d243
> Step 6/13 : LABEL version "${EBUSD_VERSION}-${EBUSD_ARCH}"
>  ---> Using cache
>  ---> 3251c987739d
> Step 7/13 : RUN curl -SL https://github.com/john30/ebusd/releases/download/v${EBUSD_VERSION}/ebusd-${EBUSD_VERSION}_${EBUSD_ARCH}-stretch_mqtt1.deb > ebusd.deb
>  ---> Using cache
>  ---> d57dfe64ef25
> Step 8/13 : RUN dpkg -i ebusd.deb
>  ---> Using cache
>  ---> 2b938093f613
> Step 9/13 : RUN rm ebusd.deb
>  ---> Using cache
>  ---> af09cd50c3af
> Step 10/13 : EXPOSE 8888
>  ---> Using cache
>  ---> 77a2e490a304
> Step 11/13 : COPY docker-entrypoint.sh /
>  ---> Using cache
>  ---> 124478fd0453
> Step 12/13 : ENTRYPOINT ["sh", "/docker-entrypoint.sh"]
>  ---> Running in 8879524b0859
> Removing intermediate container 8879524b0859
>  ---> 3771271be03c
> Step 13/13 : CMD ["-f", "--scanconfig"]
>  ---> Running in e2afcb3d56ce
> Removing intermediate container e2afcb3d56ce
>  ---> 7ca96976daf2
> Successfully built 7ca96976daf2
> Successfully tagged ebusd:rpi-latest-fix-jessie-v0.1
> root@NanoPi-NEO-Plus2:/var/docker-containers/ebusd-dev# docker run -it --device=/dev/ttyUSB0 -v /var/docker-containers/ebusd/data:/etc/ebusd -p 8888 ebusd:rpi-latest-fix-jessie-v0.1 --scanconfig --device=/dev/ttyUSB0 --configpath=/etc/ebusd --mqttuser=mqtt --mqttport=1883 --mqtthost=192.168.0.103 --mqttpass=2021 --readonly --configlang=en
> ebusd: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `CXXABI_1.3.9' not found (required by ebusd)
> ebusd: /usr/lib/arm-linux-gnueabihf/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ebusd)
> ebusd: /usr/lib/libmosquitto.so.1: version `MOSQ_1.4' not found (required by ebusd)
> ebusd: /lib/arm-linux-gnueabihf/libc.so.6: version `GLIBC_2.28' not found (required by ebusd)

Also I noticed, that row 27 should be changed to `ENTRYPOINT ["sh", "/docker-entrypoint.sh"]`

I tryied even use stretch with older version of ebusd (3.4) but container exited with code 132 without any logs

> root@NanoPi-NEO-Plus2:/var/docker-containers/ebusd-dev# docker build -t ebusd:rpi-latest-fix-stretch-v0.1 .
> Sending build context to Docker daemon  4.096kB
> Step 1/13 : FROM balenalib/raspberrypi3:stretch
> stretch: Pulling from balenalib/raspberrypi3
> cc11be355171: Already exists
> c7765c2405e2: Already exists
> 346e83cd4d1d: Already exists
> 342ba6097142: Already exists
> bb03a62953be: Already exists
> bb71ab366af0: Already exists
> 786acf2cba9a: Already exists
> d85572022cf0: Already exists
> 254bf62f105b: Already exists
> f02532a41be1: Already exists
> b0fcb50c1236: Already exists
> d854d78db1f6: Already exists
> 8a69a0ad93e8: Already exists
> a32d7ccb782b: Already exists
> 83daa2a0e8d8: Already exists
> 1033c1c851d8: Already exists
> cf97a4313546: Already exists
> Digest: sha256:cfc88e1e3a956fd505c1454b2b005b7901bf726e1a862b9b785c8edb7b1e25fa
> Status: Downloaded newer image for balenalib/raspberrypi3:stretch
>  ---> 5023bc10a5fd
> Step 2/13 : RUN install_packages     logrotate libmosquitto1 libstdc++6 libc6 libgcc1     curl
>  ---> Running in 56a8cc646e70
> Here are a few details about this Docker image (For more information please visit https://www.balena.io/docs/reference/base-images/base-images/):
> Architecture: ARM v7
> OS: Debian Stretch
> Variant: run variant
> Default variable(s): UDEV=off
> Extra features:
>  Easy way to install packages with `install_packages <package-name>` command
>  Run anywhere with cross-build feature  (for ARM only)
>  Keep the container idling with `balena-idle` command
>  Show base image details with `balena-info` command
> Reading package lists...
> Building dependency tree...
> Reading state information...
> libc6 is already the newest version (2.24-11+deb9u4).
> libc6 set to manually installed.
> The following additional packages will be installed:
>   cron gcc-6-base libc-ares2 libcurl3 libpopt0
> Suggested packages:
>   anacron checksecurity
> Recommended packages:
>   exim4 | postfix | mail-transport-agent bsd-mailx | mailx
> The following NEW packages will be installed:
>   cron libc-ares2 libmosquitto1 libpopt0 logrotate
> The following packages will be upgraded:
>   curl gcc-6-base libcurl3 libgcc1 libstdc++6
> 5 upgraded, 5 newly installed, 0 to remove and 20 not upgraded.
> Need to get 1365 kB of archives.
> After this operation, 1039 kB of additional disk space will be used.
> Get:1 http://deb.debian.org/debian stretch/main armhf cron armhf 3.0pl1-128+deb9u1 [92.3 kB]
> Get:2 http://security.debian.org/debian-security stretch/updates/main armhf curl armhf 7.52.1-5+deb9u13 [224 kB]
> Get:3 http://archive.raspberrypi.org/debian stretch/main armhf libc-ares2 armhf 1.14.0-1~bpo9+1 [80.7 kB]
> Get:4 http://deb.debian.org/debian stretch/main armhf libpopt0 armhf 1.16-10+b2 [46.1 kB]
> Get:5 http://deb.debian.org/debian stretch/main armhf logrotate armhf 3.11.0-0.1 [56.1 kB]
> Get:6 http://archive.raspbian.org/raspbian stretch/main armhf gcc-6-base armhf 6.3.0-18+rpi1+deb9u1 [180 kB]
> Get:7 http://deb.debian.org/debian stretch/main armhf libmosquitto1 armhf 1.4.10-3+deb9u4 [47.5 kB]
> Get:8 http://security.debian.org/debian-security stretch/updates/main armhf libcurl3 armhf 7.52.1-5+deb9u13 [265 kB]
> Get:9 http://archive.raspbian.org/raspbian stretch/main armhf libstdc++6 armhf 6.3.0-18+rpi1+deb9u1 [334 kB]
> Get:10 http://archive.raspbian.org/raspbian stretch/main armhf libgcc1 armhf 1:6.3.0-18+rpi1+deb9u1 [38.3 kB]
> debconf: delaying package configuration, since apt-utils is not installed
> Fetched 1365 kB in 1s (920 kB/s)
> Selecting previously unselected package cron.
> (Reading database ... 9746 files and directories currently installed.)
> Preparing to unpack .../cron_3.0pl1-128+deb9u1_armhf.deb ...
> Unpacking cron (3.0pl1-128+deb9u1) ...
> Preparing to unpack .../gcc-6-base_6.3.0-18+rpi1+deb9u1_armhf.deb ...
> Unpacking gcc-6-base:armhf (6.3.0-18+rpi1+deb9u1) over (6.3.0-18+deb9u1) ...
> Setting up gcc-6-base:armhf (6.3.0-18+rpi1+deb9u1) ...
> (Reading database ... 9785 files and directories currently installed.)
> Preparing to unpack .../libstdc++6_6.3.0-18+rpi1+deb9u1_armhf.deb ...
> Unpacking libstdc++6:armhf (6.3.0-18+rpi1+deb9u1) over (6.3.0-18+deb9u1) ...
> Setting up libstdc++6:armhf (6.3.0-18+rpi1+deb9u1) ...
> (Reading database ... 9785 files and directories currently installed.)
> Preparing to unpack .../libgcc1_1%3a6.3.0-18+rpi1+deb9u1_armhf.deb ...
> Unpacking libgcc1:armhf (1:6.3.0-18+rpi1+deb9u1) over (1:6.3.0-18+deb9u1) ...
> Setting up libgcc1:armhf (1:6.3.0-18+rpi1+deb9u1) ...
> Selecting previously unselected package libpopt0:armhf.
> (Reading database ... 9785 files and directories currently installed.)
> Preparing to unpack .../0-libpopt0_1.16-10+b2_armhf.deb ...
> Unpacking libpopt0:armhf (1.16-10+b2) ...
> Selecting previously unselected package logrotate.
> Preparing to unpack .../1-logrotate_3.11.0-0.1_armhf.deb ...
> Unpacking logrotate (3.11.0-0.1) ...
> Preparing to unpack .../2-curl_7.52.1-5+deb9u13_armhf.deb ...
> Unpacking curl (7.52.1-5+deb9u13) over (7.52.1-5+deb9u12) ...
> Preparing to unpack .../3-libcurl3_7.52.1-5+deb9u13_armhf.deb ...
> Unpacking libcurl3:armhf (7.52.1-5+deb9u13) over (7.52.1-5+deb9u12) ...
> Selecting previously unselected package libc-ares2:armhf.
> Preparing to unpack .../4-libc-ares2_1.14.0-1~bpo9+1_armhf.deb ...
> Unpacking libc-ares2:armhf (1.14.0-1~bpo9+1) ...
> Selecting previously unselected package libmosquitto1:armhf.
> Preparing to unpack .../5-libmosquitto1_1.4.10-3+deb9u4_armhf.deb ...
> Unpacking libmosquitto1:armhf (1.4.10-3+deb9u4) ...
> Setting up libpopt0:armhf (1.16-10+b2) ...
> Setting up libcurl3:armhf (7.52.1-5+deb9u13) ...
> Processing triggers for libc-bin (2.24-11+deb9u4) ...
> Setting up cron (3.0pl1-128+deb9u1) ...
> Adding group `crontab' (GID 104) ...
> Done.
> update-rc.d: warning: start and stop actions are no longer supported; falling back to defaults
> invoke-rc.d: could not determine current runlevel
> invoke-rc.d: policy-rc.d denied execution of start.
> Setting up libc-ares2:armhf (1.14.0-1~bpo9+1) ...
> Setting up logrotate (3.11.0-0.1) ...
> Setting up curl (7.52.1-5+deb9u13) ...
> Setting up libmosquitto1:armhf (1.4.10-3+deb9u4) ...
> Processing triggers for libc-bin (2.24-11+deb9u4) ...
> Removing intermediate container 56a8cc646e70
>  ---> 155c2de7d2f0
> Step 3/13 : LABEL maintainer "ebusd@ebusd.eu"
>  ---> Running in f9ce63e6c395
> Removing intermediate container f9ce63e6c395
>  ---> 8036975a8ca4
> Step 4/13 : ENV EBUSD_VERSION 3.4
>  ---> Running in f953ed97866b
> Removing intermediate container f953ed97866b
>  ---> 2a04a0aaf513
> Step 5/13 : ENV EBUSD_ARCH armhf
>  ---> Running in 78b780aaf16e
> Removing intermediate container 78b780aaf16e
>  ---> a5aa27293cd8
> Step 6/13 : LABEL version "${EBUSD_VERSION}-${EBUSD_ARCH}"
>  ---> Running in 82f42cd434f7
> Removing intermediate container 82f42cd434f7
>  ---> a0d98260f951
> Step 7/13 : RUN curl -SL https://github.com/john30/ebusd/releases/download/v${EBUSD_VERSION}/ebusd-${EBUSD_VERSION}_${EBUSD_ARCH}-stretch_mqtt1.deb > ebusd.deb
>  ---> Running in 196b90b602d9
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
> 100   657  100   657    0     0   1261      0 --:--:-- --:--:-- --:--:--  1263
> 100  190k  100  190k    0     0  96126      0  0:00:02  0:00:02 --:--:--  132k
> Removing intermediate container 196b90b602d9
>  ---> 2368811fb0a2
> Step 8/13 : RUN dpkg -i ebusd.deb
>  ---> Running in 63e5ec981ac7
> Selecting previously unselected package ebusd.
> (Reading database ... 9854 files and directories currently installed.)
> Preparing to unpack ebusd.deb ...
> Unpacking ebusd (3.4) ...
> Setting up ebusd (3.4) ...
> Instructions:
>  Edit /etc/default/ebusd if necessary
>    (especially if your device is not /dev/ttyUSB0)
>  Start the daemon with 'systemctl start ebusd'
>  Check the log file /var/log/ebusd.log
>  Make the daemon autostart with 'systemctl enable ebusd'
> root@NanoPi-NEO-Plus2:/var/docker-containers/ebusd-dev# docker run -it --device=/dev/ttyUSB0 -v /var/docker-containers/ebusd/data:/etc/ebusd -p 8888 ebusd:rpi-latest-fix-stretch-v0.1 --scanconfig --device=/dev/ttyUSB0
> root@NanoPi-NEO-Plus2:/var/docker-containers/ebusd-dev#
 
Coul you please check it?
I hope, that those logs will help, if you ned some testing with docker I can help. 

Thank you.

**Comment by MichlW** [comment]
I think rpi-latest tag is configured wrong as it states the platform as `amd64`:

![image](https://user-images.githubusercontent.com/49558935/105528270-11c01800-5ce5-11eb-9103-a6d25369992d.png)

I actually use `john30/ebusd:devel` on Raspberry Pi 4 and it is working great, because it is a multi-platform tag for `amd64` and `armv7`. You should try out that tag or `john30/ebusd:devel-arm32v7` directly...

Good luck ;-)

**Comment by MichlW** [comment]
The actual documentation also states that `latest` tag is multi-platform too. Thats not true...
Only with tag `devel` or `devel-arm32v7` it is working on arm.

**Comment by stevoh6** [comment]
HI, 

> I think rpi-latest tag is configured wrong as it states the platform as `amd64`:
> 
> ![image](https://user-images.githubusercontent.com/49558935/105528270-11c01800-5ce5-11eb-9103-a6d25369992d.png)
> 
> I actually use `john30/ebusd:devel` on Raspberry Pi 4 and it is working great, because it is a multi-platform tag for `amd64` and `armv7`. You should try out that tag or `john30/ebusd:devel-arm32v7` directly...
> 
> Good luck ;-)

Thank you, it worked :-)

**Comment by john30** [comment]
the latest tag will be functional again with the next release of ebusd. sorry for any inconvenience in between
