### ISSUE TITLE
segmentation fault after new release 21.1

### ISSUE THREAD

**Issue by eh-gh** [john30/ebusd#394]
Hi

after installing the newest version I can no start ebusd on rpi zero w

root@raspberrypi:/home/pi# ebusd
Segmentation fault

root@raspberrypi:/home/pi# cat /sys/firmware/devicetree/base/model
Raspberry Pi Zero W Rev 1.1

root@raspberrypi:/home/pi# cat /etc/debian_version
9.13

root@raspberrypi:/home/pi# uname -a
Linux raspberrypi 4.19.66+ #1253 Thu Aug 15 11:37:30 BST 2019 armv6l GNU/Linux

root@raspberrypi:/home/pi# apt-cache show ebusd
Package: ebusd
Version: 21.1
Architecture: armhf
Maintainer: John Baier <ebusd@ebusd.eu>
Homepage: https://github.com/john30/ebusd
Bugs: https://github.com/john30/ebusd/issues
Depends: logrotate, libstdc++6 (>= 4.8.1), libc6, libgcc1, libmosquitto1
Priority: required
Section: net
Filename: pool/main/e/ebusd/ebusd_21.1_armhf.deb
Size: 223670
SHA256: 50a732dbba68e63e1f4afd1fec4aa30ab03e24004d98e7ac6a46fb6cf2e735d6
SHA1: 88a1e9bd3f5ba4c149ee737f67fc5118591aec01
MD5sum: 7eb9fbd58b8ce6f4818bd39b7978a673
Description: eBUS daemon.
 ebusd is a daemon for handling communication with eBUS devices connected to a
 2-wire bus system.
Description-md5: 9fbfafb1051a5d3c5eb0b4f89ab883b3

can you check plz
thansk & br
eh-gh

UPDATE:
if I compile the packages with ./make_all.sh respectively, the ebusd-21.1_armhf_mqtt1.deb can be installed and it works correctly.

**Comment by john30** [comment]
just bought such a device and will check in detail once it arrives

**Comment by Mike1969n** [comment]
I use an elder Raspberry Pi Model B Plus Rev 1.2

**Comment by john30** [comment]
are you sure you correctly compiled it and used that compiled binary?

**Comment by eh-gh** [comment]
I reinstalled the repo pkg:

root@raspberrypi:/home/pi# cat /etc/apt/sources.list.d/ebusd.list
deb https://www.ebusd.eu/repos/apt/default/stretch stretch main

root@raspberrypi:/home/pi# apt-get install --reinstall ebusd
Reading package lists... Done
Building dependency tree
Reading state information... Done
0 upgraded, 0 newly installed, 1 reinstalled, 0 to remove and 0 not upgraded.
Need to get 0 B/224 kB of archives.
After this operation, 0 B of additional disk space will be used.
(Reading database ... 78329 files and directories currently installed.)
Preparing to unpack .../archives/ebusd_21.1_armhf.deb ...
Unpacking ebusd (21.1) over (21.1) ...
Setting up ebusd (21.1) ...
Instructions:
1. Edit /etc/default/ebusd if necessary
   (especially if your device is not /dev/ttyUSB0)
2. Start the daemon with 'service ebusd start'
3. Check the log file /var/log/ebusd.log
4. Make the daemon autostart with 'update-rc.d ebusd enable'
Processing triggers for systemd (232-25+deb9u12) ...
root@raspberrypi:/home/pi# ebusd
Segmentation fault

manually compiled using the latest src with make_all.sh

pi@raspberrypi:~/ebusd $ git show
commit 6c5cc382db263b18a06c7db47ff2669dbd635c9b
Author: John <ebusd@ebusd.eu>
Date:   Sun Jan 24 12:28:05 2021 +0100
...

pi@raspberrypi:~/ebusd $ sudo dpkg -i ebusd-21.1_armhf_mqtt1.deb
(Reading database ... 78329 files and directories currently installed.)
Preparing to unpack ebusd-21.1_armhf_mqtt1.deb ...
Unpacking ebusd (21.1) over (21.1) ...
Setting up ebusd (21.1) ...
Instructions:
1. Edit /etc/default/ebusd if necessary
   (especially if your device is not /dev/ttyUSB0)
2. Start the daemon with 'systemctl start ebusd'
3. Check the log file /var/log/ebusd.log
4. Make the daemon autostart with 'systemctl enable ebusd'
pi@raspberrypi:~/ebusd $ ebusd
2021-01-27 20:47:42.799 [main error] invalid configpath without scanconfig

-> no seg fault

**Comment by john30** [comment]
ah ok, that's what I expected. then it is a problem of the cross-compile.
for the time being please stick to the manual compile

**Comment by john30** [comment]
this should be fixed with the new release [v21.2](https://github.com/john30/ebusd/releases/tag/v21.2)

**Comment by eh-gh** [comment]
thanks John, but it seems to be NOK.

see strace attached

if I build the pkg ebusd-21.2_armhf_mqtt1.deb, it is still OK.

thanks

[ebusd_21.2_segfault_strace.log](https://github.com/john30/ebusd/files/5949430/ebusd_21.2_segfault_strace.log)

**Comment by john30** [comment]
you need to use the armel build

**Comment by eh-gh** [comment]
hi
actually the system is raspbian, which is based on armhf

I can not install armel pkg to the board:

pi@raspberrypi:/tmp $ sudo dpkg -i ebusd-21.2_armel-stretch_mqtt1.deb
dpkg: error processing archive ebusd-21.2_armel-stretch_mqtt1.deb (--install):
 package architecture (armel) does not match system (armhf)
Errors were encountered while processing:
 ebusd-21.2_armel-stretch_mqtt1.deb

**Comment by john30** [comment]
can you try the following please:
`wget https://github.com/john30/ebusd/releases/download/v21.2/ebusd-21.2_armel-stretch_mqtt1.deb`
`dpkg -x ebusd-21.2_armel-stretch_mqtt1.deb /`
and then run `ebusd -V`

**Comment by eh-gh** [comment]
pi@raspberrypi:/tmp $ wget https://github.com/john30/ebusd/releases/download/v21.2/ebusd-21.2_armel-stretch_mqtt1.deb
...
Connecting to github-releases.githubusercontent.com (github-releases.githubusercontent.com)|185.199.109.154|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 217994 (213K) [application/octet-stream]
Saving to: ‘ebusd-21.2_armel-stretch_mqtt1.deb’

ebusd-21.2_armel-st 100%[===================>] 212.88K  --.-KB/s    in 0.1s    

2021-02-13 10:47:43 (1.53 MB/s) - ‘ebusd-21.2_armel-stretch_mqtt1.deb’ saved [217994/217994]

pi@raspberrypi:/tmp $ mkdir test 
pi@raspberrypi:/tmp $ mv ebusd-21.2_armel-stretch_mqtt1.deb test/
pi@raspberrypi:/tmp $ cd test
pi@raspberrypi:/tmp/test $ dpkg -x ebusd-21.2_armel-stretch_mqtt1.deb .
pi@raspberrypi:/tmp/test $ ls
ebusd-21.2_armel-stretch_mqtt1.deb  etc  usr
pi@raspberrypi:/tmp/test $ cd usr/bin/
pi@raspberrypi:/tmp/test/usr/bin $ ls
ebusctl  ebusd  ebuspicloader
pi@raspberrypi:/tmp/test/usr/bin $ ./ebusd  -V
ebusd 21.2.v21.2
pi@raspberrypi:/tmp/test/usr/bin $ cd ..
pi@raspberrypi:/tmp/test/usr $ cd ..
pi@raspberrypi:/tmp/test $ ls
ebusd-21.2_armel-stretch_mqtt1.deb  etc  usr
pi@raspberrypi:/tmp/test $ sudo dpkg -i ebusd-21.2_armel-stretch_mqtt1.deb
dpkg: error processing archive ebusd-21.2_armel-stretch_mqtt1.deb (--install):
 package architecture (armel) does not match system (armhf)
Errors were encountered while processing:
 ebusd-21.2_armel-stretch_mqtt1.deb

**Comment by john30** [comment]
ok, so the binary works but the package is not installable due to an architecture mismatch.
does someone have an idea how to solve that?

**Comment by john30** [comment]
you can force the armel installation like this:
```shell
wget https://github.com/john30/ebusd/releases/download/v21.2/ebusd-21.2_armel-stretch_mqtt1.deb
dpkg -i --force-depends ebusd-21.2_armel-stretch_mqtt1.deb
```

**Comment by FritzAlfred** [comment]
Hi,
I want to install ebusd on a Raspberry zero wh.
After installation ebusd does not start with the following error message.
I tried both buster and stretch as operating system and eposd package in alternation, same result.
A Raspberry4 runs on the first try. 
(Can I communicate in German?)

EDIT by john: removed the crappy output. if you want to have it here again, please do with attachment

**Comment by FritzAlfred** [comment]
Sorry,
now I have probably cluttered everything!

**Comment by john30** [comment]
yes, your comment is rather unreadable.
as I wrote above, it should work by forcing the armel install like this:
```sh
wget https://github.com/john30/ebusd/releases/download/v21.2/ebusd-21.2_armel-stretch_mqtt1.deb
dpkg -i --force-depends ebusd-21.2_armel-stretch_mqtt1.deb
```

**Comment by AloisKlingler** [comment]
`dpkg -i --force-depends ebusd-21.2_armel-stretch_mqtt1.deb` did not work for me: `package architecture (armel) does not match system (armhf)`

I manually unpacked and copied, this worked for me:
`dpkg -x ebusd-21.2_armel-stretch_mqtt1.deb`

and afterwards:
`cp usr/bin/ebusd* /usr/bin/`

best regards
Alois

**Comment by riesermauf** [comment]
Hallo
I use openhabian and had the same problem:

`openhabian@openhab:~ $ systemctl status ebusd
● ebusd.service - LSB: controls ebusd, the daemon for communication with eBUS heating systems.
   Loaded: loaded (/etc/init.d/ebusd; generated)
   Active: failed (Result: exit-code) since Tue 2021-04-06 14:36:39 CEST; 3min 40s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 531 ExecStart=/etc/init.d/ebusd start (code=exited, status=139)

Apr 06 14:36:35 openhab systemd[1]: Starting LSB: controls ebusd, the daemon for communication with eBUS heating systems....
Apr 06 14:36:38 openhab ebusd[531]: Starting ebusd: ebusd/etc/init.d/ebusd: Zeile 43:   604 Speicherzugriffsfehler  start-stop-daemo
Apr 06 14:36:39 openhab ebusd[531]:  failed!
Apr 06 14:36:39 openhab systemd[1]: ebusd.service: Control process exited, code=exited, status=139/n/a
Apr 06 14:36:39 openhab systemd[1]: ebusd.service: Failed with result 'exit-code'.
Apr 06 14:36:39 openhab systemd[1]: Failed to start LSB: controls ebusd, the daemon for communication with eBUS heating systems..
lines 1-12/12 (END)

openhabian@openhab:~ $ apt-cache show ebusd
Package: ebusd
Version: 21.2
Architecture: armhf
Maintainer: John Baier <ebusd@ebusd.eu>
Homepage: https://github.com/john30/ebusd
Bugs: https://github.com/john30/ebusd/issues
Depends: logrotate, libstdc++6 (>= 4.8.1), libc6, libgcc1, libmosquitto1
Priority: required
Section: net
Filename: pool/main/e/ebusd/ebusd_21.2_armhf.deb
Size: 213928
SHA256: e8fd7beb127a287091e543a22438db7c25fea44ec47defa548d9a0203d22ae9c
SHA1: 05badbe6b237151102ea16b9bd664675a7e01fd0
MD5sum: 90a3d247c78c28a938e97fbb6dd756d2
Description: eBUS daemon.
 ebusd is a daemon for handling communication with eBUS devices connected to a
 2-wire bus system.
Description-md5: 9fbfafb1051a5d3c5eb0b4f89ab883b3

openhabian@openhab:~ $ cat /sys/firmware/devicetree/base/model
Raspberry Pi Zero W Rev 1.1

openhabian@openhab:~ $ cat /etc/debian_version
10.9
`
No solution above works for me, what can I do.

Best regards

**Comment by john30** [comment]
did you do the steps mentioned [above](https://github.com/john30/ebusd/issues/394#issuecomment-778600501)?

**Comment by john30** [comment]
covered by [ebusd-debian issue](https://github.com/john30/ebusd-debian/issues/5) now
