### ISSUE TITLE
ebusd overwrites existing /etc/default/ebusd on upgrading

### ISSUE THREAD

**Issue by AloisKlingler** [john30/ebusd#402]
on upgrading, /etc/default/ebusd is overwritten. normally debian-packages ask what needs to be done.

I upgraded from:
ebusd 3.4.v3.3-51-g57eae05

to ebusd 21.2.v21.2

(or: as it segfaulted to this version: https://github.com/john30/ebusd/issues/394 )

Best regards
Alois

**Comment by john30** [comment]
how did you do the update?

**Comment by AloisKlingler** [comment]
I did apt-get update && apt-get dist-upgrade
there the file was overwritten already

**Comment by Dinth** [comment]
I'm updating wbuad by compiling it but always forgetting to back up the config. I know it's my fault, but renaming default config file to for example ebusd.orig would be a huge quality of life improvement

**Comment by NimlothPL** [comment]
I can confirm, same behavior - config file is overwritten upon upgrade:
apt update && apt upgrade

**Comment by john30** [comment]
this is an issue for ebusd-debian, not ebusd. copied it [there](https://github.com/john30/ebusd-debian/issues/6)
