### ISSUE TITLE
error reading config files from http://ebusd.eu/config/

### ISSUE THREAD

**Issue by schinken** [john30/ebusd#407]
Just wanted to let you know, but http://ebusd.eu/config/ is 404.
Not sure if accidental or intentional, but wanted to mention it here

Best,
schinken

**Comment by john30** [comment]
how do you come to this conclusion?

**Comment by schinken** [comment]
The subject of this issue appeared as an error message running ebusd (non-docker version)

**Comment by john30** [comment]
is this still the case?
please post the full log and check if you can connect to the webservice from the host using curl or something else

**Comment by john30** [comment]
closed due to inactivity
