### ISSUE TITLE
I can't get any reading/data at all with a USB to UART converter board with an CP2102 & Ebusd on any version later than 3.4 

### ISSUE THREAD

**Issue by nimmerpeople** [john30/ebusd#413]
Hi,

I have an Ebus adapter from Floris here: https://www.tindie.com/products/foxrom/ebus-usb-adapter-ebuzzz-adapter/ to connect to my Vaillant boiler to read values from it.

I struggled for ages (having never used ebus or any of this hardware) but have, with Floris's help determined that ANY version above 3.4 just won't read the device. at all.

I have since downgraded (I was on 21.2 initially) and all is 100% fine. I just post this here incase anyone else has the same problem. I'm running Debian on a Raspberry Pi and happy to provide logs if this helps.

The version I have working is here:

https://github.com/john30/ebusd/releases/download/v3.4/ebusd-3.4_armhf-stretch_mqtt1.deb

**Comment by john30** [comment]
try compiling from sources and post some logging as the description is not enough to find the issue

**Comment by nimmerpeople** [comment]
Ok, will do. Thanks. I realised you’d need more info, just wasn’t sure what..

**Comment by nimmerpeople** [comment]
Ok, will do. Thanks. I realised you’d need more info, just wasn’t sure what..
Sorry to be so lame but I'm new to this. I've followed the guide from the wiki and got this far:

'apt install git autoconf automake g++ make'
- which worked fine

Then:
'git clone https://github.com/john30/ebusd.git'
'cd ebusd'

Again ok

Then I want to compile? so I type:

'make'
and I get errors:

make: *** No targets specified and no makefile found.  Stop.

I'll try and read up and see what I should do next..

**Comment by john30** [comment]
just follow [the documentation](https://github.com/john30/ebusd/wiki/1.-Build-and-install)

**Comment by nimmerpeople** [comment]
> just follow [the documentation](https://github.com/john30/ebusd/wiki/1.-Build-and-install)

err I did - it's from that documentation that I'm quoting above..

**Comment by john30** [comment]
I don't see autogen.sh being called before running make

**Comment by nimmerpeople** [comment]
> I don't see autogen.sh being called before running make

Ah thanks - that's just my ignorance then -I didn't think I needed that bit.. i'm learning though ;-) 
 
Ok, so I am closer to working out the problem (but will likely need help to progress).
When I compile the latest version 21.x - it works fine in the foreground all fine. It's with MQTT that I can't get it to work. I've added libmosquitto-dev support - by typing
sudo apt-get install libmosquitto-dev
which I think is right but nothing shows in the /var/log/ebusd.log once I reboot.

I probably only ever downloaded the pre compiled v21.x version with MQTT - so it may have always been an MQTT related issue all along. I'll see if I can get any further. The contents of /etc/default/ebusd are the same as I had working on 3.4, so I don't think it's that.

**Comment by nimmerpeople** [comment]
Ok, so I am closer to working out the problem (but will likely need help to progress).
When I compile the latest version 21.x - it works fine in the foreground all fine. It's with MQTT that I can't get it to work. I've added libmosquitto-dev support - by typing
 _sudo apt-get install libmosquitto-dev_
which I think is right but nothing starts in the /var/log/ebusd.log once I reboot.

I'll see if I can get any further. The contents of 
/etc/default/ebusd

are the same as I had working on 3.4, so I don't think it's that.

**Comment by john30** [comment]
you need to rebuild everything after you have added the libmosquitto-dev package

**Comment by nimmerpeople** [comment]
Thanks John. I finally got around to recompiling and everything seems to work now. 
thanks again for this marvellous utility!
