### ISSUE TITLE
Docker exec format error

### ISSUE THREAD

**Issue by Trilis29** [john30/ebusd#415]
standard_init_linux.go:219: exec user process caused: exec format error

Getting this error. I can not run on docker. Has anyone solved it?

**Comment by andig** [comment]
Youre likely running the wrong image for your platform.

**Comment by Trilis29** [comment]
tried DEVEL works ok. Seems stable RPI 3b+ HA OS

**Comment by netweaver1970** [comment]
> tried DEVEL works ok. Seems stable RPI 3b+ HA OS

How are you running ebusd on HassOS? As a manual "docker run" (from within the terminal & SSH add-on) or as a custom own-build HA  add-on pointing to the john30/ebusd docker hub image or did you install ebusd as a Debian package? 

Right now I'm running it as a manual "docker run" also on a separate Raspi 3b+but would like to consolidate all on the HassOs box.

**Comment by Trilis29** [comment]
Just use ebusd addon in supervisor HassOS. Developer works ok for me.

**Comment by john30** [comment]
closed due to inactivity
