### ISSUE TITLE
ERR: read timeout during skip, switching to no signal

### ISSUE THREAD

**Issue by lennyzaman** [john30/ebusd#417]
Hello all,

I recently bought the ebus adapter v3 in usb mode. 
this is connected to my rpi 3 model B via USB.
The adapter is wired to the ebus 2 wire line in the VRC370 wireless module.
I installed ebusd via repo through apt-get.
when running ebusd (in foreground for testing) I get following output.
`root@raspberrypi1:/home/pi# ebusd -d /dev/ttyUSB1 --mqtthost=192.168.0.188 --mqttport=1883 --mqttclientid=ebusd1 --mqttuser=******* --mqttpass=******* --scanconfig=full -f --configpath=http://ebusd.eu/config/ --loglevel=debug --enablehex --latency=10000 --receivetimeout=50000 --sendretries=4 --accesslevel=* -p 8889 --lograwdata=bytes`

> 2021-04-19 00:24:13.513 [main notice] ebusd 21.2.v21.2 started with full scan on device /dev/ttyUSB1
> 2021-04-19 00:24:13.513 [main info] loading configuration files from http://ebusd.eu/config/
> 2021-04-19 00:24:13.576 [main info] reading templates /
> 2021-04-19 00:24:13.641 [main info] read templates in /
> 2021-04-19 00:24:13.641 [main info] reading file memory.csv
> 2021-04-19 00:24:13.708 [main info] successfully read file memory.csv
> 2021-04-19 00:24:13.708 [main info] reading file broadcast.csv
> 2021-04-19 00:24:13.777 [main info] successfully read file broadcast.csv
> 2021-04-19 00:24:13.777 [main info] read config files
> 2021-04-19 00:24:13.779 [bus notice] bus started with own address 31/36
> 2021-04-19 00:24:13.780 [main info] registering data handlers
> 2021-04-19 00:24:13.780 [mqtt info] mosquitto version 1.5.7 (compiled with 1.5.7)
> 2021-04-19 00:24:13.799 [mqtt debug] connection requested
> 2021-04-19 00:24:13.799 [main info] registered data handlers
> 2021-04-19 00:24:13.805 [mqtt notice] connection established
> 2021-04-19 00:24:13.805 [mqtt debug] publish ebusd/global/version ebusd 21.2.v21.2
> 2021-04-19 00:24:13.805 [mqtt debug] publish ebusd/global/running true
> 2021-04-19 00:24:16.054 [bus notice] <fa
> 2021-04-19 00:24:16.054 [bus notice] signal acquired
> 2021-04-19 00:24:18.036 [bus debug] ERR: read timeout during skip, switching to no signal
> 2021-04-19 00:24:18.036 [bus error] signal lost
> 2021-04-19 00:24:23.800 [main debug] performing regular tasks
> 2021-04-19 00:24:23.800 [mqtt debug] publish ebusd/global/scan finished
> 2021-04-19 00:24:29.812 [mqtt debug] publish ebusd/global/uptime 16
> 2021-04-19 00:24:33.800 [main debug] performing regular tasks
> 2021-04-19 00:24:43.801 [main debug] performing regular tasks
> 2021-04-19 00:24:45.835 [mqtt debug] publish ebusd/global/uptime 32
> 2021-04-19 00:24:53.801 [main debug] performing regular tasks
> 2021-04-19 00:24:58.276 [bus notice] <ff
> 2021-04-19 00:24:58.276 [bus notice] signal acquired
> 2021-04-19 00:25:00.009 [bus debug] ERR: read timeout during skip, switching to no signal
> 2021-04-19 00:25:00.009 [bus error] signal lost
> 2021-04-19 00:25:01.857 [mqtt debug] publish ebusd/global/uptime 48
> 2021-04-19 00:25:03.802 [main debug] performing regular tasks
> 2021-04-19 00:25:13.802 [main debug] performing regular tasks
> 2021-04-19 00:25:17.879 [mqtt debug] publish ebusd/global/uptime 64
> 2021-04-19 00:25:20.402 [bus notice] <fa
> 2021-04-19 00:25:20.402 [bus notice] signal acquired
> 2021-04-19 00:25:22.013 [bus debug] ERR: read timeout during skip, switching to no signal
> 2021-04-19 00:25:22.014 [bus error] signal lost
> 2021-04-19 00:25:23.802 [main debug] performing regular tasks
> 2021-04-19 00:25:33.803 [main debug] performing regular tasks
> 2021-04-19 00:25:33.902 [mqtt debug] publish ebusd/global/uptime 80
> 2021-04-19 00:25:43.803 [main debug] performing regular tasks
> 2021-04-19 00:25:49.923 [mqtt debug] publish ebusd/global/uptime 96
> 2021-04-19 00:25:53.804 [main debug] performing regular tasks
> 2021-04-19 00:26:03.299 [bus notice] <fa
> 2021-04-19 00:26:03.299 [bus notice] signal acquired
> 2021-04-19 00:26:03.804 [main debug] performing regular tasks
> 2021-04-19 00:26:03.804 [main notice] starting initial full scan
> 2021-04-19 00:26:03.805 [bus info] scan 02 cmd: 3102070400
> 2021-04-19 00:26:03.805 [mqtt debug] publish ebusd/global/scan running
> 2021-04-19 00:26:05.033 [bus info] scan 04 cmd: 3104070400
> 2021-04-19 00:26:05.033 [bus info] scan 05 cmd: 3105070400
> 2021-04-19 00:26:05.033 [bus info] scan 06 cmd: 3106070400
> 2021-04-19 00:26:05.033 [bus info] scan 08 cmd: 3108070400
> 2021-04-19 00:26:05.033 [bus info] scan 09 cmd: 3109070400
> 2021-04-19 00:26:05.033 [bus info] scan 0a cmd: 310a070400
> 2021-04-19 00:26:05.033 [bus info] scan 0b cmd: 310b070400
> 2021-04-19 00:26:05.033 [bus info] scan 0c cmd: 310c070400
> 2021-04-19 00:26:05.034 [bus info] scan 0d cmd: 310d070400
> 2021-04-19 00:26:05.034 [bus info] scan 0e cmd: 310e070400
> 2021-04-19 00:26:05.034 [bus info] scan 12 cmd: 3112070400
> 2021-04-19 00:26:05.034 [bus info] scan 14 cmd: 3114070400
> 2021-04-19 00:26:05.034 [bus info] scan 15 cmd: 3115070400
> 2021-04-19 00:26:05.034 [bus info] scan 16 cmd: 3116070400
> 2021-04-19 00:26:05.034 [bus info] scan 18 cmd: 3118070400
> 2021-04-19 00:26:05.034 [bus info] scan 19 cmd: 3119070400
> 2021-04-19 00:26:05.034 [bus info] scan 1a cmd: 311a070400
> 2021-04-19 00:26:05.034 [bus info] scan 1b cmd: 311b070400
> 2021-04-19 00:26:05.034 [bus info] scan 1c cmd: 311c070400
> 2021-04-19 00:26:05.034 [bus info] scan 1d cmd: 311d070400
> 2021-04-19 00:26:05.034 [bus info] scan 1e cmd: 311e070400
> 2021-04-19 00:26:05.034 [bus info] scan 20 cmd: 3120070400
> 2021-04-19 00:26:05.034 [bus info] scan 21 cmd: 3121070400
> 2021-04-19 00:26:05.034 [bus info] scan 22 cmd: 3122070400
> 2021-04-19 00:26:05.034 [bus info] scan 23 cmd: 3123070400
> 2021-04-19 00:26:05.035 [bus info] scan 24 cmd: 3124070400
> 2021-04-19 00:26:05.035 [bus info] scan 25 cmd: 3125070400
> 2021-04-19 00:26:05.035 [bus info] scan 26 cmd: 3126070400
> 2021-04-19 00:26:05.035 [bus info] scan 27 cmd: 3127070400
> 2021-04-19 00:26:05.035 [bus info] scan 28 cmd: 3128070400
> 2021-04-19 00:26:05.035 [bus info] scan 29 cmd: 3129070400
> 2021-04-19 00:26:05.035 [bus info] scan 2a cmd: 312a070400
> 2021-04-19 00:26:05.035 [bus info] scan 2b cmd: 312b070400
> 2021-04-19 00:26:05.035 [bus info] scan 2c cmd: 312c070400
> 2021-04-19 00:26:05.035 [bus info] scan 2d cmd: 312d070400
> 2021-04-19 00:26:05.035 [bus info] scan 2e cmd: 312e070400
> 2021-04-19 00:26:05.035 [bus info] scan 2f cmd: 312f070400
> 2021-04-19 00:26:05.035 [bus info] scan 32 cmd: 3132070400
> 2021-04-19 00:26:05.035 [bus info] scan 34 cmd: 3134070400
> 2021-04-19 00:26:05.035 [bus info] scan 35 cmd: 3135070400
> 2021-04-19 00:26:05.035 [bus info] scan 36 cmd: 3136070400
> 2021-04-19 00:26:05.035 [bus info] scan 38 cmd: 3138070400
> 2021-04-19 00:26:05.035 [bus info] scan 39 cmd: 3139070400
> 2021-04-19 00:26:05.036 [bus info] scan 3a cmd: 313a070400
> 2021-04-19 00:26:05.036 [bus info] scan 3b cmd: 313b070400
> 2021-04-19 00:26:05.036 [bus info] scan 3c cmd: 313c070400
> 2021-04-19 00:26:05.036 [bus info] scan 3d cmd: 313d070400
> 2021-04-19 00:26:05.036 [bus info] scan 3e cmd: 313e070400
> 2021-04-19 00:26:05.036 [bus info] scan 40 cmd: 3140070400
> 2021-04-19 00:26:05.036 [bus info] scan 41 cmd: 3141070400
> 2021-04-19 00:26:05.036 [bus info] scan 42 cmd: 3142070400
> 2021-04-19 00:26:05.036 [bus info] scan 43 cmd: 3143070400
> 2021-04-19 00:26:05.036 [bus info] scan 44 cmd: 3144070400
> 2021-04-19 00:26:05.036 [bus info] scan 45 cmd: 3145070400
> 2021-04-19 00:26:05.036 [bus info] scan 46 cmd: 3146070400
> 2021-04-19 00:26:05.036 [bus info] scan 47 cmd: 3147070400
> 2021-04-19 00:26:05.036 [bus info] scan 48 cmd: 3148070400
> 2021-04-19 00:26:05.036 [bus info] scan 49 cmd: 3149070400
> 2021-04-19 00:26:05.036 [bus info] scan 4a cmd: 314a070400
> 2021-04-19 00:26:05.037 [bus info] scan 4b cmd: 314b070400
> 2021-04-19 00:26:05.037 [bus info] scan 4c cmd: 314c070400
> 2021-04-19 00:26:05.037 [bus info] scan 4d cmd: 314d070400
> 2021-04-19 00:26:05.037 [bus info] scan 4e cmd: 314e070400
> 2021-04-19 00:26:05.037 [bus info] scan 4f cmd: 314f070400
> 2021-04-19 00:26:05.037 [bus info] scan 50 cmd: 3150070400
> 2021-04-19 00:26:05.037 [bus info] scan 51 cmd: 3151070400
> 2021-04-19 00:26:05.037 [bus info] scan 52 cmd: 3152070400
> 2021-04-19 00:26:05.038 [bus info] scan 53 cmd: 3153070400
> 2021-04-19 00:26:05.038 [bus info] scan 54 cmd: 3154070400
> 2021-04-19 00:26:05.038 [bus info] scan 55 cmd: 3155070400
> 2021-04-19 00:26:05.038 [bus info] scan 56 cmd: 3156070400
> 2021-04-19 00:26:05.038 [bus info] scan 57 cmd: 3157070400
> 2021-04-19 00:26:05.038 [bus info] scan 58 cmd: 3158070400
> 2021-04-19 00:26:05.038 [bus info] scan 59 cmd: 3159070400
> 2021-04-19 00:26:05.038 [bus info] scan 5a cmd: 315a070400
> 2021-04-19 00:26:05.039 [bus info] scan 5b cmd: 315b070400
> 2021-04-19 00:26:05.039 [bus info] scan 5c cmd: 315c070400
> 2021-04-19 00:26:05.039 [bus info] scan 5d cmd: 315d070400
> 2021-04-19 00:26:05.039 [bus info] scan 5e cmd: 315e070400
> 2021-04-19 00:26:05.039 [bus info] scan 5f cmd: 315f070400
> 2021-04-19 00:26:05.039 [bus info] scan 60 cmd: 3160070400
> 2021-04-19 00:26:05.039 [bus info] scan 61 cmd: 3161070400
> 2021-04-19 00:26:05.039 [bus info] scan 62 cmd: 3162070400
> 2021-04-19 00:26:05.039 [bus info] scan 63 cmd: 3163070400
> 2021-04-19 00:26:05.039 [bus info] scan 64 cmd: 3164070400
> 2021-04-19 00:26:05.039 [bus info] scan 65 cmd: 3165070400
> 2021-04-19 00:26:05.039 [bus info] scan 66 cmd: 3166070400
> 2021-04-19 00:26:05.039 [bus info] scan 67 cmd: 3167070400
> 2021-04-19 00:26:05.039 [bus info] scan 68 cmd: 3168070400
> 2021-04-19 00:26:05.040 [bus info] scan 69 cmd: 3169070400
> 2021-04-19 00:26:05.040 [bus info] scan 6a cmd: 316a070400
> 2021-04-19 00:26:05.040 [bus info] scan 6b cmd: 316b070400
> 2021-04-19 00:26:05.040 [bus info] scan 6c cmd: 316c070400
> 2021-04-19 00:26:05.040 [bus info] scan 6d cmd: 316d070400
> 2021-04-19 00:26:05.040 [bus info] scan 6e cmd: 316e070400
> 2021-04-19 00:26:05.040 [bus info] scan 6f cmd: 316f070400
> 2021-04-19 00:26:05.040 [bus info] scan 72 cmd: 3172070400
> 2021-04-19 00:26:05.040 [bus info] scan 74 cmd: 3174070400
> 2021-04-19 00:26:05.040 [bus info] scan 75 cmd: 3175070400
> 2021-04-19 00:26:05.040 [bus info] scan 76 cmd: 3176070400
> 2021-04-19 00:26:05.040 [bus info] scan 78 cmd: 3178070400
> 2021-04-19 00:26:05.040 [bus info] scan 79 cmd: 3179070400
> 2021-04-19 00:26:05.040 [bus info] scan 7a cmd: 317a070400
> 2021-04-19 00:26:05.040 [bus info] scan 7b cmd: 317b070400
> 2021-04-19 00:26:05.040 [bus info] scan 7c cmd: 317c070400
> 2021-04-19 00:26:05.040 [bus info] scan 7d cmd: 317d070400
> 2021-04-19 00:26:05.041 [bus info] scan 7e cmd: 317e070400
> 2021-04-19 00:26:05.041 [bus info] scan 80 cmd: 3180070400
> 2021-04-19 00:26:05.041 [bus info] scan 81 cmd: 3181070400
> 2021-04-19 00:26:05.041 [bus info] scan 82 cmd: 3182070400
> 2021-04-19 00:26:05.041 [bus info] scan 83 cmd: 3183070400
> 2021-04-19 00:26:05.041 [bus info] scan 84 cmd: 3184070400
> 2021-04-19 00:26:05.041 [bus info] scan 85 cmd: 3185070400
> 2021-04-19 00:26:05.041 [bus info] scan 86 cmd: 3186070400
> 2021-04-19 00:26:05.041 [bus info] scan 87 cmd: 3187070400
> 2021-04-19 00:26:05.041 [bus info] scan 88 cmd: 3188070400
> 2021-04-19 00:26:05.041 [bus info] scan 89 cmd: 3189070400
> 2021-04-19 00:26:05.041 [bus info] scan 8a cmd: 318a070400
> 2021-04-19 00:26:05.041 [bus info] scan 8b cmd: 318b070400
> 2021-04-19 00:26:05.041 [bus info] scan 8c cmd: 318c070400
> 2021-04-19 00:26:05.041 [bus info] scan 8d cmd: 318d070400
> 2021-04-19 00:26:05.041 [bus info] scan 8e cmd: 318e070400
> 2021-04-19 00:26:05.041 [bus info] scan 8f cmd: 318f070400
> 2021-04-19 00:26:05.041 [bus info] scan 90 cmd: 3190070400
> 2021-04-19 00:26:05.042 [bus info] scan 91 cmd: 3191070400
> 2021-04-19 00:26:05.042 [bus info] scan 92 cmd: 3192070400
> 2021-04-19 00:26:05.042 [bus info] scan 93 cmd: 3193070400
> 2021-04-19 00:26:05.042 [bus info] scan 94 cmd: 3194070400
> 2021-04-19 00:26:05.042 [bus info] scan 95 cmd: 3195070400
> 2021-04-19 00:26:05.042 [bus info] scan 96 cmd: 3196070400
> 2021-04-19 00:26:05.042 [bus info] scan 97 cmd: 3197070400
> 2021-04-19 00:26:05.042 [bus info] scan 98 cmd: 3198070400
> 2021-04-19 00:26:05.042 [bus info] scan 99 cmd: 3199070400
> 2021-04-19 00:26:05.042 [bus info] scan 9a cmd: 319a070400
> 2021-04-19 00:26:05.042 [bus info] scan 9b cmd: 319b070400
> 2021-04-19 00:26:05.042 [bus info] scan 9c cmd: 319c070400
> 2021-04-19 00:26:05.042 [bus info] scan 9d cmd: 319d070400
> 2021-04-19 00:26:05.042 [bus info] scan 9e cmd: 319e070400
> 2021-04-19 00:26:05.042 [bus info] scan 9f cmd: 319f070400
> 2021-04-19 00:26:05.042 [bus info] scan a0 cmd: 31a0070400
> 2021-04-19 00:26:05.042 [bus info] scan a1 cmd: 31a1070400
> 2021-04-19 00:26:05.043 [bus info] scan a2 cmd: 31a2070400
> 2021-04-19 00:26:05.043 [bus info] scan a3 cmd: 31a3070400
> 2021-04-19 00:26:05.043 [bus info] scan a4 cmd: 31a4070400
> 2021-04-19 00:26:05.043 [bus info] scan a5 cmd: 31a5070400
> 2021-04-19 00:26:05.043 [bus info] scan a6 cmd: 31a6070400
> 2021-04-19 00:26:05.043 [bus info] scan a7 cmd: 31a7070400
> 2021-04-19 00:26:05.043 [bus info] scan a8 cmd: 31a8070400
> 2021-04-19 00:26:05.043 [bus info] scan ab cmd: 31ab070400
> 2021-04-19 00:26:05.043 [bus info] scan ac cmd: 31ac070400
> 2021-04-19 00:26:05.043 [bus info] scan ad cmd: 31ad070400
> 2021-04-19 00:26:05.043 [bus info] scan ae cmd: 31ae070400
> 2021-04-19 00:26:05.043 [bus info] scan af cmd: 31af070400
> 2021-04-19 00:26:05.043 [bus info] scan b0 cmd: 31b0070400
> 2021-04-19 00:26:05.043 [bus info] scan b1 cmd: 31b1070400
> 2021-04-19 00:26:05.043 [bus info] scan b2 cmd: 31b2070400
> 2021-04-19 00:26:05.043 [bus info] scan b3 cmd: 31b3070400
> 2021-04-19 00:26:05.043 [bus info] scan b4 cmd: 31b4070400
> 2021-04-19 00:26:05.044 [bus info] scan b5 cmd: 31b5070400
> 2021-04-19 00:26:05.044 [bus info] scan b6 cmd: 31b6070400
> 2021-04-19 00:26:05.044 [bus info] scan b7 cmd: 31b7070400
> 2021-04-19 00:26:05.044 [bus info] scan b8 cmd: 31b8070400
> 2021-04-19 00:26:05.044 [bus info] scan b9 cmd: 31b9070400
> 2021-04-19 00:26:05.044 [bus info] scan ba cmd: 31ba070400
> 2021-04-19 00:26:05.044 [bus info] scan bb cmd: 31bb070400
> 2021-04-19 00:26:05.044 [bus info] scan bc cmd: 31bc070400
> 2021-04-19 00:26:05.044 [bus info] scan bd cmd: 31bd070400
> 2021-04-19 00:26:05.044 [bus info] scan be cmd: 31be070400
> 2021-04-19 00:26:05.044 [bus info] scan bf cmd: 31bf070400
> 2021-04-19 00:26:05.044 [bus info] scan c0 cmd: 31c0070400
> 2021-04-19 00:26:05.044 [bus info] scan c1 cmd: 31c1070400
> 2021-04-19 00:26:05.044 [bus info] scan c2 cmd: 31c2070400
> 2021-04-19 00:26:05.044 [bus info] scan c3 cmd: 31c3070400
> 2021-04-19 00:26:05.044 [bus info] scan c4 cmd: 31c4070400
> 2021-04-19 00:26:05.044 [bus info] scan c5 cmd: 31c5070400
> 2021-04-19 00:26:05.045 [bus info] scan c6 cmd: 31c6070400
> 2021-04-19 00:26:05.045 [bus info] scan c7 cmd: 31c7070400
> 2021-04-19 00:26:05.045 [bus info] scan c8 cmd: 31c8070400
> 2021-04-19 00:26:05.045 [bus info] scan c9 cmd: 31c9070400
> 2021-04-19 00:26:05.045 [bus info] scan ca cmd: 31ca070400
> 2021-04-19 00:26:05.045 [bus info] scan cb cmd: 31cb070400
> 2021-04-19 00:26:05.045 [bus info] scan cc cmd: 31cc070400
> 2021-04-19 00:26:05.045 [bus info] scan cd cmd: 31cd070400
> 2021-04-19 00:26:05.045 [bus info] scan ce cmd: 31ce070400
> 2021-04-19 00:26:05.045 [bus info] scan cf cmd: 31cf070400
> 2021-04-19 00:26:05.045 [bus info] scan d0 cmd: 31d0070400
> 2021-04-19 00:26:05.045 [bus info] scan d1 cmd: 31d1070400
> 2021-04-19 00:26:05.045 [bus info] scan d2 cmd: 31d2070400
> 2021-04-19 00:26:05.045 [bus info] scan d3 cmd: 31d3070400
> 2021-04-19 00:26:05.045 [bus info] scan d4 cmd: 31d4070400
> 2021-04-19 00:26:05.045 [bus info] scan d5 cmd: 31d5070400
> 2021-04-19 00:26:05.046 [bus info] scan d6 cmd: 31d6070400
> 2021-04-19 00:26:05.046 [bus info] scan d7 cmd: 31d7070400
> 2021-04-19 00:26:05.046 [bus info] scan d8 cmd: 31d8070400
> 2021-04-19 00:26:05.046 [bus info] scan d9 cmd: 31d9070400
> 2021-04-19 00:26:05.046 [bus info] scan da cmd: 31da070400
> 2021-04-19 00:26:05.046 [bus info] scan db cmd: 31db070400
> 2021-04-19 00:26:05.046 [bus info] scan dc cmd: 31dc070400
> 2021-04-19 00:26:05.046 [bus info] scan dd cmd: 31dd070400
> 2021-04-19 00:26:05.046 [bus info] scan de cmd: 31de070400
> 2021-04-19 00:26:05.046 [bus info] scan df cmd: 31df070400
> 2021-04-19 00:26:05.046 [bus info] scan e0 cmd: 31e0070400
> 2021-04-19 00:26:05.046 [bus info] scan e1 cmd: 31e1070400
> 2021-04-19 00:26:05.046 [bus info] scan e2 cmd: 31e2070400
> 2021-04-19 00:26:05.046 [bus info] scan e3 cmd: 31e3070400
> 2021-04-19 00:26:05.047 [bus info] scan e4 cmd: 31e4070400
> 2021-04-19 00:26:05.047 [bus info] scan e5 cmd: 31e5070400
> 2021-04-19 00:26:05.047 [bus info] scan e6 cmd: 31e6070400
> 2021-04-19 00:26:05.047 [bus info] scan e7 cmd: 31e7070400
> 2021-04-19 00:26:05.047 [bus info] scan e8 cmd: 31e8070400
> 2021-04-19 00:26:05.047 [bus info] scan e9 cmd: 31e9070400
> 2021-04-19 00:26:05.047 [bus info] scan ea cmd: 31ea070400
> 2021-04-19 00:26:05.047 [bus info] scan eb cmd: 31eb070400
> 2021-04-19 00:26:05.047 [bus info] scan ec cmd: 31ec070400
> 2021-04-19 00:26:05.047 [bus info] scan ed cmd: 31ed070400
> 2021-04-19 00:26:05.048 [bus info] scan ee cmd: 31ee070400
> 2021-04-19 00:26:05.048 [bus info] scan ef cmd: 31ef070400
> 2021-04-19 00:26:05.048 [bus info] scan f2 cmd: 31f2070400
> 2021-04-19 00:26:05.048 [bus info] scan f4 cmd: 31f4070400
> 2021-04-19 00:26:05.048 [bus info] scan f5 cmd: 31f5070400
> 2021-04-19 00:26:05.048 [bus info] scan f6 cmd: 31f6070400
> 2021-04-19 00:26:05.048 [bus info] scan f8 cmd: 31f8070400
> 2021-04-19 00:26:05.048 [bus info] scan f9 cmd: 31f9070400
> 2021-04-19 00:26:05.049 [bus info] scan fa cmd: 31fa070400
> 2021-04-19 00:26:05.049 [bus info] scan fb cmd: 31fb070400
> 2021-04-19 00:26:05.049 [bus info] scan fc cmd: 31fc070400
> 2021-04-19 00:26:05.049 [bus info] scan fd cmd: 31fd070400
> 2021-04-19 00:26:05.049 [bus debug] ERR: read timeout during skip, switching to no signal
> 2021-04-19 00:26:05.049 [bus error] signal lost
> 2021-04-19 00:26:05.812 [mqtt debug] publish ebusd/global/uptime 112
> 2021-04-19 00:26:13.805 [main debug] performing regular tasks

I notice It receives 1 byte, acquired signal then disconnects...
Any idea what is going wrong here?
I tried multiple combinations of latency without any help...

Thank you
Lenny

**Comment by lennyzaman** [comment]
As an additional info:
Vaillant HR-gas-wandheizgerät mit brennwerttechnik VCW BE 346/5-5 R4
Vaillant VRC 370f

EBUS connected through 2 wire cable (in the heating unit on the EBUS connector(which is also branched into the VRC370f remote unit)

USB cable to connect to Raspberry pi 3 model B+ running Raspbian buster.

I tried a few more settings and with following I read the bus but I only see '<fe' output.(at a very high rate, sometimes also '<ff')
I also flashed the latest PIC firmware to the device (though it reported this was already present)

`ebusd -d /dev/ttyUSB0 --mqtthost=192.168.0.188 --mqttport=1883 --mqttclientid=ebusd1 --mqttuser=openhab --mqttpass=habopen --scanconfig=full -f --configpath=http://ebusd.eu/config/ --loglevel=debug --enablehex --accesslevel=* -p 8889 --lograwdata=bytes`
(The device is now ttyUSB0 iso USB1 as in the before example, also not I use port 8889 as 8888 is already in use on my system)
See following log: 
> 2021-04-19 18:12:56.748 [main notice] ebusd 21.2.v21.2 started with full scan on device /dev/ttyUSB0
> 2021-04-19 18:12:56.749 [main info] loading configuration files from http://ebusd.eu/config/
> 2021-04-19 18:12:56.820 [main info] reading templates /
> 2021-04-19 18:12:56.893 [main info] read templates in /
> 2021-04-19 18:12:56.893 [main info] reading file memory.csv
> 2021-04-19 18:12:56.959 [main info] successfully read file memory.csv
> 2021-04-19 18:12:56.959 [main info] reading file broadcast.csv
> 2021-04-19 18:12:57.033 [main info] successfully read file broadcast.csv
> 2021-04-19 18:12:57.033 [main info] read config files
> 2021-04-19 18:12:57.037 [bus notice] bus started with own address 31/36
> 2021-04-19 18:12:57.038 [main info] registering data handlers
> 2021-04-19 18:12:57.038 [mqtt info] mosquitto version 1.5.7 (compiled with 1.5.7)
> 2021-04-19 18:12:57.058 [mqtt debug] connection requested
> 2021-04-19 18:12:57.058 [main info] registered data handlers
> 2021-04-19 18:12:57.062 [mqtt notice] connection established
> 2021-04-19 18:12:57.062 [mqtt debug] publish ebusd/global/version ebusd 21.2.v21.2
> 2021-04-19 18:12:57.062 [mqtt debug] publish ebusd/global/running true
> 2021-04-19 18:12:57.068 [bus notice] <fe
> 2021-04-19 18:12:57.069 [bus notice] signal acquired
> 2021-04-19 18:12:57.111 [bus notice] <fe
> 2021-04-19 18:12:57.155 [bus notice] <fe
> 2021-04-19 18:12:57.198 [bus notice] <fe
> 2021-04-19 18:12:57.240 [bus notice] <fe
> 2021-04-19 18:12:57.283 [bus notice] <fe
> 2021-04-19 18:12:57.326 [bus notice] <fe
> 2021-04-19 18:12:57.368 [bus notice] <fe
> 2021-04-19 18:12:57.412 [bus notice] <fe
> 2021-04-19 18:12:57.456 [bus notice] <fe
> 2021-04-19 18:12:57.499 [bus notice] <fe
> 2021-04-19 18:12:57.541 [bus notice] <fe
> 2021-04-19 18:12:57.585 [bus notice] <fe
> 2021-04-19 18:12:57.628 [bus notice] <fe
> 2021-04-19 18:12:57.672 [bus notice] <fe
> 2021-04-19 18:12:57.715 [bus notice] <fe

**Comment by lennyzaman** [comment]
output from ebusctl -p 8889 info

> root@raspberrypi1:/home/pi# ebusctl -p 8889 info
> version: ebusd 21.2.v21.2
> update check: OK
> access: *
> signal: no signal
> reconnects: 221
> masters: 1
> messages: 11
> conditional: 0
> poll: 0
> update: 4
> address 31: master #8, ebusd
> address 36: slave #8, ebusd

output from ebusctl -p 8889 scan:

> root@raspberrypi1:/home/pi# ebusctl -p 8889 scan
> empty

**Comment by john30** [comment]
if you jumpered the adapter to enhanced mode, you need to pass "-d enh:/dev/ttyUSB1" to ebusd

**Comment by lennyzaman** [comment]
Hi John30,
I will try that when I am home next week! Thank you for the input!

**Comment by john30** [comment]
closed due to inactivity
