### ISSUE TITLE
How to setup "default gateway" with ebuspicloader

### ISSUE THREAD

**Issue by majowi5** [john30/ebusd#424]
Changing my adapter 3 to Ethernet mode not possible as I do not  find any setup for the default gateway?

To setup a fixed ip-address ebuspicloader offers only options for ip-address and netmask but not for default gateway
How to setup  a default gateway?

**Comment by majowi5** [comment]
workaround identified; not necessary any more

**Comment by john30** [comment]
the gateway is currently set to the first ip address of the network defined by the ip+mask. I'll enhance it to allow different address with next PIC firmware. keeping this one closed, as it is the wrong repo anyway
