### ISSUE TITLE
latest docker is not multi-arch

### ISSUE THREAD

**Issue by andrasg** [john30/ebusd#427]
The `latest` tag docker image seems to be only supporting the `amd64` platform, and therefore fails to start on a rpi.

<img width="1266" alt="image" src="https://user-images.githubusercontent.com/10730249/116782143-c35eaa00-aa87-11eb-8466-27db20d4ceaf.png">

The `devel` tag does have multi-arch images.

**Comment by john30** [comment]
probably same issue as in #415
