### ISSUE TITLE
Every counters are 0 (temp / pressure)

### ISSUE THREAD

**Issue by GuillaumeC** [john30/ebusd#428]
Hello,

I have a vaillant ecovit vkk 366/4 with a VR_70 to control 2 zones with a multimatic VRC700f.

Everything seems to be  correctly detected:

> version: ebusd 21.2.v21.2
update check: OK, broadcast.csv: different version available, vaillant/08.bai.csv: different version available, vaillant/15.b7v.csv: different version available, vaillant/bai.308523.inc: different version available, vaillant/broadcast.csv: different version available, vaillant/errors.inc: different version available, vaillant/general.csv: different version available, vaillant/hcmode.inc: different version available
access: *
signal: acquired
symbol rate: 22
max symbol rate: 152
min arbitration micros: 236
max arbitration micros: 2250
min symbol latency: 5
max symbol latency: 8
reconnects: 0
masters: 3
messages: 636
conditional: 3
poll: 0
update: 10
address 03: master #11
address 08: slave #11, scanned "MF=Vaillant;ID=BAI00;SW=0703;HW=7401", loaded "vaillant/bai.308523.inc" ([HW=7401]), "vaillant/08.bai.csv"
address 10: master #2
address 15: slave #2, scanned "MF=Vaillant;ID=B7V00;SW=0422;HW=5503", loaded "vaillant/15.b7v.csv"
address 31: master #8, ebusd
address 36: slave #8, ebusd
address 52: slave, scanned "MF=Vaillant;ID=VR_70;SW=0109;HW=2903", loaded "vaillant/52.vr_70.csv"

If I ask some params like name or date it's works fine:

> b7v z1RoomZoneMapping = VRC700
b7v z1Name1 = ZONE
b7v z1Name1 = no data stored
b7v z1Name2 = 1 RDC
ebusctl r -c b7v Date  -> 03.05.2021

BUT every temp fields are 0:
> b7v z1RoomTemp = 0.0
b7v WaterPressure = 0.0
b7v z1ActualRoomTempDesired = 0.0
b7v z1DayTemp = 0.0
b7v z1NightTemp = 0.0

Ebusd is launched with the command:
EBUSD_OPTS="--scanconfig=full --configpath=/etc/ebusd --mqtttopic=ebusd/%circuit/%name --mqtthost=xx.xx.xx.xx --mqttport=1883 --mqttlog --mqttjson --port=8888 --accesslevel=*"

I tried without the configpath but the result is the same.

**Comment by john30** [comment]
duplice of #404
