### ISSUE TITLE
Serial connection not wotking

### ISSUE THREAD

**Issue by UlrichGitHub** [john30/ebusd#431]
I recently received a new eBUS Adapter V3.0 but can not connect through the serial interface.
Putty with 115200 8N1 seems to connect but does not show anything as output and does not react on any keyboard keystrokes. Tried other speed settings with no other effect.
I was able to connect through Wemos D1 mini. Changed IP-Address but did not enter the password for my Home-WLAN but a new password. Now with Wemos it tries connecting to the Home-WLAN without success and I can not access through there.
Using USR-ES1 Module instead of the Wemos I can ping the eBUS-Adapter but I do not get a webinterface at the address of the ping (which is different from the address I set before.
So I must get access through the serial interface but can't as described above.
Any help is very much appreciated.

**Comment by john30** [comment]
115200 is not the right speed for normal operation. depending on enhanced or non-enhanced mode, traffic on the serial is on 9600 or 2400 Bd.
there is no web interface on the adapter itself, you need to use something like ebusd to talk to the adapter

**Comment by john30** [comment]
closed due to inactivity
