### ISSUE TITLE
Documentation inconsistancy

### ISSUE THREAD

**Issue by majowi5** [john30/ebusd#434]
**Wiki**
**2. RUN**
--latency=MSEC
Transfer latency in ms [0 for USB, 10 for IP]     **Unit is milliseconds**

**eBus with Raspberry Pi Serial**
--latency=60000 as the 20ms value seems to be not enough.  **Uniit is microseconds**

I suppose microseconds is correct, is it?

**Comment by john30** [comment]
the units were changed recently, thanks for spotting this.
corrected with https://github.com/john30/ebusd/wiki/eBus-with-Raspberry-Pi-Serial/62e600d8576e9ac0289f148c6feb44a1d0a76d42
