### ISSUE TITLE
No Data after a day running via http

### ISSUE THREAD

**Issue by rainscha1** [john30/ebusd#439]
I have follwing situation:
new ebus adapter 3 connected to a weishaupt wrsol 1.1.
raspberry pi: running ebusd service (connected via lan to the ebus adapter)
Openhab3 also running on the raspberry pi.

openhab read cyclic via http request
http://xxxxxxxx:yyyyy/data/wrsol?maxage=0
from the ebusd service.

And yes that works, but only maximum of one day. Than i will get no data anymore.
Solution so solve this problem: Unplug ebus adapter3 and plug in again.

BTW: I didn't got mqtt running on that raspberry pi. I use the mqtt image, configure it, but nothing happens. No logs, nothing.

**Comment by john30** [comment]
please provide some ebusd logs, otherwise it's hard to reproduce

**Comment by john30** [comment]
closed due to inactivity
