### ISSUE TITLE
Update for Debian-Bullseye

### ISSUE THREAD

**Issue by edyso** [john30/ebusd#443]
Can you please update the deb-package für Debian?

In the new Bullseye the version of mosquitto changed to 2 and there is already a fix, issue #380.

Thank you.

**Comment by GrumpyMeow** [comment]
I've created a PR to resolve this issue: https://github.com/john30/ebusd/pull/444

**Comment by john30** [comment]
bullseye is now part of the release binaries since [21.3](https://github.com/john30/ebusd/releases/tag/v21.3)
