### ISSUE TITLE
square brackets [] in JSON node names

### ISSUE THREAD

**Issue by rg-engineering** [john30/ebusd#445]
Since version 21.2 I get some nodes with square brackets in their names. This leads to problems in my application (iobroker.ebus). 
see also https://github.com/rg-engineering/ioBroker.ebus/issues/49

I can reproduce the behavior in my setup:

![grafik](https://user-images.githubusercontent.com/8238668/131211062-af39fff2-0ba9-4cdc-bbb3-a81aceaa9a8e.png)

Do you think I need to address this in my application or is it a problem that you could solve? 
This behavior did not exist up to version 3.3 ...

**Comment by john30** [comment]
brackets are allowed as names in JSON keys afaik, so this is rather an issue to address to iobroker

**Comment by john30** [comment]
closed due to inactivity
