### ISSUE TITLE
Prevent/hide invalid message from logs

### ISSUE THREAD

**Issue by limad** [john30/ebusd#446]
Hi
is there a way to prevent invalid messages showing in logs ?
```
2021-09-02 23:54:52.914 [update notice] received write bai error03 QQ=10:
2021-09-02 23:54:53.149 [update notice] received write bai error04 QQ=10:
```

i'have defined messages like this: 

```
*wi,,,,,,"B503","00",,,,,,,,,
wi,,error03,error03,,,,03,,,,,,,,,
wi,,error04,error04,,,,04,,,,,,,,,

```

grabe detail:
```
1008b503020003 / 00 = 88: bai error03
1008b503020004 / 00 = 73: bai error04
```

Thanks

**Comment by john30** [comment]
what do you mean with invalid messages? there are some options to adjust the logging, [see here](https://github.com/john30/ebusd/wiki/3.1.-TCP-client-commands#logging)

**Comment by limad** [comment]
Hi
As there si no data "00"
dont know what thé message mean .

**Comment by john30** [comment]
there is some data in the master part (the "03") and the response could just mean that e.g. there is currently no error. it could also mean a reset of error messages or something (see [service.inc](https://github.com/john30/ebusd-configuration/blob/master/ebusd-2.1.x/de/vaillant/service.inc))

**Comment by john30** [comment]
closed due to inactivity
