### ISSUE TITLE
OSX

### ISSUE THREAD

**Issue by andig** [john30/ebusd#45]
Would be nice if at least `ebusctl` could run on OSX. To compile you'd need:

    brew install automake autoconf argp-standalone 

Might be nice to add this to the readme?

**Comment by john30** [comment]
added to the [wiki](https://github.com/john30/ebusd/wiki/1.-Build-and-install/dd44ac238f15f60659a20b12568f44accbc501ac)

**Comment by pagaille** [comment]
Additionally : 

`device.cpp:322:35: error: use of undeclared identifier 'TCP_KEEPIDLE' `

I substituted  TCP_KEEPIDLE by TCP_KEEPALIVE. It worked. I guess it should be possible to add some conditional compile statements.

Ref :  https://stackoverflow.com/questions/15860127/how-to-configure-tcp-keepalive-under-mac-os-x
