### ISSUE TITLE
Write values through ebusd-http?

### ISSUE THREAD

**Issue by tinbert** [john30/ebusd#453]
Hi John,
is it possible to write values by using the http-client? It should be possible, should'nt it?

With 
`http://10.0.1.48:8889/data/470/Hc1SFMode?write`
I got:
`{
"470":{
"messages":{
"Hc1SFMode":{
"name":"Hc1SFMode",
"passive":false,
"write":false,
"lastup":1632332853,
"zz":21,
"fields":{
"0":{
"name":"",
"value":"none",
}
}
},
"Hc1SFMode-w":{
"name":"Hc1SFMode",
"passive":false,
"write":true,
"lastup":0,
}
}
},...`

so I thought I could use "Hc1SFMode-w" to achieve this? But what's the syntax?

**Comment by john30** [comment]
no. HTTP currently does not support issuing write messages. It only retrieves what was cached from the last write via the TCP client or from another device.

**Comment by john30** [comment]
closed due to inactivity
