### ISSUE TITLE
NOT LOGGING

### ISSUE THREAD

**Issue by Trilis29** [john30/ebusd#454]
Hello,

EBUSD_OPTS="  -f --scanconfig --accesslevel=* -d enh:/dev/ttyUSB0 -l /var/log/ebusd.log --address=ff --latency=10 --mqttport=1883 --mqtthost=192.168.1.xx --mqttuser=****--mqttpass=*****--mqttchanges --configpath=/etc/ebusd/ --pollinterval=3"

using RPI 3b+ with Raspbian LITE OS 32bit

ebusd is not logging, tried also -l /home/pi/ebusd.log still nothing. Where is the culprit?

By the way --latency=0 causes problems with ttyUSB0 not recognizing, so found out that latency 10 was best.

**Comment by john30** [comment]
is the daemon running at all? and does /dev/ttyUSB0 exist and is writable for the user the daemon is running with?

**Comment by Trilis29** [comment]
attachign systemctl status

`● ebusd.service - LSB: controls ebusd, the daemon for communication with eBUS heating systems.
   Loaded: loaded (/etc/init.d/ebusd; generated)
   Active: activating (start) since Mon 2021-10-25 18:00:56 EEST; 1min 40s ago
     Docs: man:systemd-sysv-generator(8)
Cntrl PID: 540 (ebusd)
    Tasks: 6 (limit: 2059)
   CGroup: /system.slice/ebusd.service
           ├─540 /bin/bash /etc/init.d/ebusd start
           └─551 /usr/bin/ebusd --pidfile /var/run/ebusd.pid -f --scanconfig --accesslevel=* -d enh:/dev/ttyUSB0 -l /var/log/ebusd.log --address=ff --latency=10 --mqttport=1883 `

**Comment by Trilis29** [comment]
i have reinstalled from package again, so when not rebooted it logs to logfile, when I make sudo update-rc.d ebusd enable it runs as USER as supposed ...
RPI3 RaspiOS

**Comment by john30** [comment]
that doesn't answer my questions. do a `ps aux|grep ebusd` and a `ls -la /dev/ttyUSB0`

you could also try to run ebusd in foreground with "-f" (don't forget to stop the service before)

**Comment by john30** [comment]
closed due to inactivity
