### ISSUE TITLE
Update 15.470.csv

### ISSUE THREAD

**Issue by michapr** [john30/ebusd#457]
Hi,

I would like to suggest an update of the file.
```
r;w,,Hc1QuickVetoTemp,Quick Veto Temperatur Heizkreis 1,,,,"3C00",,,temp1,,,manual override setpoint of the first heating circuit
...
r;w,,Hc1SFMode,HC1_SFMode,,,,"5D00",,,UCH,0=none;1=party;2=onedaybankholiday;3=onedayholiday;4=holiday;5=bankholiday;6=quickveto;7=onetimeventilation;8=onetimewater,,activated special function of first
```
Both parameters are writable - and so it is possible to set the QuickVetoTemperature and change the mode as sample from none to quickveto (or something else) for a limited timeframe.

Michael

**Comment by john30** [comment]
please use pull request on [ebusd-configuration](https://github.com/john30/ebusd-configuration/issues/) for such requests
