### ISSUE TITLE
HTTP client stops responding

### ISSUE THREAD

**Issue by pbystrov** [john30/ebusd#459]
I'm using ebusd with E-Service eBus Coupler USB and collecting data from HTTP client with telegraf.
But after some time telegraf either starts to report stale data or stops collecting data at all.

The following is logged by telegraf:
```
Oct 14 17:18:32 vaillant telegraf[2890]: 2021-10-14T14:18:32Z E! [inputs.http] Error in plugin:  [url=http://localhost:8080/data/bai?maxage=120]: Get "http://localhost:8080/data/bai?maxage=120": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
```
and by ebusd:
```
2021-10-14 18:00:31.301 [update error] unable to parse read bai Status16 from 3108b5040116 / 00: ERR: invalid position
2021-10-14 18:00:31.468 [update error] unable to parse read bai Status from 3108b5110103 / 00: ERR: invalid position
2021-10-14 18:00:41.127 [bus error] prepare message part 0: ERR: end of input reached
2021-10-14 18:00:50.890 [bus error] prepare message part 0: ERR: end of input reached
```

Interesting enough -- once stopped, data collection via HTTP resumes back (but not for long) if I run any `ebusctl` command, i.e. `ebusctl i`.

Could you please advise if this behavior is expected or is there anything I can do about it?
Thank you.

Running options:
```
EBUSD_OPTS="--scanconfig --configlang=en --device=/dev/ttyFTDI --httpport=8080 --log=all:error"
```
```
version: ebusd 21.2.v21.2
update check: OK
signal: acquired
symbol rate: 89
max symbol rate: 102
min arbitration micros: 1180
max arbitration micros: 6788
min symbol latency: 4
max symbol latency: 30
reconnects: 0
masters: 2
messages: 214
conditional: 0
poll: 0
update: 10
address 03: master #11
address 08: slave #11, scanned "MF=Vaillant;ID=BAI00;SW=0518;HW=7401", loaded "vaillant/bai.0010002465.inc" ([PROD='0010003961']), "vaillant/08.bai.csv"
address 31: master #8, ebusd
address 36: slave #8, ebusd
```

**Comment by john30** [comment]
after what time does this come up?

**Comment by pbystrov** [comment]
> after what time does this come up?

I wasn't able to find any pattern. This may come up after 20-30 minutes or 3-4 hours after restart.
I'm gathering data every 3 minutes and Telegraf is installed on the same host with ebusd (if that matters).

**Comment by john30** [comment]
please try again with compiling from the current sources

**Comment by john30** [comment]
closed due to inactivity
