### ISSUE TITLE
Docker image env params

### ISSUE THREAD

**Issue by luzik** [john30/ebusd#465]
Many of us are using docker-compose to set up home automation docker images up together.

If I understand it correctly there is no way to pass any extra arguments to ebusd in docker daemon mode

Please consider adding ability to pass EBUSD_OPTS into docker container

**Comment by john30** [comment]
sure, just pass the arguments that you would add to ebusd commandline to the docker run command as noted in the [readme](https://github.com/john30/ebusd/blob/master/contrib/docker/README.md)

**Comment by luzik** [comment]
but how can I run this as daemon ?
I can't also add 'run' into docker-compose.yaml file
Env is quite a standard to pass extra params to docker image, like MYSQL_ROOT_PASSWORD for mariadb docker image

this is standard way of running mariadb docker 
docker run --name some-mysql -e MYSQL_ROOT_PASSWORD=my-secret-pw -d mysql:tag

**Comment by john30** [comment]
just use the compose [command](https://docs.docker.com/compose/compose-file/compose-file-v3/#command) part

**Comment by luzik** [comment]
Oh didn't know that! thanks :)
