### ISSUE TITLE
Missing values. Bad config?

### ISSUE THREAD

**Issue by blanosko** [john30/ebusd#472]
Hi, 

Yesterday my ebus adapter 3 (Wifi) arrived so I connected everything and tried to set it up. My enviroment is Proxmox host on which are HomeAssistant and ebusd as virtual machines. I have MQTT broker on HomeAssistant. Here is some basic info:

Boiler: Protherm Tiger Condens
Thermostat: Thermolink P (Wired) + Outside temperature sensor

Start up options for EBUSD:
`EBUSD_OPTS="-d enh:192.168.0.117:9999 -l /var/log/ebusd.log  --scanconfig --mqtthost=192.168.0.10 --mqttport=1883 --mqttuser=ebusd --mqttpass=pass"`

Result of ebusctl info command:
![image](https://user-images.githubusercontent.com/26611576/141093047-733d6756-6147-4d8e-b6f9-5777e39ab48c.png)

So, problem is that there is very little information on ebus bus. And messages that are decoded does not make any sense:

![image](https://user-images.githubusercontent.com/26611576/141093864-cd9ec02d-9bb2-4c11-a52c-fb1d94510bfd.png)

Is it correct configuration csv that it automaticaly loaded?

Thanks for any answers

**Comment by john30** [comment]
this is the wrong repo for message configuration issues, please use [ebusd-configuration](https://github.com/john30/ebusd-configuration). there are already a couple of tickets related to e7c
