### ISSUE TITLE
Divider/value leading to 0.0 outputs

### ISSUE THREAD

**Issue by ardjanvb** [john30/ebusd#473]
I am new to ebusd, so might be something really stupid I am overlooking. If so, please laugh at me and point me in the right direction after.

Whenever there is a divider defined in the config .csv file, ebusctl is reporting back 0.0 for the specified IDs. When I remove the divider, ebusctl is reporting back the value my unit reads without division.

For example: Aussenlufttemperatur = 7.4 on the screen of unit (in degrees Celsius)

csv divider = 10, ebusctl read Aussenlufttemperatur = 0.0
csv divider = empty, ebusctl read Aussenlufttemperatur = 74

I'm of course trying the get the formatted value to be able to send that to MQTT. What am I missing here?

I am using attached .csv
[7c.renovent-excellent-400.csv](https://github.com/dstrigl/ebusd-config-brink-renovent-excellent-300/blob/master/7c.renovent-excellent-400.csv)

**Comment by john30** [comment]
which ebusd version are you using?

**Comment by ardjanvb** [comment]
I'm using 21.2 which seems to be the newest version available for armhf.

Any chances of a 21.3 version?

Op di 16 nov. 2021 07:37 schreef John ***@***.***>:

**Comment by john30** [comment]
21.3 was published short time ago. anyway I'd prefer if you could try with a build from the latest source

**Comment by ardjanvb** [comment]
It seems like I've got the armhf 21.2 version on my Pi Zero W now. Which
architecture version should I install, since there is no armhf version
available of 21.3? I've tried to update via terminal, yet it responded with
an in release for ebusd.

Sorry for the dumb questions, still exploring the wonderful world of Linux.

Op di 16 nov. 2021 18:57 schreef John ***@***.***>:

**Comment by john30** [comment]
just use the .deb package of the [release](https://github.com/john30/ebusd/releases/tag/v21.3)

**Comment by john30** [comment]
closed due to inactivity
