### ISSUE TITLE
message chaining of random messages

### ISSUE THREAD

**Issue by J0EK3R** [john30/ebusd#48]
It would bei great to enable message chaining of randam messages with different IDs and sizes.

I have the following scenario:
The errorhistory ist stored as memoryblock in the device. To get the complete errorhistory it is necessary to read the block as six messages. Till now you have to define 6 messages differing in ID and size. And you have to communicate each defined message seperately.

Here is an example of the current definition - cutted - and the commands to get the values:
_r,,ErrorHistory1,,,,,"03029F8263",,s,skip,,, ,,s,UCH,,,Byte2 ,E4.ErrorCode,s,UCH,,, -- cut
r,,ErrorHistory2,,,,,"A8B26C",,s,skip,,, ,E4.ThroughputValue,s,UCH,,, -- cut_

**ebusctl r -f ErrorHistory1
ebusctl r -f ErrorHistory2**

And here is the same definition as chained message and only one command to get the complete errorhistory:

_r,,ErrorHistory,,,,,"03029F8263; A8B26C",,s,skip,,, ,,s,UCH,,,Byte2 ,E4.ErrorCode,s,UCH,,, -- cut_

**ebusctl r -f ErrorHistory**

**Comment by john30** [comment]
this is solvable using a different memory block start address right?
therefore closed
