### ISSUE TITLE
Ebusd in docker and Vaillant VSC206

### ISSUE THREAD

**Issue by pepsonEL** [john30/ebusd#485]
Hi I connect adapater 3 to my gas boiler Vaillant VSC206. It is comunnicate by wemos WIFI. It is connected ok.
![adapter](https://user-images.githubusercontent.com/71824185/147204309-e307e702-fe8c-4812-a854-7aa5ee70e296.jpg)
Then i run on my Synology NAS in Docker EBUSD Daemon. with this command:
-f --scanconfig -d tcp:192.168.4.39:9999 --latency\=10 --mqtthost\=192.168.4.6 --mqttport\=1883 --mqttuser\=MYLOGIN --mqttpass\=MYASSWORD

and in MQTT EXPLORER i have only this:
ebusd
global
version = ebusd 21.3.v21.3
running = true
scan = finished
updatecheck = OK
signal = true
uptime = 29296

Why i dont have any other infor from my boiler....

**Comment by john30** [comment]
you need to use the device string that is noted in the web page: enh:192.168.4.39:9999
