### ISSUE TITLE
cant install addon

### ISSUE THREAD

**Issue by Kentrp** [john30/ebusd#486]
Hi When i install addon from repository in HA i get error 
     "Failed to install add-on
      The command '/bin/ash -o pipefail -c apk add --no-cache build-base argp-standalone git mosquitto-dev cmake'                   returned a non-zero code: 5" 
can someone help to resolve this? 
And when I install in docker and want to run i get 
      "raspberrypi:~ $ docker run --rm -it --device=/dev/ttyUSB0 -p 8888 john30/ebusd
      1970-01-01 00:00:03.005 [main error] invalid configPath URL"
 Raspberry +4b, usb-ebus adapter

**Comment by john30** [comment]
can't tell anything about the HA addon, please contact the author.
for ebusd, I can't reproduce. please pull the latest image using `docker pull john30/ebusd`

**Comment by Kentrp** [comment]
kent@raspberrypi:~ $ docker pull john30/ebusd
Using default tag: latest
latest: Pulling from john30/ebusd
Digest: sha256:0e5232148c08bbc073dda25ccbc3436c0871fd01a9446865dfa20ab006f3981f
Status: Image is up to date for john30/ebusd:latest
docker.io/john30/ebusd:latest
kent@raspberrypi:~ $ docker run --rm -it --device=/dev/ttyUSB0 -p 8888 john30/ebusd
1970-01-01 00:00:03.005 [main error] invalid configPath URL
kent@raspberrypi:~ $

**Comment by john30** [comment]
your time is invalid, please check the system time

**Comment by Kentrp** [comment]
kent@raspberrypi:~ $ date
п'ятниця, 24 грудня 2021 14:58:54 +0200

How to update date in docker thank you

**Comment by Kentrp** [comment]
Hi Im reinstall all my system, and all work correct. Thank you for help

**Comment by john30** [comment]
great!
