### ISSUE TITLE
Vaillant VRC 720 with other ID

### ISSUE THREAD

**Issue by snooze83** [john30/ebusd#487]
Hello Friends.
I have a new VRC 720 from Vaillant. My problem is, the ID from the panel is not 72000. 
My panel id is:
"MF=Vaillant;ID=CTLV2;SW=0514;HW=1104"
Iam sure it works with the 15.700.csv, but how can i "say" ebusd that it must take the 15.700.csv?

Please help me.

Greetings Andreas

**Comment by snooze83** [comment]
Hello Friends,
i solved the problem. I have created a hyperlink to 15.700.csv named 15.ctlv2.csv.

Merry Christmas

**Comment by klaus77777777** [comment]
Hello snooze83,

thx for you hint after I read your entry I got it and I was able to solve my issue.
many thx

regards
Klaus

**Comment by mainmind83** [comment]
> Hello snooze83,
> 
> thx for you hint after I read your entry I got it and I was able to solve my issue. many thx
> 
> regards Klaus

Try to copy file 10.700.csv and rename to15.ctlv2.csv

**Comment by stingone** [comment]
> 15.ctlv2.csv

just a check. my id is Vaillant;CTLV2;0514;1104. i copied the 15.720 and renamed it to 15.ctlv2.csv however its not doing anything and not creating a new device under MQTT with the add-on

is it giving me the error below
error reading scan config file vaillant/15.ctlv2.csv for ID "ctlv2", SW0514, HW1104: ERR: end of input reached, vaillant/15.ctlv2.csv:1: ERR: end of input reached, missing message type/name/pbsb

**Comment by snooze83** [comment]
Hello stingone,
dont rename it,  make a hyperlink to 15.700.csv named 15.ctlv2.csv.

Greetings snooze

**Comment by Trapper12** [comment]
Hi snooze83,

I know it is a long time ago, but I am facing the same problem. What do you mean with hyperlink? How and where should I create that?
Regards
Klaus

**Comment by fifalars** [comment]
He means a symbolic link: ln -s on Linux

**Comment by majuss** [comment]
@snooze83 how did you get your panel ID?

**Comment by klaus77777777** [comment]
Hello,

don’t know if I got your question

I did a
ebusctl info and got
…
address 26: slave, scanned „MF=Vaillant;ID=VR_71;SW=0203;HW=5904", loaded "vaillant/26.vr_71.csv“
…

and than I named the file beginning with the address 26 and than the id vr_71 and vr_71 was detected by ebusctl, result of the name is 26.vr_71.csv
good luck

regards

Klaus

**Comment by DrFrankBV** [comment]
I have the same problem with "MF=Vaillant;ID=CTLV2;SW=0514;HW=1104":
I know how to create a symbolic link, but my configs are not local, because I'm using this as config path: 
--configpath=http://ebusd.eu/config/

How can I fix this problem and why is no one created the correct config file in the repository?
Are the CSV files cached somewhere, where I can store local versions?

**Comment by john30** [comment]
it is ongoing: https://github.com/john30/ebusd-configuration/pull/266

**Comment by TeXiCiTy** [comment]
Current sensoComfort thermostat is at version ID=CTLV**3** already...
`address 15: slave #2, scanned "MF=Vaillant;ID=CTLV3;SW=0709;HW=3704"`

**Comment by akloud** [comment]
I created a symbolic link for the CTLV3 pointing to the CTLV2. This worked nicely. 

Still, I have no clue about the general workflow how to track down undecoded values and how to add them to the configuration afterwards.

@john30, would that not be a good addition to the Wiki? Maybe it could encourage more people to dig into the configuration at this level.

**Comment by john30** [comment]
ctlv3 is in [the next folder](https://ebus.github.io/next/)
