### ISSUE TITLE
Adapter 3 + wemos d1 mini = Vaillant VSC206 problems read hardware and configuration

### ISSUE THREAD

**Issue by pepsonEL** [john30/ebusd#488]
Hi. I buy from you Adapter 3 with Wemod D1 Mini. 
My Hardware is Vaillant EcoCompact VSC206, Multimatic VRC700/6, module VR71, remote control VR91 and Vaillant Gateway VR920.
I flashed wemos by latest FW Build: 20211205
Adapter works on IP 192.168.4.39 port 9999
Then on Synology i install Docker and then download latest container ebusD 21.3 and run it by command:
`-f --scanconfig -d enh:192.168.4.39:9999 --latency\=8000 --mqtthost\=192.168.4.6 --mqttport\=1883 --mqttuser\=MY_LOGIN --mqttpass\=MY_PASSWORD`

Then in MQTT Explorer i see sometimes scan BAI, 700, VR71 , VR91 VR920 but sometime i dont see example 700... or VR920. What i do wrong ? Please help me....
Screen below show and logs from event from docker.....
![mqtt1](https://user-images.githubusercontent.com/71824185/147384328-5c3c3733-34a1-4ab3-abb3-0a1ec9b62ac6.jpg)
![mqtt2](https://user-images.githubusercontent.com/71824185/147384329-c922306b-2206-4d0c-b114-e2c4eed4720e.jpg)
![adapter1](https://user-images.githubusercontent.com/71824185/147384372-c870b736-9870-4da7-97ea-65c08677bdb5.jpg)
![adapter2](https://user-images.githubusercontent.com/71824185/147384374-9190c0ae-89be-41d5-8604-a59ef58b7e93.jpg)

LOgs event from docker ebusd
https://pastebin.com/2fiv3sgi

Please help me .....

**Comment by pepsonEL** [comment]
![mqtt3](https://user-images.githubusercontent.com/71824185/147386264-695a6363-2378-4e18-81d8-6e2d0ab201e7.jpg)

**Comment by Christoph1111** [comment]
Did you edit the 15.700.csv to your needs?
Without polling, there is no output.

**Comment by pepsonEL** [comment]
No i dont edit any CSV. I use option --scanconfig and config should be automatically use... ?


**Without polling, there is no output.**

What you mean ?

**Comment by Christoph1111** [comment]
When you "ebusctl i", you see the files which are loaded for decoding. In my case it's 15.700.csv. Lines in this file start with eg.
`r;w,,PrFuelSumHwcThisMonth,ThisMonthsFConsumptionHwc,,,,5100,,,energy4,,,`.
If you want this parameter (PrFuelSumHwcThisMonth) polled, you have to add a priority number from 1 to 9 after the leading **r**. After reloading `ebusctl reload` this parameter is polled and you can watch the output in the log, in the http page or in MQTT browser depending on your `--pollinterval=xx` in EBUSD_OPTS.

For testing (before scrambling your config), just put a `ebusctl read -f PrFuelSumHwcThisMonth` to control that ebusd has read the appropriate config file.

**Comment by pepsonEL** [comment]
One big problem on my Synology docker is that i can not run TERMINAL on container EBUSD. I send issue to support SYnology but wait for resolve problem. 
But if i only run MQTT Explorer and sometime show more info about VRC700 but sometime not show ? Why ? It is run with automatically scan config....

**Comment by Christoph1111** [comment]
Don't know your hardware and without Console it's hard to debug.
Try to change the 15.700.csv. If there is no change, maybe your hw is the problem.

**Comment by pepsonEL** [comment]
But how change 15.700.csv in docker ?

**Comment by Christoph1111** [comment]
Don't know docker, I have classical linux. Without console information, I can't help you.
When ebusd cannot identify your master because of eg. triggering problems on the wires, the csv is not loaded and you have no output. Sometimes it works, sometimes not.

**Comment by pepsonEL** [comment]
Problem on wires ? But all hardware from Vaillant works ok. No problem.... But what problem with wires ?

For me and my opinion adapter is bad quality because all device has less than one year and installation wires is new... also less than one year. This is new house.

**Comment by Christoph1111** [comment]
The ebus wires to your D1?

**Comment by pepsonEL** [comment]
But what you ask?

My Adapter is connected to PLUG in my boiler VSC206.... by wire 2x0,75mm2

**Comment by pepsonEL** [comment]
My Adapter is connected to PLUG in my boiler VSC206.... by wire 2x0,75mm2

**Comment by john30** [comment]
since the synology is not the fastest device, I'd recommend to increase the latency value to 40 ms, i.e. use "--latency\=40" instead of "--latency\=8000" (the factor 1000 is not needed any more)

**Comment by john30** [comment]
closed due to inactivity
