### ISSUE TITLE
RPI 1 B : New install

### ISSUE THREAD

**Issue by kimi1983** [john30/ebusd#493]
Hello,

i have tried several times to install the latest version of ebusd 21.3 on my rpi b.
I am using an old buster distribution since otherwise i am getting errors on compiling ttyebus

When i try to start the ebusd service i get the following 👍 
ebusd.service : Failed with result 'signal'

Can you please help me. I did the installation already several times using my old documentation i did in the days from version 3.1

best regards,
Kim

**Comment by john30** [comment]
have a look at the log file in /var/log/ebusd.log as well as the system log. start ebusd in foreground using the appropriate commandline options

**Comment by john30** [comment]
closed due to inactivity
