### ISSUE TITLE
nur gewollte Werte

### ISSUE THREAD

**Issue by chonghuwa** [john30/ebusd#494]
Hi,

wie kann ich explizit angeben welche Werte abgerufen werden sollen?
Ich brauche nur eine Hand voll.

Danke!

**Comment by john30** [comment]
depends on how you query the values. MQTT/ebusctl/just polling?

**Comment by mwildbolz** [comment]
vielleicht hilft dir das weiter - https://github.com/john30/ebusd/issues/508#issuecomment-1022135737

**Comment by john30** [comment]
closed due to inactivity
