### ISSUE TITLE
Logrotate Error since V21.3

### ISSUE THREAD

**Issue by Nico184** [john30/ebusd#501]
Since I updated to version 21.3 an ubuntu 18.04.6 LTS logrotate doesn't work. The logfile /var/log/ebusd.log is present and grows bigger.
If I start logrotate -d /var/log/ebusd.log manually I get an error massage: 
error: /var/log/ebusd.log:1 lines must begin with a keyword or a filename (possibly in double quotes)
It seems that the ebusd.log is in wrong file format? All other logfiles are treated correctly.
Till version 21.1 it works without problems.
Maybe anyone can give me a hind?
Thanks a lot

**Comment by eh-gh** [comment]
Hi
I think you should give the config file as parameter:
logrotate -d /etc/logrotate.d/ebusd

**Comment by Nico184** [comment]
Hi,
thanks.. my fault - I startes manually with wrong file but if I do like you said, I get this massage:
error: Ignoring /etc/logrotate.d/ebusd because of bad file mode - must be 0644 or 0444.
Any hind?
This is the config for ebus logrotate
`/var/log/ebusd*.log {
	rotate 7
	size 1M
	copytruncate
	compress
	missingok
	notifempty
	daily
	postrotate
		/usr/bin/killall -HUP ebusd
	endscript
}
`

**Comment by eh-gh** [comment]
please check 
ls -l /etc/logrotate.d/ebusd , if the ownership is not root/root change with 

sudo chown root.root /etc/logrotate.d/ebusd
and try again

@john30, i think if the pkg is installed with sudo dpkg -i ... (not as root), the file /etc/logrotate.d/ebusd has no root.root ownership but the user, who runs the installation , which would be required for logrotate

**Comment by Nico184** [comment]
did so,
ownership was `-rwxr-xr-x 1 root root 150 Nov  9 22:52 /etc/logrotate.d/ebusd
`
same behaviour...

**Comment by eh-gh** [comment]
somehow you've got different permissions as mine:

please run additionally:
sudo chmod 0644 /etc/logrotate.d/ebusd

**Comment by Nico184** [comment]
Thanks for help, I changed permissions and now it works since one week.
And many thanks for providing and supporting ebusd to john and the other guys of this community
