### ISSUE TITLE
Add eBUSd to Alpine Linux Repository

### ISSUE THREAD

**Issue by tim-devel** [john30/ebusd#503]
Hi @john30 

Thanks for all your work on eBUSd, it really is a great tool.

@lukasgrebe and I have been developing an  eBUSd for Home Assistant.  I am not sure how much you know about Home Assistant but the addon system allows you to install and configure addon programs through a web interface from within the Home Assistant frontend.

Home Assistant OS is based on Alpine Linux and I would like to submit an APKBUILD file to their repository so that eBUSd can be installed via their package manager.  I have created the APKBUILD ready for submission on the pull below but thought I should contact you before i submit as you are the maintainer of this project.  Do you have any comments or concerns before I submit this to the Alpine repo?

https://github.com/LukasGrebe/ha-addons/pull/23

**Comment by john30** [comment]
interesting, I am in the middle of extending ebusd MQTT to be able to support a variety of integrations and I was starting with homeassistant.
maybe we can check for synergies here?
anyway, as long as you don't expect me to provide support for your integration, I'm fine with it of course.

**Comment by netweaver1970** [comment]
seems indeed a combination of both would be ideal!
@tim-devel (How) would local config files work in HA context? And specifying extra options on the command line? Or is that a next step after creating the add-on?

**Comment by tim-devel** [comment]
Very happy to work with you on this.  To answer your questions:

- I do not expect you to support the add-on.  I will maintain the add-on which is really just a customised dockerfile that can be configured via the Home Assistant web frontend.

- The add-on already supports all runtime options including local config CSVs, wireless device support and TCP/HTTP access

- Your say you are extending MQTT support, what do you have planned?  Not sure if this is what you are thinking but adding MQTT auto discovery for polled messages and eBUSd global messages would be a great addition - https://www.home-assistant.io/docs/mqtt/discovery/

**Comment by john30** [comment]
I was just browsing through the PR and the Dockerfile and was wondering why you're not using the [ebusd docker image](https://hub.docker.com/r/john30/ebusd) directly? It is quite small and ready to use.

Using the HA MQTT discovery is exactly what I am working on.

**Comment by tim-devel** [comment]
@lukasgrebe wrote the dockerfile.  I will have a look at whether we can switch to your dockerfile

**Comment by LukasGrebe** [comment]
Hey - Interesting discussion!

Home Assistant's [Supervisor (docs)](https://developers.home-assistant.io/docs/supervisor/) needs a docker container with some special files eg. to show the configuration UI in home assistant, translation files for the UI or setup communication between containers in Home Assistant OS. see also:[ HomeAssistant Docs on addon development](https://developers.home-assistant.io/docs/add-ons)

Naiv and without a lot of prior knowledge in Home Assistant os/addons, docker or ebusd, the given configuration worked for me. 

I'm sure there are better solutions such as
- loading the given ebusd dockerfile within the addon specific docker file
- modifying the ebusd docker to contain the needed adon files
- something completely different.

Again the current setup is the result of "works for me" without enough background knowledge in the given Topics. Feel free to enhance as best seen fit!
