### ISSUE TITLE
etc/init.d/functions, No such file 

### ISSUE THREAD

**Issue by michal-broda** [john30/ebusd#512]
Hello, I am a beginner, I have RPI4, hassio, for two months trying to install ebusd. Compiled and installed but when I try to turn on, I have information about the missing file functions. What did I do wrong?

**Comment by john30** [comment]
if you're using hassio and you're limited in Linux knowledge, then maybe using the HA supervisor with [this addon](https://github.com/LukasGrebe/ha-addons) might be easier for you
