### ISSUE TITLE
add username/password to MQTT broker connection

### ISSUE THREAD

**Issue by john30** [john30/ebusd#55]

**Comment by legacycode** [comment]
TLS/SSL Support would be great as well :-)

**Comment by john30** [comment]
solved with 73c18ff

**Comment by legacycode** [comment]
Great! Thanks!

**Comment by Vittaly76** [comment]
Thank alot!!!

**Comment by john30** [comment]
the docker image now also supports MQTT by default: https://hub.docker.com/r/john30/ebusd/
