### ISSUE TITLE
Q: In which version can I find MQQT

### ISSUE THREAD

**Issue by absalom-muc** [john30/ebusd#57]
Since I'm very curious to use the MQTT implementation I installed [lastbeforec++11](https://github.com/john30/ebusd/releases/tag/lastbeforec%2B%2B11). 
But there seems to be no MQTT support in this version:
```
ebusd -V
ebusd 3.0pre.p20170130

sudo ebusd --scanconfig --mqttport=1883
ebusd: unrecognized option '--mqttport=1883'
Try `ebusd --help' or `ebusd --usage' for more information.
```
But ebusd --help shows me no MQTT option. Could you lead me to the version including MQTT?

Thank you.
absalom

**Comment by andig** [comment]
See https://github.com/john30/ebusd/issues/56

**Comment by absalom-muc** [comment]
I've seen it but how is it related to my question? I had no problem to build it and ebusd 3.0pre.p20170130 doesn't recognize the MQTT options.
btw: libmosquitto-dev is installed

**Comment by john30** [comment]
please attach the output of ./autogen.sh

**Comment by absalom-muc** [comment]
sorry, libmosquitto-dev was **not** installed. Now it is and I'm able to subsribe to the ebusd messages.

Thank you!
