### ISSUE TITLE
ebusd Segmentation fault

### ISSUE THREAD

**Issue by EnDe** [john30/ebusd#584]
### Description

ebusd crashes with Segmentation fault
RasPi Zero, debian buster, kernel 5.10.103+, armv6l

% apt search ebusd
ebusd/stable,now 22.2 armhf [installed]
  eBUS daemon.

I guess the reason is that the repository https://repo.ebusd.eu/apt/default/buster delivered the armhf binary instead of a armv6 binary.

Any ideas how to fix without building myself?

Thanks.

### Actual behavior

Segmentation fault

### Expected behavior

simply do the work ;-)

### ebusd version

22.2

### ebusd arguments

-h

### Operating system

Debian 10 (Buster) / Raspbian 10 / Ubuntu 18-19

### CPU architecture

other

### Hardware interface

other

### Logs

can provide strace output

**Comment by john30** [comment]
there is no pre-built binary for armv6. you have to build it yourself using e.g. [make_debian.sh](https://github.com/john30/ebusd/blob/master/make_debian.sh)
