### ISSUE TITLE
Saunier Duval boyler

### ISSUE THREAD

**Issue by sorosj** [john30/ebusd#59]
I have bought a "Saunier Duval Semiatec Condense 24" type boyler.
I am trying to control it over an e-bus/ethernet gateway with ebusd using Vaillant commands.
Up till now I can read the state of the waterpump and can swith on/off heating, but nothing else.
Does anybody has e-bus description or config file set to this type of device?
Thanks in advance: Joseph

**Comment by john30** [comment]
first of all, please open this issue in the right project (ebusd-configuration). Additionally, post your scan result, info result and grab result there.
