### ISSUE TITLE
Fehlerhafte Anzeige für Aussentemperatur 15.700

### ISSUE THREAD

**Issue by Anykan** [john30/ebusd#613]
### Description

Hi,

mir ist aufgefallen das über den Befehl ebusd listen, die Aussentemperatur immer mit 0 Angezeigt wird.

`broadcast outsidetemp = 0.000`

Das selbe ist auch unter der http/jsno version im browser.
Schau ich mir jetzt über "ebusctl grab result all" an, bekomme ich folgende Zeile:

`0015b52406020000007300 / 08010073000098af41 = 180: 700 DisplayedOutsideTemp`

nehme ich jetzt den wert 0098af41 und spiel bischen mit den Endians rum kommt 0x41af9800 umgewandelt in float 21.9492 raus, was auch der Aussentemperatur entspricht und auch in der Heizung angezeigt wird.

Diesen Effekt habe ich mit mehreren Werten

VG

### Actual behavior

Werte werden falsch dargestellt

### Expected behavior

Werte werden korrekt dargestellt

### ebusd version

other

### ebusd arguments

EBUSD_OPTS="--scanconfig -d /dev/ttyUSB0 -p 8888 --httpport=801 --configpath=http://ebusd.eu/config/ --mqtthost=192.168.178.51 --mqttport=1883 --mqttjson --accesslevel="*" --latency=20000"

### Operating system

Debian 11 (Bullseye) / Raspbian 11 / Ubuntu 20-21

### CPU architecture

armv7l

### Hardware interface

Esera USB

### Related integration

HTTP

### Logs

0015b52406020000007300 / 08010073000098af41 = 180: 700 DisplayedOutsideTemp

**Comment by john30** [comment]
please stick to the common language: english

you are talking about two completely different messages, the one from the broadcast and the one from the 700 unit. consequently, the values might be completely different including one of them being 0 always. thus, not an ebusd issue but rather an ebusd-configuration
