### ISSUE TITLE
How to set poll priority to a nonpolling value?

### ISSUE THREAD

**Issue by J0EK3R** [john30/ebusd#65]
I just played around with **ebusctl** command to test my message definitions. I was using the "-p" option to set _poll priority_ of the message like it is described in the wiki.

As result I could see ebusd polling the message.

Then I wanted my message not to be polled any more.
I could not find any hint in the wiki how to do this.
Then I tried different things like setting the poll priority to 0 but ebusd was still polling the message.

How do I have to do this?

**Comment by john30** [comment]
this is not possible at the moment. just use a high value for the prio and the poll will be done rarely
