### ISSUE TITLE
V22.3 vs V22.4

### ISSUE THREAD

**Issue by splashmak** [john30/ebusd#664]
### Description

I test ebusd with : 
- raspi 4 raspbian
- Vaillant Ecotec
- VRC 720f
- Esera bridge ( ebusd to ethernet ). 

Everything was ok under tag 22.3

I now wanted to : 
- swich on a rapi 3 b+ raspbian **lite**,  
- new tag is 22.4. 

It compiles but service don't want to start with the same config file. I'm getting : 
- error connecting to localhost:8888 when sending a ebusctl command
- [bus notice] device invalid
- [bus error] unable to open /dev/ttyUSB0: ERR: element not found  ( ??! )

The raspi 4 is always ready to run. I tough that maybe the ESERA tcp server could only able to handle 1 client so I switch off the service but no result. 

### Actual behavior

Can't start it

### Expected behavior

Just want to run it like on V22.3 with the raspberry 4

### ebusd version

22.4

### ebusd arguments

EBUSD_OPTS="--scanconfig --configpath=/home/pi/Downloads/config/ebusd-2.1.x/de/ --device=tcp:127.0.0.1:5000 --mqtthost=127.0.0.1 --mqttport=1883 --mqttuser=MyLogin --mqttpass=MyPassword  --mqttint=/etc/ebusd/mqtt-hassio.cfg  --accesslevel='*' "

### Operating system

other

### CPU architecture

arm64

### Hardware interface

Esera Ethernet

### Related integration

MQTT Home Assistant via mqtt-hassio.cfg

### Logs

[bus notice] device invalid
2022-10-01 10:42:44.971 [bus error] unable to open /dev/ttyUSB0: ERR: element                               not found

**Comment by Dinth** [comment]
Have you updated the OS? If so, have you recompiled and installed ttyebus?

**Comment by splashmak** [comment]
OS is up to date.
So it's a raspberry pi os lite on my 3B+ , it was not the lite version for the working 4.

For ttyebus I don't even know what it s because I'm not using a usb bridge, it's an ethernet with tcp server

**Comment by splashmak** [comment]
What I don't undestand is that I don't use USB and port localhost:8888

**Comment by john30** [comment]
did you adjust the /etc/default/ebusd file to use the net device?

**Comment by splashmak** [comment]
yes for sure

**Comment by john30** [comment]
check it by posting `egrep -v "^#" /etc/default/ebusd` and also post `ps aux|grep ebusd`

and is the OS systemd or SysV based?

**Comment by splashmak** [comment]
Yes, it's the right EBUSD_OPTS

pi          7325  0.0  0.0   5908   736 pts/0    S+   09:39   0:00 grep --color=auto ebusd

it's systemd

Thank you for your help!

**Comment by john30** [comment]
did you adjust the `/lib/systemd/system/ebusd.service` file or create your own `/etc/systemd/system/ebusd.service`

ebusd is not running according to `ps aux`

**Comment by splashmak** [comment]
Yes it's not running, it fails at startup seing in logfile that there is a issue : 
[bus notice] device invalid
2022-10-01 10:42:44.971 [bus error] unable to open /dev/ttyUSB0: ERR: element not found

I did it automaticaly 
systemctl enable/start ebusd

here is the file /lib/systemd/system/ebusd.service

[Unit]
Description=ebusd, the daemon for communication with eBUS heating systems.
After=network-online.target
ConditionPathExists=/var/log

[Service]
Type=forking
Restart=always
RestartSec=30
PIDFile=/var/run/ebusd.pid
EnvironmentFile=-/etc/default/ebusd
ExecStart=/usr/bin/ebusd $EBUSD_OPTS

[Install]
WantedBy=multi-user.target

**Comment by splashmak** [comment]
Ok, It can now start!
I had :
raspberrypi ebusd[7707]: /usr/bin/ebusd: unrecognized option '--mqtthost=127.0.0.1'

So when I remove all the mqtt parameters service start.

![image](https://user-images.githubusercontent.com/77586262/193541545-8679a64c-00f1-4f57-ad6d-5fff77d542fe.png)


So is there a problem with --mqtthost parameter ?

**Comment by john30** [comment]
ah ok. then you have an ebusd version without MQTT support

**Comment by splashmak** [comment]
yes it seems to be the case but I get the source using a simple git clone https://github.com/john30/ebusd.git, autogen, make,...
How can I add the mqtt support?

**Comment by john30** [comment]
as stated in the [wiki](https://github.com/john30/ebusd/wiki/1.-Build-and-install#installing-dependencies): add libmosquitto-dev

**Comment by splashmak** [comment]
Yes MY BAD!
It's ok now. Sorry for that but thank you for you AMAZING JOB!

**Comment by john30** [comment]
great, thanks
