### ISSUE TITLE
contrib script readall.sh does not work

### ISSUE THREAD

**Issue by legacycode** [john30/ebusd#67]
Hi,

the contrib script readall.sh does not work for me. It starts, but stucks with no output. I could work around this issue by inserting the paramater -q 1. I am not really sure, why this problem occurs.

```
netcat version [v1.10-41]
Linux version 3.4.39-h3 (root@wwd) (gcc version 4.6.3 20120201 (prerelease) (crosstool-NG linaro-1.13.1-2012.02-20120222 - Linaro GCC 2012.02) ) #23 SMP PREEMPT Tue Oct 18 13:04:06 CST 2016
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=15.10
DISTRIB_CODENAME=wily
DISTRIB_DESCRIPTION="Ubuntu 15.10"
NAME="Ubuntu"
VERSION="15.10 (Wily Werewolf)"
```

Best regards.

Christian

**Comment by john30** [comment]
weird. would be really interesting what's going on there.
thanks for the patch, was just applied.
