### ISSUE TITLE
Connect to ebusd over network

### ISSUE THREAD

**Issue by stefanheijnen** [john30/ebusd#728]
### Description

I've got an RPi 4 with an Esera eBus Coupler USB. On the RPi (10.0.2.179) it's working as expected:

```
Nov 21 20:30:13 esera ebusd[29085]: 2022-11-21 20:30:13.280 [update notice] sent read ctlv2 Hc1MinFlowTempDesired QQ=31: 35
Nov 21 20:30:13 esera ebusd[29085]: 2022-11-21 20:30:13.485 [update notice] sent read ctlv2 Hc1MixerMovement QQ=31: 0.0
Nov 21 20:30:14 esera ebusd[29085]: 2022-11-21 20:30:14.210 [update notice] sent read ctlv2 Hc1PumpStatus QQ=31: 0
Nov 21 20:30:14 esera ebusd[29085]: 2022-11-21 20:30:14.404 [update notice] sent read ctlv2 Hc1RoomTempSwitchOn QQ=31: thermostat
Nov 21 20:30:14 esera ebusd[29085]: 2022-11-21 20:30:14.595 [update notice] sent read ctlv2 Hc1Status QQ=31: 0
Nov 21 20:30:15 esera ebusd[29085]: 2022-11-21 20:30:15.360 [update notice] sent read ctlv2 Hc1SummerTempLimit QQ=31: 20

```

When I try to connect to it from my openHAB host, I get no signal.

```
ebusd -d 10.0.2.179:8888 --scanconfig -f -p 8888 --latency=10 --enablehex --latency=80 --acquiretimeout=20 --acquireretries=10 --receivetimeout=10 -c /home/openhab3/ebusd-configuration/latest/en
2022-11-21 20:13:53.494 [main notice] ebusd 22.4.v22.4 started with auto scan on device 10.0.2.179:8888
2022-11-21 20:13:53.521 [bus notice] bus started with own address 31/36
2022-11-21 20:15:59.615 [main notice] update check: OK, broadcast.csv: different version available, memory.csv: different version available
```

But ebusctl i gives:

```
version: ebusd 22.4.v22.4
update check: OK, broadcast.csv: different version available, memory.csv: different version available
device: 10.0.2.179:8888
signal: no signal
reconnects: 0
masters: 1
messages: 11
conditional: 0
poll: 0
update: 4
address 31: master #8, ebusd
address 36: slave #8, ebusd

```

Strange thing is, I can connect to it from within the the openHAB ebus addon:

![image](https://user-images.githubusercontent.com/1306331/203141545-9b1c5023-f0e1-40cb-993b-353c3ea23ac0.png)

It detects all my Vailliant devices:

![image](https://user-images.githubusercontent.com/1306331/203141692-90b893d5-a889-4e46-8acc-45e0a2418e61.png)

Only issue is that the items get no data:

![image](https://user-images.githubusercontent.com/1306331/203143168-40178718-9430-4930-bcd9-9898fd16c54e.png)

### Actual behavior

It seems connected to the ebusd but it doesn't get a signal / data.

### Expected behavior

I expect that ebusctl can connect to ebus over the network and gets a signal / detects my ebus components.

### ebusd version

22.4

### ebusd arguments

-d /dev/ttyUSB0 --enablehex --scanconfig=full -f -p 8888 --latency=80000 --acquiretimeout=20000 --acquireretries=10 --receivetimeout=10000 -c /home/esera/ebusd-configuration/latest/en -l /var/log/ebusd.log --httpport=8889 --pollinterval=5 --accesslevel=*

### Operating system

Debian 10 (Buster) / Ubuntu 18-19 / Raspbian 10 / Raspberry Pi OS 10 (including lite)

### CPU architecture

armv7l

### Hardware interface

Esera USB

### Related integration

TCP (cmdline client like ebusctl or netcat)

### Logs

version: ebusd 22.4.v22.4
update check: OK, broadcast.csv: different version available, memory.csv: different version available
device: 10.0.2.179:8888
access: *
signal: no signal
reconnects: 0
masters: 1
messages: 11
conditional: 0
poll: 0
update: 4
address 31: master #8, ebusd
address 36: slave #8, ebusd

**Comment by john30** [comment]
no idea about openhab, but the address+port you connect to seem to be wrong: when ebusd listens on port 8888 for ebusctl connection (or other TCP), then it can't connect to a hardware at the same IP and port (10.0.2.179:8888)
