### ISSUE TITLE
non-zero exit codes on error

### ISSUE THREAD

**Issue by Mathadon** [john30/ebusd#782]
### Description

When issuing an incorrect read command like so:
```
ebusctl r gibberish
ERR: element not found
```
the exit code is zero:
```
echo $?
0
``` 

It would make sense to return a non-zero error code for such cases? This helps to perform error detection in automated scripts.

**Comment by john30** [comment]
hm, the command as such was successful as it established a connection to ebusd and queried it for an answer.
so it would probably have to be a different exit code for that, but that might break hundreds of integrations done with the current behaviour

**Comment by john30** [comment]
added an extra option for that

**Comment by Mathadon** [comment]
Great solution, thank you!
