### ISSUE TITLE
HTTP "update check" json malformed leads to not parseable json output

### ISSUE THREAD

**Issue by AloisKlingler** [john30/ebusd#790]
### Description

the json output is invalid in the field "updatecheck":

```
  "version": "22.4.v22.4-64-g670fb774",
  "updatecheck": "
revision v22.4 available",
  "access": "*",
```

### Actual behavior

the updatecheck field has an linebreak which leads to non-parseable output

### Expected behavior

no linebreak after the : "

### ebusd version

current source from git

### ebusd arguments

-d /dev/ttyUSB0 --configpath=/etc/ebusd/ --latency=100 --loglevel=error --mqtthost=localhost --mqttport=1883 --mqtttopic=brink --accesslevel='*' --httpport=8880 -l /tmp/ebusd.log

### Operating system

Debian 10 (Buster) / Ubuntu 18-19 / Raspbian 10 / Raspberry Pi OS 10 (including lite)

### CPU architecture

other

### Dockerized

None

### Hardware interface

adapter 3.0 USB

### Related integration

HTTP

### Logs

self-compiled current latest sources from github on a rpi 1

```
 "global": {
  "version": "22.4.v22.4-64-g670fb774",
  "updatecheck": "
revision v22.4 available",
  "access": "*",
  "signal": true,
  "symbolrate": 21,
  "maxsymbolrate": 166,
  "minarbitrationmicros": 452,
  "maxarbitrationmicros": 4527,
  "minsymbollatency": 0,
  "maxsymbollatency": 25,
  "qq": 49,
  "reconnects": 0,
  "masters": 2,
  "messages": 76,
  "lastup": 1672744828
 }
```

Workaround: disable updatecheck with --updatecheck=off

**Comment by john30** [comment]
thanks for spotting this, classic copy&paste error
