### ISSUE TITLE
Convert float to int in case of UCH ?

### ISSUE THREAD

**Issue by JuMi2006** [john30/ebusd#8]
While using several commands i saw that using int values on float-objects works fine.
On the other hand i got errors (invalid numeric arguments) by using floats like "2.0" or "3.0" on UCH-objects.

Is it possible to fix it ? This is more a feature-request than an issue.

best regards
Mirko

**Comment by john30** [comment]
I'll check it on the weekend, should be possible.
John

**Comment by JuMi2006** [comment]
Not necessary in near future. In the late evening i found a way to fix it in my 3rd-party-program. But maybe nice to be consistent in acepting float/int to all numeric datatypes.

Mirko

**Comment by john30** [comment]
solved with commit f26e1d0
