### ISSUE TITLE
add "listen unknown" command

### ISSUE THREAD

**Issue by john30** [john30/ebusd#80]

**Comment by brucemiranda** [comment]
Also maybe adding a TimeStamp will be especially helpful with the "listen unknown" command.

**Comment by john30** [comment]
what would be the use case for having a timestamp there? When interpreting the output line programmatically, the time of reception is exactly the timestamp, so I don't see any benefit here.

**Comment by brucemiranda** [comment]
This would be useful if we kept listen running for a long time, say overnight. You can then see what time a particular message was seen on the bus. Ofcourse, one could always direct the telnet output to a file and use a program that adds timestamp to every output line. (e.g. RealTerm)

**Comment by john30** [comment]
all this information is available in ebusd log, so I don't see the benefit

**Comment by brucemiranda** [comment]
Another use case for a listen unknown is that listen will only list out known and configured messages. Listen is often used to look at the messages in real time and you would want to know if any un-configured messages were seen on the bus.
