### ISSUE TITLE
Ebusd PicLoader Doku / jumper settings

### ISSUE THREAD

**Issue by majowi5** [john30/ebusd#804]
### Description

Nach dem update auf die aktuelle Firmware Version (2022-12-31) für den ebus Adapter 3.0 funktionierte die Kommunikation mit den ebus Komponenten nicht mehr.
Konfiguration ebus Adapter 3.0: USB-Mode, enhanced protocol; kein high speed
(Jumper-Einstellung wurde seit mehr als einem Jahr nicht mehr geändert)
PicLoader –variant=u

Nach Umstellung von _enh:_ auf _ens_:: mode im ebusd configuration file funktionierte alles wieder einwandfrei.
Der Dokumentation konnte ich nicht entnehmen, dass man auf „ens“ umstellen muß.
Nach meiner Ansicht sollte man noch in der PicLoader Doku ergänzen, dass mit dem _enhanced mode_ automatisch der _high speed_ mode eingestellt wird und damit auf _ens:_ umgestellt werden muß

Ansonsten funktioniert die Kombination ebus-Adapter und ebusd perfekt!

### Actual behavior

see above

### Expected behavior

see above

### ebusd version

23.1

### ebusd arguments

na

### Operating system

Debian 11 (Bullseye) / Ubuntu 20-21 / Raspbian 11 / Raspberry Pi OS 11 (including lite)

### CPU architecture

armv7l

### Dockerized

None

### Hardware interface

adapter 3.0 USB

### Related integration

TCP (cmdline client like ebusctl or netcat)

### Logs

na

**Comment by john30** [comment]
it is noted in the [documentation](https://adapter.ebusd.eu/picfirmware.en.html#variant), but I agree it could also be part of the ebuspicloader help/logging
