### ISSUE TITLE
Variable Length Strings generating error

### ISSUE THREAD

**Issue by yarwoob** [john30/ebusd#805]
### Description

When a configuration file uses a datatype definition of a variable length string i.e.  STR:* or NTS:* the following error is produced when checking the config files.  ERR: invalid position, data length

e.g. changing from:
r;w,,z1Name2,zone 1 label (second part),,,,1800,,,STR:5,,,name of zone 1
to
r;w,,z1Name2,zone 1 label (second part),,,,1800,,,STR:*,,,name of zone 1

According to https://github.com/john30/ebusd/wiki/4.3.-Builtin-data-types
:* is allowed for the STR datatype.

This config produces variable length response depending on data, hence the attemp to use *
0015b52406020003001800 / 0803031800476e6400    (Response string is "Gnd" + 0x00 at end)
0015b52406020003011800 / 07030318006e6400        (Response String is "nd" + 0x00 at end)
0015b52406020003021800 / 06020318003300            (Response string is "3" + 0x00 at end)

I'm new at this so maybe barking up the wrong tree to fix my problem and I note this STR:* isn't used in an single config file anywhere I can find.

### Actual behavior

ERR: invalid position, data length

### Expected behavior

I would not expect an error at all.

### ebusd version

22.4

### ebusd arguments

 ebusd --checkconfig -c /etc/ebusd --loglevel=debug

### Operating system

Debian 10 (Buster) / Ubuntu 18-19 / Raspbian 10 / Raspberry Pi OS 10 (including lite)

### CPU architecture

armv7l

### Dockerized

None

### Hardware interface

adapter 3.1 RPi

### Related integration

other

### Logs

[main error] error reading config files from /etc/ebusd/: ERR: invalid position, last error: vaillant/15.700.csv:171: ERR: invalid position, data length

**Comment by john30** [comment]
indeed, it should validate the configs nevertheless. I'll check
