### ISSUE TITLE
Valid HDA:3 datatype decode failing

### ISSUE THREAD

**Issue by djwmarcx** [john30/ebusd#819]
### Description

I have a SD Genia Air Max 12. Reads over `errorhistory` are causing the following error:

```
read -c full -i 1 errorhistory
ERR: argument value out of valid range in decode
```

However, using `grab decode` feature I can see all field are actually reasonable values (yes, including the error number 9998!!!).
```
7108b50303010106 / 0a 02  3104 230822 0e27 ff00 = 3
                      UCH VTM  HDA:3  UIN 
 UCH   02=2, 31=49, 04=4, 23=35, 08=8, 22=34, 0e=14, 27=39, ff=-, 00=0
 VTM   3104="04:49", 2308="08:35", 220e="14:34", 27ff="-:39", ff00="00:-"
 BDA:3 310423="31.04.2023", 230822="23.08.2022", 27ff00="27.-.2000"
 UIN   0231=12546, 3104=1073, 0423=8964, 2308=2083, 0822=8712, 220e=3618, 0e27=9998, 27ff=65319, ff00=2558
```

To discover which field is causing the issue, i've modified the `_templates.csv` file ignoring one field at a time until error went away. Ignoring the 3 bytes corresponding to the HDA:3 makes the read work again.

So the question is: ¿How is this possible? The value `grab decode` is showing me for the corresponding bytes is perfectly fine, however the actual read is telling me the HDA:3 decode result is not. ¿Wrong validation?

Thanks!

### Actual behavior

Read is failing:
```
read -c full -i 1 errorhistory
ERR: argument value out of valid range in decode
```

### Expected behavior

Read should work:
```
read -c full -i 1 errorhistory
9;2;09:34;read -c full -i 1 errorhistory
9;2;09:34;23.08.2022;9998
```

### ebusd version

23.1

### ebusd arguments

--scanconfig -d ens:/dev/ttyUSB0 --configpath /config --loglevel=debug --enabledefine --mqtthost=$MQTT_HOST --mqttport=$MQTT_PORT --mqttint=/etc/ebusd/mqtt-hassio.cfg --mqttuser=$MQTT_USER --mqttpass=$MQTT_PASS --mqttjson --mqtttopic=ebusd --enablehex

### Operating system

Debian 11 (Bullseye) / Ubuntu 20-21 / Raspbian 11 / Raspberry Pi OS 11 (including lite)

### CPU architecture

arm64

### Dockerized

latest

### Hardware interface

adapter 3.1 USB

### Logs

ebusd_1  | 2023-01-21 09:48:25.330 [update info] received MS cmd: 7108b50303010106 / 0a0231042308220e270000
ebusd_1  | 2023-01-21 09:48:25.332 [update error] unable to parse poll-read full errorhistory from 7108b50303010106 / 0a0231042308220e270000: ERR: argument value out of valid range

**Comment by john30** [comment]
the polling can't work for messages that need an input parameter (such as the errorhistory with the index input), so that's why it is logged like "unable to parse poll-read full errorhistory...".

the datatype you're referring to does not decode that value:
```bash
ebusctl decode HDA:3 230822
ERR: argument value out of valid range
```
only BDA:3 does, so the definition does not match your data
