### ISSUE TITLE
docker build

### ISSUE THREAD

**Issue by kobza70** [john30/ebusd#82]
I am getting error starting the ebusd docker (debian, jessie 64bit)

ebusd: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ebusd)

Any idea about the reason?

Thanks
Kobza70

**Comment by chri2** [comment]
I had the same problem (trying to start on a synology 64-bit system) and could solve the issue by installing gcc from testing inside the docker image.

**Comment by kobza70** [comment]
thanks, but I I cannot log-in into the docker image since the error ouccurs before the docker is started...

**Comment by john30** [comment]
probably the wrong libraries due to updates in the docker hub.
to avoid this, use the devel version of the image instead.
anyway, the images have just been updated with 753ed44
