### ISSUE TITLE
ebusd keeps rebooting

### ISSUE THREAD

**Issue by rakete1** [john30/ebusd#825]
### Description

I tried my new eBUS Adapter 3 USB on two different machines (Raspberry PI 3 [buster] and a Dell x64 [bullseye]) and I get the exact same result. The service starts up and the device and bus is detected. Some messages are received and suddenly after like 10 seconds no more messages appear in the logfile (/var/log/ebusd.log). 30 seconds afterwards the service is restarted and the same happens again.

### Actual behavior

Service keeps restarting in an endless loop. I haven't seen an error message indicating why the service is always killed.

Output of journalctl:

> -- Journal begins at Sun 2023-01-29 00:58:14 CET, ends at Sun 2023-01-29 11:44:21 CET. --
> Jan 29 08:30:48 atlas systemd[1]: Starting ebusd, the daemon for communication with eBUS heating systems....
> Jan 29 08:30:48 atlas systemd[1]: Started ebusd, the daemon for communication with eBUS heating systems..
> Jan 29 08:31:04 atlas systemd[1]: ebusd.service: Main process exited, code=killed, status=6/ABRT
> Jan 29 08:31:04 atlas systemd[1]: ebusd.service: Failed with result 'signal'.
> Jan 29 08:31:34 atlas systemd[1]: ebusd.service: Scheduled restart job, restart counter is at 1.
> Jan 29 08:31:34 atlas systemd[1]: Stopped ebusd, the daemon for communication with eBUS heating systems..
> Jan 29 08:31:34 atlas systemd[1]: Starting ebusd, the daemon for communication with eBUS heating systems....
> Jan 29 08:31:34 atlas systemd[1]: Started ebusd, the daemon for communication with eBUS heating systems..
> Jan 29 08:31:50 atlas systemd[1]: ebusd.service: Main process exited, code=killed, status=6/ABRT
> Jan 29 08:31:50 atlas systemd[1]: ebusd.service: Failed with result 'signal'.
> Jan 29 08:32:21 atlas systemd[1]: ebusd.service: Scheduled restart job, restart counter is at 2.
> Jan 29 08:32:21 atlas systemd[1]: Stopped ebusd, the daemon for communication with eBUS heating systems..
> Jan 29 08:32:21 atlas systemd[1]: Starting ebusd, the daemon for communication with eBUS heating systems....
> Jan 29 08:32:21 atlas systemd[1]: Started ebusd, the daemon for communication with eBUS heating systems..
> Jan 29 08:32:37 atlas systemd[1]: ebusd.service: Main process exited, code=killed, status=6/ABRT
> Jan 29 08:32:37 atlas systemd[1]: ebusd.service: Failed with result 'signal'.
> Jan 29 08:33:07 atlas systemd[1]: ebusd.service: Scheduled restart job, restart counter is at 3.
> Jan 29 08:33:07 atlas systemd[1]: Stopped ebusd, the daemon for communication with eBUS heating systems..
> Jan 29 08:33:07 atlas systemd[1]: Starting ebusd, the daemon for communication with eBUS heating systems....
> Jan 29 08:33:07 atlas systemd[1]: Started ebusd, the daemon for communication with eBUS heating systems..
> Jan 29 08:33:24 atlas systemd[1]: ebusd.service: Main process exited, code=killed, status=6/ABRT
> Jan 29 08:33:24 atlas systemd[1]: ebusd.service: Failed with result 'signal'.
> Jan 29 08:33:24 atlas systemd[1]: Stopped ebusd, the daemon for communication with eBUS heating systems..
> 

### Expected behavior

Service keeps running.

### ebusd version

23.1

### ebusd arguments

EBUSD_OPTS="--scanconfig --mqtthost 192.168.178.5 --mqttport 1883 --mqttint=/etc/ebusd/mqtt-integration.cfg --mqttjson -d ens:/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_58fe59899d8aec11b5ca6f89d76262f7-if00-port0"

### Operating system

Debian 11 (Bullseye) / Ubuntu 20-21 / Raspbian 11 / Raspberry Pi OS 11 (including lite)

### CPU architecture

x64

### Dockerized

None

### Hardware interface

adapter 3.1 USB

### Related integration

MQTT generic

### Logs

> 2023-01-29 08:30:48.457 [main notice] ebusd 23.1.23.1 started with auto scan on enhanced device /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_58fe59899d8aec11b5ca6f89d76262f7-if00-port0
> 2023-01-29 08:30:48.987 [bus notice] device status: resetting
> 2023-01-29 08:30:48.987 [bus notice] bus started with own address 31/36
> 2023-01-29 08:30:48.991 [mqtt notice] connection established
> 2023-01-29 08:30:48.991 [bus notice] signal acquired
> 2023-01-29 08:30:49.079 [bus notice] device status: reset, supports info
> 2023-01-29 08:30:49.117 [bus notice] device status: extra info: firmware 1.1[8419].2[847f], jumpers 0x33
> 2023-01-29 08:30:49.894 [bus notice] new master 10, master count 2
> 2023-01-29 08:30:49.964 [bus notice] new master 03, master count 3
> 2023-01-29 08:30:49.964 [update notice] received unknown MS cmd: 1008b5110101 / 09694cc002ff6b0100ff
> 2023-01-29 08:30:50.238 [update notice] received unknown MS cmd: 1008b5100900006affffff000000 / 0101
> 2023-01-29 08:30:59.178 [bus notice] scan 08: ;Vaillant;BAI00;0104;7803
> 2023-01-29 08:30:59.178 [update notice] store 08 ident: done
> 2023-01-29 08:30:59.178 [update notice] sent scan-read scan.08  QQ=31: Vaillant;BAI00;0104;7803
> 2023-01-29 08:30:59.178 [bus notice] scan 08: ;Vaillant;BAI00;0104;7803
> 2023-01-29 08:30:59.694 [main notice] read common config file vaillant/broadcast.csv
> 2023-01-29 08:30:59.822 [main notice] read common config file vaillant/scan.csv
> 2023-01-29 08:30:59.951 [main notice] read common config file vaillant/general.csv
> 2023-01-29 08:31:00.025 [update notice] received unknown MS cmd: 1008b5110101 / 09694cc002ff6b0100ff
> 2023-01-29 08:31:00.080 [main notice] read scan config file vaillant/08.bai.csv for ID "bai00", SW0104, HW7803
> 2023-01-29 08:31:00.280 [update notice] sent scan-read scan.08 id QQ=31: 
> 2023-01-29 08:31:00.381 [update notice] received unknown MS cmd: 1008b5100900006affffff000000 / 0101
> 2023-01-29 08:31:00.504 [update notice] sent scan-read scan.08 id QQ=31: 
> 2023-01-29 08:31:00.677 [update notice] sent scan-read scan.08 id QQ=31: 
> 2023-01-29 08:31:00.809 [update notice] received unknown MS cmd: 1008b5110102 / 06033c96468c74
> 2023-01-29 08:31:00.934 [update notice] sent scan-read scan.08 id QQ=31: 21;20;22;0010021924;0001;007635;N6
> 2023-01-29 08:31:01.030 [bus notice] max. symbols per second: 135
> 2023-01-29 08:31:01.391 [main notice] found messages: 224 (3 conditional on 28 conditions, 0 poll, 10 update)
> 2023-01-29 08:31:01.584 [update notice] sent scan-read scan.08 id QQ=31: 21;20;22;0010021924;0001;007635;N6
> 2023-01-29 08:31:01.755 [update notice] sent scan-read scan.08 id QQ=31: 21;20;22;0010021924;0001;007635;N6
> 2023-01-29 08:31:01.928 [update notice] sent scan-read scan.08 id QQ=31: 21;20;22;0010021924;0001;007635;N6
> 2023-01-29 08:31:02.099 [update notice] sent scan-read scan.08 id QQ=31: 21;20;22;0010021924;0001;007635;N6
> 2023-01-29 08:31:02.099 [bus notice] scan 08: ;21;20;22;0010021924;0001;007635;N6
> 2023-01-29 08:31:34.397 [main notice] ebusd 23.1.23.1 started with auto scan on enhanced device /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_58fe59899d8aec11b5ca6f89d76262f7-if00-port0
> 2023-01-29 08:31:34.886 [bus notice] device status: resetting
> 2023-01-29 08:31:34.886 [bus notice] bus started with own address 31/36
> 2023-01-29 08:31:34.889 [mqtt notice] connection established
> 2023-01-29 08:31:34.903 [bus notice] signal acquired
> 2023-01-29 08:31:35.744 [bus notice] device status: reset, supports info
> 2023-01-29 08:31:35.836 [bus notice] device status: extra info: firmware 1.1[8419].2[847f], jumpers 0x33
> 2023-01-29 08:31:40.171 [bus notice] new master 10, master count 2
> 2023-01-29 08:31:40.236 [bus notice] new master 03, master count 3
> 2023-01-29 08:31:40.236 [update notice] received unknown MS cmd: 1008b5110101 / 096a4d8002ff6b0100ff
> 2023-01-29 08:31:40.507 [update notice] received unknown MS cmd: 1008b51009000069ffffff000000 / 0101
> 2023-01-29 08:31:45.083 [bus notice] scan 08: ;Vaillant;BAI00;0104;7803
> 2023-01-29 08:31:45.084 [update notice] store 08 ident: done
> 2023-01-29 08:31:45.084 [update notice] sent scan-read scan.08  QQ=31: Vaillant;BAI00;0104;7803
> 2023-01-29 08:31:45.084 [bus notice] scan 08: ;Vaillant;BAI00;0104;7803
> 2023-01-29 08:31:45.618 [main notice] read common config file vaillant/broadcast.csv
> 2023-01-29 08:31:45.746 [main notice] read common config file vaillant/scan.csv
> 2023-01-29 08:31:45.874 [main notice] read common config file vaillant/general.csv
> 2023-01-29 08:31:46.003 [main notice] read scan config file vaillant/08.bai.csv for ID "bai00", SW0104, HW7803
> 2023-01-29 08:31:46.175 [update notice] sent scan-read scan.08 id QQ=31: 
> 2023-01-29 08:31:46.349 [update notice] sent scan-read scan.08 id QQ=31: 
> 2023-01-29 08:31:46.517 [update notice] sent scan-read scan.08 id QQ=31: 
> 2023-01-29 08:31:46.687 [update notice] sent scan-read scan.08 id QQ=31: 21;20;22;0010021924;0001;007635;N6
> 2023-01-29 08:31:47.103 [main notice] found messages: 224 (3 conditional on 28 conditions, 0 poll, 10 update)
> 2023-01-29 08:31:47.291 [update notice] sent scan-read scan.08 id QQ=31: 21;20;22;0010021924;0001;007635;N6
> 2023-01-29 08:31:47.460 [update notice] sent scan-read scan.08 id QQ=31: 21;20;22;0010021924;0001;007635;N6
> 2023-01-29 08:31:47.632 [update notice] sent scan-read scan.08 id QQ=31: 21;20;22;0010021924;0001;007635;N6
> 2023-01-29 08:31:47.801 [update notice] sent scan-read scan.08 id QQ=31: 21;20;22;0010021924;0001;007635;N6
> 2023-01-29 08:31:47.801 [bus notice] scan 08: ;21;20;22;0010021924;0001;007635;N6
> 2023-01-29 08:31:49.963 [bus notice] scan 15: ;Vaillant;70000;0614;6903
> 2023-01-29 08:31:49.963 [update notice] store 15 ident: done
> 2023-01-29 08:31:49.963 [update notice] sent scan-read scan.15  QQ=31: Vaillant;70000;0614;6903
> 2023-01-29 08:31:49.963 [bus notice] scan 15: ;Vaillant;70000;0614;6903
> 2023-01-29 08:31:50.122 [update notice] sent unknown MS cmd: 3115b5090124 / 09003231323032353030
> 2023-01-29 08:31:50.270 [update notice] received read bai Status01 QQ=10: 53.0;38.5;2.750;-;53.5;on
> 2023-01-29 08:31:50.381 [update notice] sent scan-read scan.15 id QQ=31: 
> 2023-01-29 08:31:50.539 [update notice] sent scan-read scan.15 id QQ=31: 
> 2023-01-29 08:31:50.682 [update notice] received update-write bai SetMode QQ=10: auto;52.5;-;-;0;0;0;0;0;0
> 2023-01-29 08:31:50.794 [update notice] sent scan-read scan.15 id QQ=31: 21;20;25;0020266797;0082;033046;N6
> 2023-01-29 08:31:50.794 [bus notice] scan 15: ;21;20;25;0020266797;0082;033046;N6
> 2023-01-29 08:32:21.147 [main notice] ebusd 23.1.23.1 started with auto scan on enhanced device /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_58fe59899d8aec11b5ca6f89d76262f7-if00-port0
> 2023-01-29 08:32:21.659 [bus notice] device status: resetting
> 2023-01-29 08:32:21.660 [bus notice] bus started with own address 31/36
> 2023-01-29 08:32:21.663 [mqtt notice] connection established
> 2023-01-29 08:32:21.692 [bus notice] signal acquired
> 2023-01-29 08:32:22.451 [bus notice] device status: reset, supports info
> 2023-01-29 08:32:22.559 [bus notice] device status: extra info: firmware 1.1[8419].2[847f], jumpers 0x33
> 2023-01-29 08:32:30.411 [bus notice] new master 10, master count 2
> 2023-01-29 08:32:30.475 [bus notice] new master 03, master count 3
> 2023-01-29 08:32:30.475 [update notice] received unknown MS cmd: 1008b5110101 / 096a4f8002ff6b0100ff
> 2023-01-29 08:32:30.748 [update notice] received unknown MS cmd: 1008b51009000069ffffff000000 / 0101
> 2023-01-29 08:32:31.029 [update notice] received unknown MS cmd: 1008b5040100 / 0a03323208290107238002
> 2023-01-29 08:32:31.294 [update notice] received unknown MS cmd: 1008b5110102 / 06033c96468c74
> 2023-01-29 08:32:31.536 [update notice] received unknown BC cmd: 10feb516080031320829010723
> 2023-01-29 08:32:31.809 [update notice] received unknown MS cmd: 1008b5110100 / 085503124f040f0081
> 2023-01-29 08:32:31.930 [bus notice] scan 08: ;Vaillant;BAI00;0104;7803
> 2023-01-29 08:32:31.930 [update notice] store 08 ident: done
> 2023-01-29 08:32:31.930 [update notice] sent scan-read scan.08  QQ=31: Vaillant;BAI00;0104;7803
> 2023-01-29 08:32:31.930 [bus notice] scan 08: ;Vaillant;BAI00;0104;7803
> 2023-01-29 08:32:32.106 [update notice] received unknown BC cmd: 10feb5160301c002
> 2023-01-29 08:32:32.545 [main notice] read common config file vaillant/broadcast.csv
> 2023-01-29 08:32:32.673 [main notice] read common config file vaillant/scan.csv
> 2023-01-29 08:32:32.802 [main notice] read common config file vaillant/general.csv
> 2023-01-29 08:32:32.931 [main notice] read scan config file vaillant/08.bai.csv for ID "bai00", SW0104, HW7803
> 2023-01-29 08:32:33.108 [update notice] sent scan-read scan.08 id QQ=31: 
> 2023-01-29 08:32:33.276 [update notice] sent scan-read scan.08 id QQ=31: 
> 2023-01-29 08:32:33.444 [update notice] sent scan-read scan.08 id QQ=31: 
> 2023-01-29 08:32:33.616 [update notice] sent scan-read scan.08 id QQ=31: 21;20;22;0010021924;0001;007635;N6
> 2023-01-29 08:32:34.012 [main notice] found messages: 224 (3 conditional on 28 conditions, 0 poll, 10 update)
> 2023-01-29 08:32:34.183 [update notice] sent scan-read scan.08 id QQ=31: 21;20;22;0010021924;0001;007635;N6
> 2023-01-29 08:32:34.358 [update notice] sent scan-read scan.08 id QQ=31: 21;20;22;0010021924;0001;007635;N6
> 2023-01-29 08:32:34.526 [update notice] sent scan-read scan.08 id QQ=31: 21;20;22;0010021924;0001;007635;N6
> 2023-01-29 08:32:34.695 [update notice] sent scan-read scan.08 id QQ=31: 21;20;22;0010021924;0001;007635;N6
> 2023-01-29 08:32:34.695 [bus notice] scan 08: ;21;20;22;0010021924;0001;007635;N6
> 2023-01-29 08:32:36.855 [bus notice] scan 15: ;Vaillant;70000;0614;6903
> 2023-01-29 08:32:36.855 [update notice] store 15 ident: done
> 2023-01-29 08:32:36.855 [update notice] sent scan-read scan.15  QQ=31: Vaillant;70000;0614;6903
> 2023-01-29 08:32:36.855 [bus notice] scan 15: ;Vaillant;70000;0614;6903
> 2023-01-29 08:32:37.013 [update notice] sent unknown MS cmd: 3115b5090124 / 09003231323032353030
> 2023-01-29 08:32:37.171 [update notice] sent scan-read scan.15 id QQ=31: 
> 2023-01-29 08:32:37.329 [update notice] sent scan-read scan.15 id QQ=31: 
> 2023-01-29 08:32:37.487 [update notice] sent scan-read scan.15 id QQ=31: 21;20;25;0020266797;0082;033046;N6
> 2023-01-29 08:32:37.487 [bus notice] scan 15: ;21;20;25;0020266797;0082;033046;N6
> 2023-01-29 08:33:07.897 [main notice] ebusd 23.1.23.1 started with auto scan on enhanced device /dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_58fe59899d8aec11b5ca6f89d76262f7-if00-port0
> 2023-01-29 08:33:08.407 [bus notice] device status: resetting
> 2023-01-29 08:33:08.407 [bus notice] bus started with own address 31/36
> 2023-01-29 08:33:08.411 [mqtt notice] connection established
> 2023-01-29 08:33:08.435 [bus notice] signal acquired
> 2023-01-29 08:33:09.155 [bus notice] device status: reset, supports info
> 2023-01-29 08:33:09.168 [bus notice] device status: extra info: firmware 1.1[8419].2[847f], jumpers 0x33
> 2023-01-29 08:33:10.604 [bus notice] new master 10, master count 2
> 2023-01-29 08:33:10.670 [bus notice] new master 03, master count 3
> 2023-01-29 08:33:10.670 [update notice] received unknown MS cmd: 1008b5110101 / 096c53c002ff6b0100ff
> 2023-01-29 08:33:10.945 [update notice] received unknown MS cmd: 1008b5100900006affffff000000 / 0101
> 2023-01-29 08:33:18.576 [bus notice] scan 08: ;Vaillant;BAI00;0104;7803
> 2023-01-29 08:33:18.576 [update notice] store 08 ident: done
> 2023-01-29 08:33:18.576 [update notice] sent scan-read scan.08  QQ=31: Vaillant;BAI00;0104;7803
> 2023-01-29 08:33:18.576 [bus notice] scan 08: ;Vaillant;BAI00;0104;7803
> 2023-01-29 08:33:20.688 [update notice] received unknown MS cmd: 1008b5110101 / 096c53c002ff6b0100ff
> 2023-01-29 08:33:20.959 [update notice] received unknown MS cmd: 1008b5100900006affffff000000 / 0101
> 2023-01-29 08:33:21.037 [main notice] read common config file vaillant/broadcast.csv
> 2023-01-29 08:33:21.166 [main notice] read common config file vaillant/scan.csv
> 2023-01-29 08:33:21.274 [main notice] read common config file vaillant/general.csv
> 2023-01-29 08:33:21.402 [main notice] read scan config file vaillant/08.bai.csv for ID "bai00", SW0104, HW7803
> 2023-01-29 08:33:21.609 [update notice] sent scan-read scan.08 id QQ=31: 
> 2023-01-29 08:33:21.778 [update notice] sent scan-read scan.08 id QQ=31: 
> 2023-01-29 08:33:21.950 [update notice] sent scan-read scan.08 id QQ=31: 
> 2023-01-29 08:33:22.122 [update notice] sent scan-read scan.08 id QQ=31: 21;20;22;0010021924;0001;007635;N6
> 2023-01-29 08:33:22.539 [main notice] found messages: 224 (3 conditional on 28 conditions, 0 poll, 10 update)
> 2023-01-29 08:33:22.727 [update notice] sent scan-read scan.08 id QQ=31: 21;20;22;0010021924;0001;007635;N6
> 2023-01-29 08:33:22.900 [update notice] sent scan-read scan.08 id QQ=31: 21;20;22;0010021924;0001;007635;N6
> 2023-01-29 08:33:23.071 [update notice] sent scan-read scan.08 id QQ=31: 21;20;22;0010021924;0001;007635;N6
> 2023-01-29 08:33:23.240 [update notice] sent scan-read scan.08 id QQ=31: 21;20;22;0010021924;0001;007635;N6
> 2023-01-29 08:33:23.240 [bus notice] scan 08: ;21;20;22;0010021924;0001;007635;N6
> 

The attached log file contains also a test with "--loglevel=DEBUG" option set. But even with this log level there is no error message visible before the service is killed.
[ebusd.log](https://github.com/john30/ebusd/files/10529572/ebusd.log)

**Comment by rakete1** [comment]
Just as a side node: The dockerized version of ebusd is running fine.

**Comment by john30** [comment]
please check a foreground run with the following arguments and post the result:
`./ebus/git/clean-ebusd/src/ebusd/ebusd -f -s --checkconfig --log all:debug`
it would be interesting to have that from the dockerized version and the directly installed ones

**Comment by rakete1** [comment]
This?

> root@atlas:~# ebusd -f -s --checkconfig --log all:debug
> 2023-01-30 09:27:19.251 [main notice] ebusd 23.1.23.1 performing configuration check...
> 2023-01-30 09:27:19.251 [main info] loading configuration files from https://cfg.ebusd.eu/
> 2023-01-30 09:27:19.400 [main info] reading templates /
> 2023-01-30 09:27:19.529 [main info] read templates in /
> 2023-01-30 09:27:19.529 [main info] reading file memory.csv
> 2023-01-30 09:27:19.657 [main info] successfully read file memory.csv
> 2023-01-30 09:27:19.657 [main info] reading file broadcast.csv
> 2023-01-30 09:27:19.806 [main info] successfully read file broadcast.csv
> 2023-01-30 09:27:19.806 [main info] read config files, got 11 messages
> 2023-01-30 09:27:19.806 [main notice] found messages: 11 (0 conditional on 0 conditions, 0 poll, 4 update)
> 
> 
> root@atlas:~# docker run -it --name=ebusd-debug john30/ebusd -f -s --checkconfig --log all:debug
> 2023-01-30 08:30:44.342 [main notice] ebusd 23.1.23.1 performing configuration check...
> 2023-01-30 08:30:44.342 [main info] loading configuration files from https://cfg.ebusd.eu/
> 2023-01-30 08:30:44.449 [main info] reading templates /
> 2023-01-30 08:30:44.558 [main info] read templates in /
> 2023-01-30 08:30:44.558 [main info] reading file memory.csv
> 2023-01-30 08:30:44.667 [main info] successfully read file memory.csv
> 2023-01-30 08:30:44.667 [main info] reading file broadcast.csv
> 2023-01-30 08:30:44.775 [main info] successfully read file broadcast.csv
> 2023-01-30 08:30:44.776 [main info] read config files, got 11 messages
> 2023-01-30 08:30:44.776 [main notice] found messages: 11 (0 conditional on 0 conditions, 0 poll, 4 update)

**Comment by rakete1** [comment]
I did one more run with ebusd in the foreground. Finally I got an error message:

> root@atlas:~# ebusd -f -s --log all:debug --scanconfig --mqtthost 192.168.178.5 --mqttport 1883 --mqttint=/etc/ebusd/mqtt-integration.cfg --mqttjson -d ens:/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_58fe59899d8aec11b5ca6f89d76262f7-if00-port0 > ebusd-run.log
> terminate called after throwing an instance of 'std::bad_alloc'
>   what():  std::bad_alloc
> Aborted

 Unfortunately it does not say which alloc caused the error. Attached is the [ebusd-run.log](https://github.com/john30/ebusd/files/10533923/ebusd-run.log)

I added the [output](https://github.com/john30/ebusd/files/10533965/valgrind-out.txt) of this valgrind run:

```
valgrind --leak-check=full \
         --show-leak-kinds=all \
         --track-origins=yes \
         --verbose \
         --log-file=valgrind-out.txt \
         ebusd -f -s --log all:debug --scanconfig --mqtthost 192.168.178.5 --mqttport 1883 --mqttint=/etc/ebusd/mqtt-integration.cfg --mqttjson -d ens:/dev/serial/by-id/usb-Silicon_Labs_CP2102N_USB_to_UART_Bridge_Controller_58fe59899d8aec11b5ca6f89d76262f7-if00-port0
```

**Comment by john30** [comment]
can you compile it with [debug settings](https://github.com/john30/ebusd/wiki/1.-Build-and-install#configuration-with-autoconf) and try to reproduce with that binary?

**Comment by wimleers** [comment]
`ebusd` ran fine for months.

I enabled MQTT yesterday. That worked fine in the morning and afternoon. And now … `ebusd` is endlessly rebooting. Coincidence? 🤔 

The error I'm seeing is slightly different:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```

I think the context in which it happens is likely relevant:
```
2023-05-19 09:38:09.121 [bus notice] bus started with own address 31/36
2023-05-19 09:38:09.121 [main info] registering data handlers
2023-05-19 09:38:09.121 [mqtt info] mosquitto version 2.0.11 (compiled with 2.0.11)
2023-05-19 09:38:09.121 [main info] registered data handlers
2023-05-19 09:38:09.122 [mqtt notice] connection established
2023-05-19 09:38:09.142 [bus notice] signal acquired
2023-05-19 09:38:09.166 [bus notice] new master 00, master count 2
2023-05-19 09:38:09.366 [bus notice] new master 10, master count 3
2023-05-19 09:38:09.381 [bus notice] new master 71, master count 4
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
```
Note how the MQTT connection was established just as it is connecting to the EBus. 💡

So I tried my theory and **disabled the MQTT integration. Result: no more crash.** This is with the latest version: `23.1`. Running in Docker.

**Comment by wimleers** [comment]
> Just as a side node: The dockerized version of ebusd is running fine.

Looks like my use case shows the opposite is also possible.

This is really starting to sound like a classical race condition bug.

**Comment by john30** [comment]
same thing here: compile it with debug settings as stated above and try to reproduce

**Comment by wimleers** [comment]
> same thing here: compile it with debug settings as stated above and try to reproduce

Happy to do so. But pointers on how to do that when using a dockerized `ebusd` would be very much appreciated! 😇

**Comment by wimleers** [comment]
I had adopted a lot of `r1`, `r9` etc. entries to automatically poll, as documented at https://github.com/john30/ebusd/wiki/4.1.-Message-definition. Then I reverted many. `ebusd` worked reliably again, even while using MQTT.

Just now, I added a bunch more of those. And it started crashing in the same way again.

This means there is likely a bug in either:
- higher frequency of MQTT updates
- handling of more polling

**Comment by wimleers** [comment]
## Configuration
It keeps happening, now with fewer polled messages (42 instead of >50), and a poll interval of `5` instead of `2`:
```
services:
  ebusd:
    image: john30/ebusd:v23.1
    container_name: ebusd
    restart: unless-stopped
    volumes:
      - /Volumes/dev/ebusd/ebusd-configuration/ebusd-2.1.x/en:/etc/ebusd-configuration
      - ~/ebusd/log:/var/log/ebusd
    ports:
      - 8888:8888
      # when enabling the HTTP port, add it to the published ports as well:
      - 8080:8080
    devices: []
    environment:
      TZ: Europe/Brussels
      EBUSD_DEVICE: esp-ebus.local:3333
      EBUSD_CONFIGPATH: /etc/ebusd-configuration
      EBUSD_SCANCONFIG: "full"
      EBUSD_CONFIGLANG: "en"
      EBUSD_POLLINTERVAL: 5
      EBUSD_HTTPPORT: 8080
      EBUSD_UPDATECHECK: "off"

      EBUSD_LOGFILE: "/var/log/ebusd/ebusd.log"
      EBUSD_LOGAREAS: "all"
      EBUSD_LOGLEVEL: "info"
      EBUSD_LOGRAWDATA: ""
      EBUSD_LOGRAWDATAFILE: "/var/log/ebusd/raw.log"
      EBUSD_LOGRAWDATASIZE: 1000

      EBUSD_MQTTHOST: "mist.local"
      EBUSD_MQTTPORT: 1883
      EBUSD_MQTTCLIENTID: "ebusd"
      EBUSD_MQTTTOPIC: "ebusd"
      EBUSD_MQTTRETAIN: ""
      EBUSD_MQTTQOS: 2
      EBUSD_MQTTINT: "/etc/ebusd/mqtt-integration.cfg"
      EBUSD_MQTTVERBOSE: ""
```

## Typical crash
```
2023-05-24 11:02:24.263 [bus info] send/receive symbol latency 0 - 17 ms
2023-05-24 11:02:24.263 [update info] sent MS cmd: 3108b51a0405ff3213 / 0aff081926000000000000
2023-05-24 11:02:24.263 [update notice] sent poll-read hmu CopHwcMonth QQ=31: 3.8
2023-05-24 11:02:24.296 [bus info] send/receive symbol latency 0 - 30 ms
2023-05-24 11:02:25.542 [update info] received MS cmd: 7108b5110107 / 0a001300c1083c00000000
2023-05-24 11:02:25.543 [update notice] received read hmu State QQ=71: 0;19;193;8
2023-05-24 11:02:28.610 [main notice] ebusd 23.1.23.1 started with auto scan on device esp-ebus.local:3333
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
2023-05-24 11:02:28.610 [main info] loading configuration files from /etc/ebusd-configuration/
2023-05-24 11:02:28.617 [main info] reading templates /
2023-05-24 11:02:28.619 [main info] read templates in /
2023-05-24 11:02:28.619 [main info] reading file broadcast.csv
2023-05-24 11:02:28.623 [main info] successfully read file broadcast.csv
2023-05-24 11:02:28.623 [main info] reading file memory.csv
2023-05-24 11:02:28.625 [main info] successfully read file memory.csv
2023-05-24 11:02:28.625 [main info] read config files, got 11 messages
2023-05-24 11:02:28.808 [bus notice] bus started with own address 31/36
```

## Next attempts to resolve this/pin down the cause:
I'm going to try:

1. reduce the number of polled messages
2. increase `EBUSD_LATENCY`
3. remove the `EBUSD_MQTTVERBOSE` flag
4. remove the `EBUSD_MQTTRETAIN` flag

**Comment by wimleers** [comment]
Apparently it can happen even while booting:
```
2023-05-24 11:43:05.672 [main info] read templates in /
2023-05-24 11:43:05.672 [main info] reading file broadcast.csv
2023-05-24 11:43:05.675 [main info] successfully read file broadcast.csv
2023-05-24 11:43:05.675 [main info] reading file memory.csv
2023-05-24 11:43:05.677 [main info] successfully read file memory.csv
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
2023-05-24 11:43:05.677 [main info] read config files, got 11 messages
2023-05-24 11:43:05.939 [bus notice] bus started with own address 31/36
2023-05-24 11:43:05.939 [bus notice] signal acquired
2023-05-24 11:43:05.939 [main info] registering data handlers
2023-05-24 11:43:05.939 [mqtt info] mosquitto version 2.0.11 (compiled with 2.0.11)
```
… or is the logging order meaningless? 🤔

**Comment by wimleers** [comment]
Now with 36 polled messages and
```
services:
  ebusd:
    image: john30/ebusd:v23.1
    container_name: ebusd
    restart: unless-stopped
    volumes:
      - /Volumes/dev/ebusd/ebusd-configuration/ebusd-2.1.x/en:/etc/ebusd-configuration
      - ~/ebusd/log:/var/log/ebusd
    ports:
      - 8888:8888
      # when enabling the HTTP port, add it to the published ports as well:
      - 8080:8080
    devices: []
    environment:
      TZ: Europe/Brussels
      EBUSD_DEVICE: esp-ebus.local:3333
      EBUSD_LATENCY: 40
      EBUSD_CONFIGPATH: /etc/ebusd-configuration
      EBUSD_SCANCONFIG: "full"
      EBUSD_CONFIGLANG: "en"
      EBUSD_POLLINTERVAL: 5
      EBUSD_HTTPPORT: 8080
      EBUSD_UPDATECHECK: "off"

      EBUSD_LOGFILE: "/var/log/ebusd/ebusd.log"
      EBUSD_LOGAREAS: "all"
      EBUSD_LOGLEVEL: "info"
      EBUSD_LOGRAWDATA: ""
      EBUSD_LOGRAWDATAFILE: "/var/log/ebusd/raw.log"
      EBUSD_LOGRAWDATASIZE: 1000

      EBUSD_MQTTHOST: "mist.local"
      EBUSD_MQTTPORT: 1883
      EBUSD_MQTTCLIENTID: "ebusd"
      EBUSD_MQTTTOPIC: "ebusd"
      EBUSD_MQTTRETAIN: ""
      EBUSD_MQTTQOS: 2
      EBUSD_MQTTINT: "/etc/ebusd/mqtt-integration.cfg"
```

Still crashes:
```
2023-05-24 12:00:41.321 [main notice] ebusd 23.1.23.1 started with auto scan on device esp-ebus.local:3333
2023-05-24 12:00:41.321 [main info] loading configuration files from /etc/ebusd-configuration/
2023-05-24 12:00:41.325 [main info] reading templates /
2023-05-24 12:00:41.328 [main info] read templates in /
2023-05-24 12:00:41.328 [main info] reading file broadcast.csv
2023-05-24 12:00:41.329 [main info] successfully read file broadcast.csv
2023-05-24 12:00:41.329 [main info] reading file memory.csv
2023-05-24 12:00:41.331 [main info] successfully read file memory.csv
2023-05-24 12:00:41.331 [main info] read config files, got 11 messages
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
2023-05-24 12:00:41.475 [bus notice] bus started with own address 31/36
2023-05-24 12:00:41.475 [main info] registering data handlers
2023-05-24 12:00:41.475 [mqtt info] mosquitto version 2.0.11 (compiled with 2.0.11)
2023-05-24 12:00:41.477 [main info] registered data handlers
2023-05-24 12:00:41.480 [mqtt notice] connection established
2023-05-24 12:00:41.546 [bus notice] signal acquired
2023-05-24 12:00:41.882 [bus notice] new master 10, master count 2
2023-05-24 12:00:41.936 [bus notice] new master 03, master count 3
```
😞

**Comment by john30** [comment]
compile with debug as [stated in wiki](https://github.com/john30/ebusd/wiki/1.-Build-and-install#configuration-with-autoconf) ("...debuggable version...")

**Comment by wimleers** [comment]
Switching to the [official `eBUS` v5 adapter](https://adapter.ebusd.eu/v5/) did not help.

Updating from `23.1` to `23.2` did. Not a single crash since! 👍 Zero other changes.

**Comment by john30** [comment]
considered fixed
