### ISSUE TITLE
problems with config

### ISSUE THREAD

**Issue by HeinzSam** [john30/ebusd#83]
Hi, 

this is my current config:

> 
> version: ebusd 3.0pre.27f28eb
> update check: revision f252b07 available
> signal: acquired
> symbol rate: 57
> max symbol rate: 149
> reconnects: 0
> masters: 3
> messages: 600
> conditional: 213
> poll: 3
> update: 58
> address 03: master #11
> address 08: slave #11, scanned "MF=Vaillant;ID=EHP00;SW=0419;HW=7201", loaded "vaillant/08.ehp.csv"
> address 10: master #2
> address 15: slave #2, scanned "MF=Vaillant;ID=UIH00;SW=0374;HW=6901", loaded "vaillant/15.uih.csv"
> address 23: slave, scanned "MF=Vaillant;ID=EHP00;SW=0419;HW=7201", loaded "vaillant/23.ehp.cc.csv"
> address 25: slave, scanned "MF=Vaillant;ID=EHP00;SW=0419;HW=7201", loaded "vaillant/25.ehp.hwc.csv"
> address 31: master #8, ebusd
> address 36: slave #8, ebusd
> address 50: slave, scanned "MF=Vaillant;ID=EHP00;SW=0419;HW=7201", loaded "vaillant/50.ehp.mc.csv"
> 
> 

vwmon works fine everthing ok, currently I want to start a warm water load but the write command doesn't work. Please any hint for what I do wrong:

> write -c ehp load on
> ERR: element not found

> **scan result**
> 08;Vaillant;EHP00;0419;7201;21;13;42;0010009074;0006;005332;N8
> 15;Vaillant;UIH00;0374;6901;21;13;28;0020101780;0907;008822;N5
> 23;Vaillant;EHP00;0419;7201;21;13;42;0010009074;0006;005332;N8
> 25;Vaillant;EHP00;0419;7201;21;13;42;0010009074;0006;005332;N8
> 50;Vaillant;EHP00;0419;7201;21;13;42;0010009074;0006;005332;N8

the service itself sends errors which I don't understand:

> 2017-04-19 19:20:13.670 [update error] unable to parse ehp Mode from 1008b51009000240000000000002 / 00: ERR: invalid position
> 2017-04-19 19:20:25.702 [update error] unable to parse ehp Mode from 1008b51009000240000000000002 / 00: ERR: invalid position
> 2017-04-19 19:20:37.789 [update error] unable to parse ehp Mode from 1008b51009000240000000000002 / 00: ERR: invalid position
> 2017-04-19 19:20:50.072 [update error] unable to parse ehp Mode from 1008b51009000240000000000002 / 00: ERR: invalid position
> 2017-04-19 19:21:01.912 [update error] unable to parse ehp Mode from 1008b51009000240000000000002 / 00: ERR: invalid position

Thanks for any support

**Comment by john30** [comment]
not an ebusd issue but rather ebusd-configuration, but anyway:
I guess you need to issue the command on the mixer circuit rather than the ehp. It's weird, I know:)
your ehp is newer than the one matching the configuration files. in order to get rid of that message, remove the last field from the hcmode.inc mode message.
