### ISSUE TITLE
MQTT stops on invalid value

### ISSUE THREAD

**Issue by russss** [john30/ebusd#85]
If ebusd gets an "invalid position" error on reading a value, it causes an error which stops MQTT messages for that circuit being published until ebusd is restarted. The error raised is:

```
2017-05-11 13:08:27.841 [mqtt error] decode bai HwcTempDesired: ERR: invalid position
```

**Comment by russss** [comment]
[edit: removed incorrect assumption]

I'm using ebusd 3.0pre.340f862.

**Comment by john30** [comment]
I'm afraid I can't reproduce this behaviour. The decode error is correctly logged but the next valid decodable message gets posted regularly on MQTT.

**Comment by russss** [comment]
Yes, I can't reproduce this now. I think it might have been a bug in the code I was using to receive the MQTT messages, sorry!
