### ISSUE TITLE
Home Assistant Addon

### ISSUE THREAD

**Issue by mainmind83** [john30/ebusd#889]
### Description

Without external docker installation, more easy integration addon on Home Assistant OS like:

https://github.com/LukasGrebe/ha-addons

**Comment by Koky05** [comment]
Most of all HA Addons are docker containers. So result is same but you do not need to configure it manually.

**Comment by mainmind83** [comment]
I know, but it makes it easy to integrate into existing HA SO installations. Maybe they know each other ;D

**Comment by john30** [comment]
what's the issue then? use the addon and you're fine. it is also listed in the wiki and yes, we had the one or the other discussion
