### ISSUE TITLE
TEM controller: time and date combined?

### ISSUE THREAD

**Issue by sporkbyspork** [john30/ebusd#908]
### Description

While trying to access a TEM ES 5941 FW controller, I decoded this:
10fe 0700 09 0080 230818 25050423
with the following matches:
BTI   230818="18:08:23"
BDA   23081825="23.08.2025", 25050423="25.05.2023"
BDZ   23081825="23.08.2025", 25050423="25.05.2023"

How do I represent this in my CSV file? I found nothing about splitting, offsetting or otherwise manipulating data.
I (as expected) get an error if I just use date or time.

**Comment by sporkbyspork** [comment]
Argh, it's in templates.csv.

**Comment by john30** [comment]
exactly, simply build a chain of fields
