### ISSUE TITLE
Configuration for TEM ES 5941 FW

### ISSUE THREAD

**Issue by sporkbyspork** [john30/ebusd#909]
### Description

I'd like to create a configuration for the TEM ES 5941 FW controller.

It presents itself as TEM;25467;0041;0010.
I receive only very limited data (e.g. time and date) by listening on the bus.
In issue https://github.com/john30/ebusd/issues/209 it is stated that I might have to query the registers manually.

How do I do that?

For example, the language selection is saved in ID 04:056.

There is a bit more information about the available data in the datasheet of a Modbus interface (https://www.taconova.com/fileadmin/downloads/BA/Modbus_Interface.pdf) if that helps.

P.S.: the new V5 adapter is really great! :+1:

**Comment by john30** [comment]
this is clearly not an ebusd issue, but [ebusd-configuration](https://github.com/john30/ebusd-configuration).
