### ISSUE TITLE
Continuous : Error	my_client_socket_send: send: errno 11 in easi log

### ISSUE THREAD

**Issue by LD40** [john30/ebusd#921]
### Description

When I look in easi interface, I see tha the logs are filled with "Error	my_client_socket_send: send: errno 11" messages.
(not directly related to ebusd, but did'nt find how to post an issue on v5 adapter itself)

### Actual behavior

between 15 and 30 per minute messages "Error	my_client_socket_send: send: errno 11" 

### Expected behavior

no error messages

### ebusd version

23.1

### ebusd arguments

EBUSD_OPTS="--scanconfig -d ens:192.168.1.244:9999 --httpport=8889"

### Operating system

Debian 11 (Bullseye) / Ubuntu 20-21 / Raspbian 11 / Raspberry Pi OS 11 (including lite)

### CPU architecture

armv7l

### Dockerized

None

### Hardware interface

other

### Related integration

other

### Logs

(easi log and not ebusd log)

09:10:03 | Error | my_client_socket_send: send: errno 11
09:10:05 | Error | my_client_socket_send: send: errno 11
09:10:09 | Error | my_client_socket_send: send: errno 11
09:10:11 | Error | my_client_socket_send: send: errno 11
09:10:13 | Error | my_client_socket_send: send: errno 11
09:10:15 | Error | my_client_socket_send: send: errno 11
09:10:18 | Error | my_client_socket_send: send: errno 11
09:10:23 | Error | my_client_socket_send: send: errno 11
09:10:28 | Error | my_client_socket_send: send: errno 11
09:10:33 | Error | my_client_socket_send: send: errno 11
09:10:34 | Error | my_client_socket_send: send: errno 11
09:10:37 | Error | my_client_socket_send: send: errno 11
09:10:38 | Error | my_client_socket_send: send: errno 11
09:10:38 | Error | my_client_socket_send: send: errno 11
09:10:43 | Error | my_client_socket_send: send: errno 11
09:10:45 | Error | my_client_socket_send: send: errno 11
09:10:47 | Error | my_client_socket_send: send: errno 11
09:10:47 | Error | my_client_socket_send: send: errno 11
09:10:48 | Error | my_client_socket_send: send: errno 11
09:10:50 | Error | my_client_socket_send: send: errno 11
09:10:53 | Error | my_client_socket_send: send: errno 11
09:10:54 | Error | my_client_socket_send: send: errno 11
09:10:55 | Error | my_client_socket_send: send: errno 11
09:10:56 | Error | my_client_socket_send: send: errno 11
09:10:58 | Error | my_client_socket_send: send: errno 11

**Comment by john30** [comment]
issues related to adapter 5 are [tracked here](https://github.com/john30/ebusd-esp32/issues).

the message occurs when sending eBUS data to ebusd via TCP is not quick enough, i.e. the queue is full. probably you have a bad wifi signal strength or other wifi issues that should be solved
