### ISSUE TITLE
getting error message "invalid position in decode" when trying to read values from circuit "sc"

### ISSUE THREAD

**Issue by UnderPalms** [john30/ebusd#929]
### Description

When I try to read all values from circuit "sc" I get the message "ERR: invalid position in decode". This error occurs for example when executing "ebusctl read SolGain". 
For all other objects which are not related to the circuit "sc" the ebus daemon is working fine and delivering sufficient values.

### Actual behavior

When reading values from circuit "sc" getting error message "ERR: invalid position in decode"

### Expected behavior

I expected proper values to be received. For example for "SolGain"

### ebusd version

23.1

### ebusd arguments

EBUSD_OPTS="--configpath=http://ebusd.eu/config/  -d ens:/dev/ttyAMA0 -p 8888 --latency=50 -receivetimeout=60000 -l /var/log/ebusd.log --scanconfig=full --httpport=8889 --htmlpath=/var/ebusd/html --accesslevel=* --enablehex

### Operating system

Debian 11 (Bullseye) / Ubuntu 20-21 / Raspbian 11 / Raspberry Pi OS 11 (including lite)

### CPU architecture

x64

### Dockerized

None

### Hardware interface

other

### Related integration

TCP (cmdline client like ebusctl or netcat)

### Logs

2023-05-10 21:47:50.564 [main notice] ebusd 23.1.23.1-9-g1895339e started with auto scan on device /dev/ttyUSB0
2023-05-10 21:47:50.886 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:47:50.889 [bus notice] bus started with own address 31/36
2023-05-10 21:47:50.890 [bus notice] device invalid
2023-05-10 21:47:55.890 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:47:55.898 [bus notice] device invalid
2023-05-10 21:48:00.899 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:48:00.899 [bus notice] device invalid
2023-05-10 21:48:05.900 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:48:05.900 [bus notice] device invalid
2023-05-10 21:48:10.900 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:48:10.901 [bus notice] device invalid
2023-05-10 21:48:15.901 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:48:15.901 [bus notice] device invalid
2023-05-10 21:48:20.902 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:48:20.902 [bus notice] device invalid
2023-05-10 21:48:25.903 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:48:25.903 [bus notice] device invalid
2023-05-10 21:48:30.903 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:48:30.904 [bus notice] device invalid
2023-05-10 21:48:35.904 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:48:35.905 [bus notice] device invalid
2023-05-10 21:48:40.905 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:48:40.905 [bus notice] device invalid
2023-05-10 21:48:45.906 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:48:45.906 [bus notice] device invalid
2023-05-10 21:48:50.907 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:48:50.907 [bus notice] device invalid
2023-05-10 21:48:55.907 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:48:55.908 [bus notice] device invalid
2023-05-10 21:49:00.908 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:49:00.908 [bus notice] device invalid
2023-05-10 21:49:05.909 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:49:05.909 [bus notice] device invalid
2023-05-10 21:49:10.910 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:49:10.910 [bus notice] device invalid
2023-05-10 21:49:15.910 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:49:15.911 [bus notice] device invalid
2023-05-10 21:49:20.911 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:49:20.911 [bus notice] device invalid
2023-05-10 21:49:25.912 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:49:25.912 [bus notice] device invalid
2023-05-10 21:49:30.913 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:49:30.913 [bus notice] device invalid
2023-05-10 21:49:35.914 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:49:35.914 [bus notice] device invalid
2023-05-10 21:49:40.914 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:49:40.915 [bus notice] device invalid
2023-05-10 21:49:45.915 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:49:45.915 [bus notice] device invalid
2023-05-10 21:49:50.916 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:49:50.916 [bus notice] device invalid
2023-05-10 21:49:55.917 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:49:55.917 [bus notice] device invalid
2023-05-10 21:50:00.917 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:50:00.918 [bus notice] device invalid
2023-05-10 21:50:01.107 [main notice] update check: revision 23.1 available
2023-05-10 21:50:05.918 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:50:05.919 [bus notice] device invalid
2023-05-10 21:50:10.919 [bus error] unable to open /dev/ttyUSB0: ERR: element not found
2023-05-10 21:50:10.919 [bus notice] device invalid
2023-05-10 21:50:15.920 [bus error] unable to open /dev/ttyUSB0: ERR: element not found

**Comment by john30** [comment]
the log does not match the start parameters and thus is irrelevant.
anyway, I guess the circuit is not capable of answering to the SolGain query and as such responds empty which will lead to the exact error report. you can check by looking at the hex bytes of that message (e.g. grab command)

**Comment by UnderPalms** [comment]
Thanks John, 
indeed there's something wrong with my log. However, I copied that in as it represents the last entries saved in the log and also because the issue-mask required to fill something for the log-part.
I tried the grab command and indeed there're a lot of messages related to that circuit "sc" with the bus address "ec".
Here's the extract:


peter@raspberrypi:~ $ ebusctl grab result
1008b5110100 / 0832041b001f000080 = 731
1008b5160111 / 090105040e0430040a04 = 1
100ab5160111 / 00 = 1
1026b5160111 / 090103010e0130010301 = 1
10edb5160111 / 00 = 1
10feb510020601 = 155
01ecb5040110 / 0a00800080008000800080 = 1991
01ecb5040134 / 03000001 = 701
01feb505054ef51c0080 = 685
1008b5120204ff / 0101 = 150
1008b513020508 / 00 = 156
100ab505020400 / 00 = 1
1006b50903295600 / 065600f51c0000 = 76
1008b5100305ff01 / 0101 = 143
1006b5080707000030006d02 / 00 = 46
1006b50807070000a0031402 / 00 = 102
1008b516081000ffff0400212e / 0b0000ff0400c92e5431344c = 1
1008b516081002ffff0400812d / 0b0207ff04008b2d88b9ba49 = 34
100ab5050433000400 / 00 = 1
1026b5030c0700ffffffffffffffffffff / 0101 = 49
1026b516081000ffff0304212e / 0b2000ff0304c92e00000000 = 2
1026b516081002ffff0304a12e / 0b2201ff0304a12e00000000 = 21
1026b5230b0401010000000000220200 / 0101 = 1
01ecb505084d00040000000000 / 00 = 1
01ecb505084d00050000640100 / 00 = 1
01ecb505084d01030000190100 / 00 = 1
01ecb505084d01050000640100 / 00 = 1
01ecb505084d02040000190100 / 00 = 1
01ecb505084d02050000640100 / 00 = 3
01ecb505084d02090001000000 / 00 = 1
01ecb505084d03020000000000 / 00 = 1
01ecb505084d030500004b0100 / 00 = 2
01ecb505084d06030000000000 / 00 = 1
01ecb505084d060500004b0100 / 00 = 1
01ecb505084d07010000000000 / 00 = 1
01ecb505084d07040000640100 / 00 = 1
01ecb505084d09020000000000 / 00 = 1
01ecb505084d0b010000000000 / 00 = 1
01ecb505084d0b030000000000 / 00 = 2
01ecb505084d0b040000190100 / 00 = 2
01ecb505084d0c030000000000 / 00 = 1
01ecb505084d0c080001000000 / 00 = 1
01ecb505084d0d020000000000 / 00 = 2
01ecb505084d0f010000000000 / 00 = 2
01ecb505084d0f040000000000 / 00 = 1
01ecb505084d0f060001000000 / 00 = 1
01ecb505084d10010000000000 / 00 = 1
01ecb505084d110400004b0100 / 00 = 2
01ecb505084d12020000000000 / 00 = 1
01ecb505084d13040000190100 / 00 = 2
01ecb505084d14010000000000 / 00 = 2
01ecb505084d14050000640100 / 00 = 1
01ecb505084d15030000000000 / 00 = 1
01ecb505084d15050000640100 / 00 = 1
01ecb505084d160500004b0100 / 00 = 1
01ecb505084d17010000000000 / 00 = 1
01ecb505084d17020000000000 / 00 = 3
01ecb505084d17030000000000 / 00 = 1
01ecb505084d17050000640100 / 00 = 2
01ecb505084d1a010000000000 / 00 = 2
01ecb505084d1c010000000000 / 00 = 1
01ecb505084d1c030000000000 / 00 = 1
01ecb505084d1d020000000000 / 00 = 1
01ecb505084d1e010000000000 / 00 = 1
01ecb505084d1e090001000000 / 00 = 2
01ecb505084d1f010000000000 / 00 = 1
01ecb505084d1f020000000000 / 00 = 1
01ecb505084d21040000190100 / 00 = 1
01ecb505084d22030000190100 / 00 = 1
01ecb505084d220500004b0100 / 00 = 1
01ecb505084d22090001000000 / 00 = 1
01ecb505084d23020000000000 / 00 = 1
01ecb505084d24010000000000 / 00 = 1
01ecb505084d25010000000000 / 00 = 1
01ecb505084d27010000000000 / 00 = 1
01ecb505084d270400004b0100 / 00 = 3
01ecb505084d28040000320100 / 00 = 1
01ecb505084d28090001000000 / 00 = 1
01ecb505084d29030000190100 / 00 = 1
01ecb505084d2a010000000000 / 00 = 2
01ecb505084d2a030000190100 / 00 = 1
01ecb505084d2a040000320100 / 00 = 1
01ecb505084d2a060001000000 / 00 = 1
01ecb505084d2b010000000000 / 00 = 1
01ecb505084d2b030000190100 / 00 = 2
01ecb505084d2b040000190100 / 00 = 1
01ecb505084d2d020000000000 / 00 = 2
01ecb505084d2e040000000000 / 00 = 1
01ecb505084d2f030000190100 / 00 = 1
01ecb505084d31040000000000 / 00 = 1
01ecb505084d32050000640100 / 00 = 1
01ecb505084d32090001000000 / 00 = 1
01ecb505084d33010000000000 / 00 = 1
01ecb505084d340500004b0100 / 00 = 2
01ecb505084d35030000190100 / 00 = 1
01ecb505084d38010000000000 / 00 = 1
01ecb505084d390400004b0100 / 00 = 1
01ecb505084d3a010000000000 / 00 = 1
01ecb505084d3a040000640100 / 00 = 1
01ecb505084d3b030000190100 / 00 = 1
01ecb505084d3b070001000000 / 00 = 1
01ecb505084d3c020000000000 / 00 = 1
01ecb505084d3c030000190100 / 00 = 1
01ecb505084d3e010000000000 / 00 = 1
01ecb505084d3e040000190100 / 00 = 1
01ecb505084d3f010000000000 / 00 = 1
01ecb505084d3f050000320100 / 00 = 1
01ecb505084d3f060000190100 / 00 = 1
01ecb505084d40020000000000 / 00 = 1
01ecb505084d40030000190100 / 00 = 1
01ecb505084d40080001000000 / 00 = 2
01ecb505084d43010000000000 / 00 = 1
01ecb505084d43020000000000 / 00 = 1
01ecb505084d43060001000000 / 00 = 1
01ecb505084d44010000000000 / 00 = 1
01ecb505084d45060001000000 / 00 = 1
01ecb505084d46010000000000 / 00 = 2
01ecb505084d46030000190100 / 00 = 1
01ecb505084d460500004b0100 / 00 = 1
01ecb505084d47030000190100 / 00 = 1
01ecb505084d47070001000000 / 00 = 1
01ecb505084d48010000000000 / 00 = 1
01ecb505084d48030000190100 / 00 = 1
01ecb505084d48040000000000 / 00 = 1
01ecb505084d480500004b0100 / 00 = 2
01ecb505084d49010000000000 / 00 = 1
01ecb505084d49090001000000 / 00 = 1
01ecb505084d4a0500004b0100 / 00 = 4
01ecb505084d4b010000000000 / 00 = 2
01ecb505084d4c0500004b0100 / 00 = 1
01ecb505084d4c090001000000 / 00 = 1
01ecb505084d4d010000000000 / 00 = 1
01ecb505084d4d0500004b0100 / 00 = 3
01ecb505084d4e020000000000 / 00 = 1
01ecb505084d4f010000000000 / 00 = 1
01ecb505084d4f020000000000 / 00 = 1
01ecb505084d4f030000190100 / 00 = 1
01ecb505084d4f0500004b0100 / 00 = 2
01ecb505084d4f080001000000 / 00 = 1
01ecb505084d4f090001000000 / 00 = 1
01ecb505084d50010000000000 / 00 = 1
01ecb505084d500500004b0100 / 00 = 2
01ecb505084d510500004b0100 / 00 = 2
01ecb505084d52010000000000 / 00 = 1
01ecb505084d52050000640100 / 00 = 1
01ecb505084d53010000000000 / 00 = 1
01ecb505084d53020000000000 / 00 = 1
01ecb505084d53050000640100 / 00 = 2
01ecb505084d53070001000000 / 00 = 1
01ecb505084d540500004b0100 / 00 = 5
01ecb505084d55020000000000 / 00 = 2
01ecb505084d56030000190100 / 00 = 1
01ecb505084d560500004b0100 / 00 = 1
01ecb505084d56070001000000 / 00 = 1
01ecb505084d57010000000000 / 00 = 1
01ecb505084d57030000190100 / 00 = 1
01ecb505084d57040000190100 / 00 = 1
01ecb505084d570500004b0100 / 00 = 1
01ecb505084d58010000000000 / 00 = 1
01ecb505084d58020000000000 / 00 = 1
01ecb505084d58030000320100 / 00 = 1
01ecb505084d58050000640100 / 00 = 1
01ecb505084d59010000000000 / 00 = 1
01ecb505084d59020000000000 / 00 = 1
01ecb505084d59030000190100 / 00 = 1
01ecb505084d5a010000000000 / 00 = 2
01ecb505084d5a0500004b0100 / 00 = 1
01ecb505084d5c060001000000 / 00 = 1
01ecb505084d5d010000000000 / 00 = 1
01ecb505084d5e080001000000 / 00 = 1
01ecb505084d5f020000000000 / 00 = 1
01ecb505084d60010000000000 / 00 = 1
01ecb505084d64010000000000 / 00 = 2
01ecb505084d66010000000000 / 00 = 1
01ecb505084d66090001000000 / 00 = 1
01ecb505084d68030000190100 / 00 = 1
01ecb505084d68060001000000 / 00 = 1
01ecb505084d69010000000000 / 00 = 1
01ecb505084d6b010000000000 / 00 = 1
01ecb505084d6b030000000000 / 00 = 1
01ecb505084d6c010000000000 / 00 = 1
01ecb505084d6d010000000000 / 00 = 1
01ecb505084d6d030000000000 / 00 = 1
01ecb505084d6e030000000000 / 00 = 1
01ecb505084d6f010000000000 / 00 = 1
01ecb505084d6f030000000000 / 00 = 1
01ecb505084d6f060001000000 / 00 = 1
01ecb505084d70010000000000 / 00 = 2
01ecb505084d70030000320100 / 00 = 3
01ecb505084d70070001000000 / 00 = 1
01ecb505084d72030000000000 / 00 = 1
01ecb505084d73020000000000 / 00 = 1
01ecb505084d73030000000000 / 00 = 1
01ecb505084d75030000320100 / 00 = 1
01ecb505084d76010000000000 / 00 = 3
01ecb505084d77030000000000 / 00 = 1
01ecb505084d77090001000000 / 00 = 1
01ecb505084d78070001000000 / 00 = 1
01ecb505084d79010000000000 / 00 = 2
01ecb505084d79020000000000 / 00 = 1
01ecb505084d79030000320100 / 00 = 1
01ecb505084d79070001000000 / 00 = 1
01ecb505084d7a040000320100 / 00 = 1
01ecb505084d7b040000320100 / 00 = 1
01ecb505084d7c030000320100 / 00 = 2
01ecb505084d7d010000000000 / 00 = 1
01ecb505084d7d020000000000 / 00 = 2
01ecb505084d7d080001000000 / 00 = 1
01ecb505084d7e020000000000 / 00 = 1
01ecb505084d7f010000000000 / 00 = 1
01ecb505084d7f070001000000 / 00 = 1
01ecb505084d7f090001000000 / 00 = 2
01ecb505084d80010000000000 / 00 = 2
01ecb505084d81010000000000 / 00 = 1
01ecb505084d82020000000000 / 00 = 1
01ecb505084d83030000320100 / 00 = 1
01ecb505084d84010000000000 / 00 = 1
01ecb505084d84030000190100 / 00 = 1
01ecb505084d85010000000000 / 00 = 2
01ecb505084d85020000000000 / 00 = 2
01ecb505084d86090001000000 / 00 = 2
01ecb505084d87030000000000 / 00 = 1
01ecb505084d88030000320100 / 00 = 4
01ecb505084d8b010000000000 / 00 = 1
01ecb505084d8b080001000000 / 00 = 1
01ecb505084d8c060001000000 / 00 = 1
01ecb505084d8d080001000000 / 00 = 1
01ecb505084d8e030000190100 / 00 = 1
01ecb505084d8e040000190100 / 00 = 1
01ecb505084d8f050001000000 / 00 = 1
01ecb505084d90010000000000 / 00 = 1
01ecb505084d91060001000000 / 00 = 1
01ecb505084d91090001000000 / 00 = 1
01ecb505084d92010000000000 / 00 = 1
01ecb505084d92020000000000 / 00 = 1
01ecb505084d93010000000000 / 00 = 1
01ecb505084d93030000320100 / 00 = 1
01ecb505084d930400004b0100 / 00 = 1
01ecb505084d94010000000000 / 00 = 1
01ecb505084d96010000000000 / 00 = 2
01ecb505084d96030000320100 / 00 = 1
01ecb505084d97040000190100 / 00 = 1
01ecb505084d98030000190100 / 00 = 1
01ecb505084d9a020000000000 / 00 = 1
01ecb505084d9b000000000000 / 00 = 3
01ecb505084d9b030000190100 / 00 = 1
01ecb505084d9c000000000000 / 00 = 2
01ecb505084d9c010000000000 / 00 = 2
01ecb505084d9c070001000000 / 00 = 1
01ecb505084d9c090001000000 / 00 = 1
01ecb505084d9d000000000000 / 00 = 5
01ecb505084d9d010000000000 / 00 = 1
01ecb505084d9e000000000000 / 00 = 4
01ecb505084d9e040000320100 / 00 = 1
01ecb505084d9e080001000000 / 00 = 1
01ecb505084da0000000000000 / 00 = 3
01ecb505084da0040000190100 / 00 = 1
01ecb505084da1000000000000 / 00 = 3
01ecb505084da1010000000000 / 00 = 1
01ecb505084da2000000000000 / 00 = 2
01ecb505084da2010000000000 / 00 = 2
01ecb505084da3000000000000 / 00 = 1
01ecb505084da3010000000000 / 00 = 1
01ecb505084da3080001000000 / 00 = 1
01ecb505084da4000000000000 / 00 = 4
01ecb505084da4020000000000 / 00 = 1
01ecb505084da4030000190100 / 00 = 1
01ecb505084da5000000000000 / 00 = 4
01ecb505084da6000000000000 / 00 = 2
01ecb505084da6030000000000 / 00 = 1
01ecb505084da7000000000000 / 00 = 3
01ecb505084da7090001000000 / 00 = 1
01ecb505084da8030000000000 / 00 = 1
01ecb505084da8080001000000 / 00 = 1
01ecb505084daa000000000000 / 00 = 2
01ecb505084daa040000000000 / 00 = 1
01ecb505084dab000000000000 / 00 = 6
01ecb505084dab010000000000 / 00 = 1
01ecb505084dab080001000000 / 00 = 1
01ecb505084dac000000000000 / 00 = 12
01ecb505084dac060000190100 / 00 = 1
01ecb505084dad000000000000 / 00 = 15
01ecb505084dad010000000000 / 00 = 2
01ecb505084dad020000000000 / 00 = 1
01ecb505084dae000000000000 / 00 = 10
01ecb505084dae030000190100 / 00 = 1
01ecb505084daf000000000000 / 00 = 5
01ecb505084daf020000320100 / 00 = 1
01ecb505084db0000000000000 / 00 = 3
01ecb505084db0040000000000 / 00 = 1
01ecb505084db1000000000000 / 00 = 4
01ecb505084db1020000320100 / 00 = 1
01ecb505084db10300004b0100 / 00 = 1
01ecb505084db10400004b0100 / 00 = 1
01ecb505084db2000000000000 / 00 = 3
01ecb505084db2030000000000 / 00 = 1
01ecb505084db3000000000000 / 00 = 2
01ecb505084db30400004b0100 / 00 = 1
01ecb505084db4000000000000 / 00 = 4
01ecb505084db5000000000000 / 00 = 1
01ecb505084db5010000000000 / 00 = 1
01ecb505084db5030000320100 / 00 = 1
01ecb505084db5060001000000 / 00 = 1
01ecb505084db6000000000000 / 00 = 4
01ecb505084db7000000000000 / 00 = 3
01ecb505084db7010000000000 / 00 = 2
01ecb505084db7040000190100 / 00 = 1
01ecb505084db8000000000000 / 00 = 1
01ecb505084db8030000190100 / 00 = 1
01ecb505084db9000000000000 / 00 = 5
01ecb505084db9030000000000 / 00 = 1
01ecb505084db9070001000000 / 00 = 1
01ecb505084db9090001000000 / 00 = 1
01ecb505084dba000000000000 / 00 = 2
01ecb505084dbb000000000000 / 00 = 1
01ecb505084dbc000000000000 / 00 = 3
01ecb505084dbc030000000000 / 00 = 3
01ecb505084dbd000000000000 / 00 = 3
01ecb505084dbd0300004b0100 / 00 = 1
01ecb505084dbd050001000000 / 00 = 1
01ecb505084dbd090001000000 / 00 = 1
01ecb505084dbe000000000000 / 00 = 3
01ecb505084dbe010000000000 / 00 = 1
01ecb505084dbe030000000000 / 00 = 2
01ecb505084dbe0400004b0100 / 00 = 2
01ecb505084dbf000000000000 / 00 = 1
01ecb505084dc0000000000000 / 00 = 5
01ecb505084dc1000000000000 / 00 = 2
01ecb505084dc1010000000000 / 00 = 1
01ecb505084dc1070001000000 / 00 = 1
01ecb505084dc1090001000000 / 00 = 2
01ecb505084dc2000000000000 / 00 = 1
01ecb505084dc2030000320100 / 00 = 1
01ecb505084dc20400004b0100 / 00 = 1
01ecb505084dc3000000000000 / 00 = 1
01ecb505084dc3060001000000 / 00 = 1
01ecb505084dc3070001000000 / 00 = 1
01ecb505084dc4000000000000 / 00 = 1
01ecb505084dc4020000000000 / 00 = 1
01ecb505084dc4030000320100 / 00 = 1
01ecb505084dc4090001000000 / 00 = 2
01ecb505084dc5000000000000 / 00 = 3
01ecb505084dc5030000320100 / 00 = 1
01ecb505084dc5060001000000 / 00 = 1
01ecb505084dc6000000000000 / 00 = 1
01ecb505084dc6030000000000 / 00 = 1
01ecb505084dc6070001000000 / 00 = 1
01ecb505084dc7000000000000 / 00 = 2
01ecb505084dc7010000000000 / 00 = 1
01ecb505084dc70300004b0100 / 00 = 2
01ecb505084dc7080001000000 / 00 = 1
01ecb505084dc8000000000000 / 00 = 2
01ecb505084dc8070001000000 / 00 = 1
01ecb505084dc9000000000000 / 00 = 1
01ecb505084dca000000000000 / 00 = 2
01ecb505084dca060001000000 / 00 = 1
01ecb505084dca080001000000 / 00 = 1
01ecb505084dcb000000000000 / 00 = 2
01ecb505084dcc000000000000 / 00 = 1
01ecb505084dcc020000000000 / 00 = 1
01ecb505084dcd000000000000 / 00 = 1
01ecb505084dcd010000000000 / 00 = 1
01ecb505084dcd0300004b0100 / 00 = 2
01ecb505084dcd040000000000 / 00 = 1
01ecb505084dcd060000190100 / 00 = 1
01ecb505084dce020000000000 / 00 = 1
01ecb505084dcf000000000000 / 00 = 1
01ecb505084dcf010000000000 / 00 = 1
01ecb505084dcf070001000000 / 00 = 2
01ecb505084dd0000000000000 / 00 = 3
01ecb505084dd0040000640100 / 00 = 2
01ecb505084dd0050001000000 / 00 = 1
01ecb505084dd1000000000000 / 00 = 1
01ecb505084dd1020000000000 / 00 = 1
01ecb505084dd2000000000000 / 00 = 1
01ecb505084dd2020000190100 / 00 = 1
01ecb505084dd3040000320100 / 00 = 1
01ecb505084dd4000000000000 / 00 = 1
01ecb505084dd4010000000000 / 00 = 1
01ecb505084dd5000000000000 / 00 = 2
01ecb505084dd50300004b0100 / 00 = 2
01ecb505084dd5060001000000 / 00 = 1
01ecb505084dd6010000000000 / 00 = 1
01ecb505084dd6030000320100 / 00 = 1
01ecb505084dd7000000000000 / 00 = 2
01ecb505084dd7030000000000 / 00 = 1
01ecb505084dd7050001000000 / 00 = 1
01ecb505084dd8000000000000 / 00 = 2
01ecb505084dd8010000000000 / 00 = 1
01ecb505084dd8030000320100 / 00 = 1
01ecb505084dd8070001000000 / 00 = 1
01ecb505084dd9000000000000 / 00 = 1
01ecb505084dd9020000000000 / 00 = 1
01ecb505084dda0300004b0100 / 00 = 2
01ecb505084dda040000320100 / 00 = 1
01ecb505084dda070001000000 / 00 = 1
01ecb505084ddb000000000000 / 00 = 3
01ecb505084ddb010000000000 / 00 = 1
01ecb505084ddb0300004b0100 / 00 = 1
01ecb505084ddb0400004b0100 / 00 = 1
01ecb505084ddc000000000000 / 00 = 2
01ecb505084ddc0300004b0100 / 00 = 2
01ecb505084ddc080001000000 / 00 = 1
01ecb505084ddd000000000000 / 00 = 1
01ecb505084ddd0300004b0100 / 00 = 1
01ecb505084dde000000000000 / 00 = 5
01ecb505084dde040000000000 / 00 = 3
01ecb505084ddf030000000000 / 00 = 1
01ecb505084ddf040000000000 / 00 = 3
01ecb505084de0040000640100 / 00 = 1
01ecb505084de1000000000000 / 00 = 1
01ecb505084de10300004b0100 / 00 = 3
01ecb505084de1040000640100 / 00 = 6
01ecb505084de1070001000000 / 00 = 1
01ecb505084de2020000000000 / 00 = 1
01ecb505084de20300004b0100 / 00 = 1
01ecb505084de2040000640100 / 00 = 8
01ecb505084de3000000000000 / 00 = 1
01ecb505084de3040000640100 / 00 = 1
01ecb505084de3060001000000 / 00 = 1
01ecb505084de4040000640100 / 00 = 1
01ecb505084de5000000000000 / 00 = 1
01ecb505084de5010000000000 / 00 = 1
01ecb505084de5040000640100 / 00 = 4
01ecb505084de6000000000000 / 00 = 1
01ecb505084de7010000000000 / 00 = 1
01ecb505084de70300004b0100 / 00 = 1
01ecb505084de7070001000000 / 00 = 1
01ecb505084de8000000000000 / 00 = 2
01ecb505084de8030000320100 / 00 = 1
01ecb505084de80400004b0100 / 00 = 2
01ecb505084de9030000000000 / 00 = 1
01ecb505084dea010000000000 / 00 = 1
01ecb505084deb000000000000 / 00 = 1
01ecb505084deb010000000000 / 00 = 1
01ecb505084dec010000000000 / 00 = 1
01ecb505084dec040000640100 / 00 = 2
01ecb505084ded000000000000 / 00 = 2
01ecb505084ded040000640100 / 00 = 2
01ecb505084ded070001000000 / 00 = 1
01ecb505084dee0300004b0100 / 00 = 1
01ecb505084dee040000640100 / 00 = 1
01ecb505084def000000000000 / 00 = 2
01ecb505084df0000000000000 / 00 = 1
01ecb505084df00300004b0100 / 00 = 1
01ecb505084df0040000640100 / 00 = 1
01ecb505084df1000000000000 / 00 = 2
01ecb505084df1020000000000 / 00 = 1
01ecb505084df1030000000000 / 00 = 4
01ecb505084df1040000640100 / 00 = 3
01ecb505084df1050001000000 / 00 = 1
01ecb505084df20300004b0100 / 00 = 1
01ecb505084df3000000000000 / 00 = 2
01ecb505084df3020000000000 / 00 = 1
01ecb505084df4010000000000 / 00 = 1
01ecb505084df4040000640100 / 00 = 2
01ecb505084df4070001000000 / 00 = 1
01ecb505084df5000000000000 / 00 = 1
01ecb505084df5040000640100 / 00 = 1
01ecb505084df6000000000000 / 00 = 3
01ecb505084df6080001000000 / 00 = 1
01ecb505084df7040000640100 / 00 = 1
01ecb505084df8040000640100 / 00 = 1
01ecb505084df9080001000000 / 00 = 1
01ecb505084dfa000000000000 / 00 = 1
01ecb505084dfa030000000000 / 00 = 1
01ecb505084dfa040000640100 / 00 = 2
01ecb505084dfb040000640100 / 00 = 2
01ecb505084dfc000000000000 / 00 = 2
01ecb505084dfc030000000000 / 00 = 1
01ecb505084dfd010000000000 / 00 = 1
01ecb505084dfe060001000000 / 00 = 1
01ecb505084dff000000000000 / 00 = 1
01ecb505084dff040000640100 / 00 = 1
01ecb505084dff080001000000 / 00 = 1

**Comment by john30** [comment]
looks as if the unit is not responding as it should. without proper logging/scan result there is not more to tell

**Comment by UnderPalms** [comment]
OK, thanks for the hint.
I think I need to re-setup my entire ebusd installation as since the beginning it seemed to be not properly working.
Once done I'll try out to get proper log results.

Best regards
Peter

**Comment by UnderPalms** [comment]
I received now a distinct log for this issue reading the value "Col" from the circuit "sc"

2023-06-16 13:52:51.427 [main debug] >>> read Col
2023-06-16 13:52:51.427 [bus info] send message: 31ecb509030d0400
2023-06-16 13:52:51.427 [network debug] [00025] wait for result
2023-06-16 13:52:51.433 [bus debug] start request 31
2023-06-16 13:52:51.434 [bus debug] arbitration start with 31
2023-06-16 13:52:51.481 [bus debug] arbitration won
2023-06-16 13:52:51.481 [bus debug] arbitration delay 25 micros
2023-06-16 13:52:51.481 [bus debug] switching from ready to send command
2023-06-16 13:52:51.486 [bus debug] send/receive symbol latency 4 ms
2023-06-16 13:52:51.491 [bus debug] send/receive symbol latency 4 ms
2023-06-16 13:52:51.496 [bus debug] send/receive symbol latency 4 ms
2023-06-16 13:52:51.501 [bus debug] send/receive symbol latency 4 ms
2023-06-16 13:52:51.506 [bus debug] send/receive symbol latency 4 ms
2023-06-16 13:52:51.511 [bus debug] send/receive symbol latency 4 ms
2023-06-16 13:52:51.516 [bus debug] send/receive symbol latency 4 ms
2023-06-16 13:52:51.517 [bus debug] switching from send command to send command CRC
2023-06-16 13:52:51.522 [bus debug] send/receive symbol latency 4 ms
2023-06-16 13:52:51.522 [bus debug] switching from send command CRC to receive command ACK
2023-06-16 13:52:51.526 [bus debug] switching from receive command ACK to receive response
2023-06-16 13:52:51.530 [bus debug] switching from receive response to receive response CRC
2023-06-16 13:52:51.534 [bus debug] switching from receive response CRC to send response ACK
2023-06-16 13:52:51.539 [bus debug] send/receive symbol latency 4 ms
2023-06-16 13:52:51.540 [update info] sent MS cmd: 31ecb509030d0400 / 00
2023-06-16 13:52:51.542 [update error] unable to parse read sc Col from 31ecb509030d0400 / 00: ERR: invalid position

Does that help anyhow?

**Comment by john30** [comment]
same as before: the unit does not answer to the queries as expected, ergo the csvs don't fit

**Comment by UnderPalms** [comment]
Thanks John, is there any workaround to load a csv that fits bester? The ec.sol.csv (which seems to be the wrong file) is always being loaded automatically

**Comment by john30** [comment]
are you sure that the unit is working correctly? since it does answer only on two messages with non-empty response it seems to be rather useless.
the right way to exclude the ec.sol for it would be to adjust the csv to exclude the product number or the HW/SW version

**Comment by UnderPalms** [comment]
Yes, I'm sure it's working correctly since another ebus-device (the 700 and display at my gas-heater) is able to visualize the solar yield from the past months. That means there must be a proper communication being established at least among these 2 devices (700 and sc) which means that they must be properly communicating via ebus.
