### ISSUE TITLE
strange --mqtttopic handling when / inserted

### ISSUE THREAD

**Issue by JanHBade** [john30/ebusd#943]
### Description

setting the topic to --mqtttopic=ebusd/lueftung results in strange behaviour, links to #559 maybe?

![grafik](https://github.com/john30/ebusd/assets/3524802/d7fc1bf7-488f-45bf-aaa5-14347e32f83c)

### Actual behavior

see picture, the / is ignored

### Expected behavior

subtopic in mqtttopic should supported

### ebusd version

current source from git

### ebusd arguments

sudo ./src/ebusd/ebusd --scanconfig=full -c /etc/ebusd -d /dev/ttyebus --receivetimeout=50000 --pollinterval=30 --mqtthost=isis --mqttport=1883 --mqtttopic=ebusd/lueftung -f

### Operating system

Debian 11 (Bullseye) / Ubuntu 20-21 / Raspbian 11 / Raspberry Pi OS 11 (including lite)

### CPU architecture

armv7l

### Dockerized

None

### Hardware interface

other

### Related integration

MQTT generic

### Logs

-none-

**Comment by john30** [comment]
is this only for the global topic or for all?

**Comment by JanHBade** [comment]
for all

**Comment by JanHBade** [comment]
```pi@lueftung:~/ebusd$ sudo ./src/ebusd/ebusd --scanconfig=full -c /etc/ebusd -d /dev/ttyebus --receivetimeout=50000 --pollinterval=30 --mqtthost=isis --mqttport=1883 --mqtttopic=ebusd/lueftung -f
2023-07-04 20:58:49.002 [main notice] ebusd 23.1.23.1-51-ge33810aa started with full scan on device: /dev/ttyebus
2023-07-04 20:58:49.030 [bus notice] bus started with own address 31/36
2023-07-04 20:58:49.067 [bus notice] signal acquired
2023-07-04 20:58:49.070 [mqtt notice] connection established
2023-07-04 20:58:49.073 [mqtt error] subscribe: Invalid function arguments provided.
2023-07-04 20:58:49.803 [bus notice] new master 37, master count 2
2023-07-04 20:58:59.066 [main notice] starting initial full scan
```

![grafik](https://github.com/john30/ebusd/assets/3524802/7c71f813-32b0-4c35-af4a-01e264939174)

![grafik](https://github.com/john30/ebusd/assets/3524802/96afe498-5b19-4f42-8a66-21cde20094aa)

**Comment by john30** [comment]
please check again with 43d3599

**Comment by JanHBade** [comment]
works, thank you
