### ISSUE TITLE
ebusd telling signal connected while ebusd can't connect to ebus network interface

### ISSUE THREAD

**Issue by eazy** [john30/ebusd#965]
### Description

From time to time my ebus network interface crashes and ebusd can't connect to it. 

But the MQTT Message of ebusd tells signal = true

After Powercycling the interface everything works fine again. So I need to detect that problem, to auto powercyle the intreface.

### Actual behavior

Can't detect ebusd is realy working because of the wrong signal information.

### Expected behavior

signal should be false
maybe there should be an additional connection state regarding the ebus interface and not just the ebus signal itself.

### ebusd version

23.2

### ebusd arguments

--mqttvar=filter-direction=r|u|^w

### Operating system

other

### CPU architecture

x64

### Dockerized

None

### Hardware interface

adapter 3.0 Ethernet

### Related integration

MQTT Home Assistant via mqtt-hassio.cfg

### Logs

2023-07-26 21:02:35.828 [bus error] unable to open 192.168.222.107:9999: ERR: generic I/O error
2023-07-26 21:02:35.828 [bus notice] device invalid

**Comment by john30** [comment]
which firmware version is it?

**Comment by eazy** [comment]
device status: extra info: firmware 1.1[8419].2[847f], jumpers 0x37

**Comment by john30** [comment]
can you ping the ip in this case?
what is the status of the LEDs on the adapter and the W5500?

**Comment by eazy** [comment]
the device is responding to icmp.
Adapter LED States:
yellow: on
blue: on
green: normal flickering
red: off

WS550 LED States:
red: on

And I changed the USB-Powersupply already, same behavior.

**Comment by john30** [comment]
please check with the updated source as in e3abbf1

**Comment by john30** [comment]
closed due to inactivity

**Comment by MartinMichaux** [comment]
Hey,
I am actually also having this issue. My ebus adapter is connected to the vr94f network module. I receive signals like:

# Try to telnet to the adapter
telnet 192.168.1.100 9999
Trying 192.168.1.100...
Connected to 192.168.1.100.
Escape character is '^]'.
ƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƵƴ
1ƶ*ƽƪƪƪƪƪƪƪƪƪƪƪƪƪƪƵƉ    ?7ƀǿǿǿƪƪƪƪƪvƵ   Aǿ=ǹǿaǿƪƪƪƪƪvƵǼ
ǿǿƪƪƪƪƵ GǿǿǿǢƚƪƪƪƪƪvƵ   ǿǿǿƅƚƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪvƵƶǿǓƪƪƪƪƪƪƪƪƪƵƴ
2ƶ*3ƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪǱƵ$ƪƪƪǱƵ$ǚƕƪƵƴ
2ƶ*3ƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƵƴ
3Ʒ*ǔƪƪƪƪƪƵƉ     ?6ƀǿǿǿƩƪƪƪƪƪvƵ  Aǿ*ǹǿaǿ?ƪvƵƶǿǓƪƪƪƪvƵǼ
                                                      ǿơƪƪƪƪƵ   GǿǿǿǢƚƪƪƪƪƪvƵ   ǿǿǿƅƚƪƪƪƪƪƪƪƪƪƵ|2Ơ|ǀǏǀ{<ưƪƪƪƪƪƪƪƪƵ}3:}ǀƋǰƪƪƪƪƪƪƪƵ~4
                                                                                                                                   ~Ǐ ǀ!9ƪƪƪƪƪƪƪƵ5ƑƐƑƪƪƪƪƪƪƪƪƵƀ6ǩƀǌƪƪƪƪƪƪƪƪƪƵƴ
3Ʒ*ǔƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪ


and there doesnt seem to be data parser for it.
Could you help ?

Thanks in advance.

**Comment by john30** [comment]
> Hey, I am actually also having this issue. My ebus adapter is connected to the vr94f network module. I receive signals like:
> # Try to telnet to the adapter
> 
> telnet 192.168.1.100 9999 Trying 192.168.1.100... Connected to 192.168.1.100. Escape character is '^]'. ƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƵƴ 1ƶ_ƽƪƪƪƪƪƪƪƪƪƪƪƪƪƪƵƉ ?7ƀǿǿǿƪƪƪƪƪvƵ Aǿ=ǹǿaǿƪƪƪƪƪvƵǼ ǿǿƪƪƪƪƵ GǿǿǿǢƚƪƪƪƪƪvƵ ǿǿǿƅƚƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪvƵƶǿǓƪƪƪƪƪƪƪƪƪƵƴ 2ƶ_3ƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪǱƵ$ƪƪƪǱƵ$ǚƕƪƵƴ 2ƶ_3ƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƵƴ 3Ʒ_ǔƪƪƪƪƪƵƉ ?6ƀǿǿǿƩƪƪƪƪƪvƵ Aǿ_ǹǿaǿ?ƪvƵƶǿǓƪƪƪƪvƵǼ ǿơƪƪƪƪƵ GǿǿǿǢƚƪƪƪƪƪvƵ ǿǿǿƅƚƪƪƪƪƪƪƪƪƪƵ|2Ơ|ǀǏǀ{<ưƪƪƪƪƪƪƪƪƵ}3:}ǀƋǰƪƪƪƪƪƪƪƵ~4 ~Ǐ ǀ!9ƪƪƪƪƪƪƪƵ5ƑƐƑƪƪƪƪƪƪƪƪƵƀ6ǩƀǌƪƪƪƪƪƪƪƪƪƵƴ 3Ʒ_ǔƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪƪ
> 
> and there doesnt seem to be data parser for it. Could you help ?

misplaced here on this already closed issue, but anyway: look at this image here:
https://adapter.ebusd.eu/v5-c6/index.en.html#connections
as of today, you need to have ebusd running somewhere in the network for interpreting the traffic
