### ISSUE TITLE
Create a way to "find" all variables with values

### ISSUE THREAD

**Issue by brucemiranda** [john30/ebusd#97]
Currently I can use a "find a" and the command will list all the Variables with the letter "a" within them but a lot of them have "no data stored".

If there was a way of passing a wildcard like "*" I would get all the variables configured listed. 

Then maybe add a way to just display the variables that have some value, ignoring all those that have a "no data stored"

**Comment by john30** [comment]
"find" without any arguments will solve your first question ("wildcard").
"find -d" will only return messages with data thus solving your second question.
