### ISSUE TITLE
Read all data that is configured 

### ISSUE THREAD

**Issue by brucemiranda** [john30/ebusd#98]
So now I know that "find" will give me a list of all messages and "find -d" will then give me all messages that have values. Is there a way to "read -f" all messages that are configured so that "find -d" then becomes almost as full as just "find".

**Comment by john30** [comment]
just use the the readall.sh script: https://github.com/john30/ebusd/blob/master/contrib/scripts/readall.sh
e.g. from within a git clone: `./contrib/scripts/readall.sh -R "-f" -d`
