### ISSUE TITLE
Temperature fields with the unit "K" are not writable in HA

### ISSUE THREAD

**Issue by LordShadowen** [john30/ebusd#989]
### Description

Not 100% sure this is a bug of intended behavior...

I've changed the mqtt filter to allow writable fields when using MQTT Auto Discovery.

I've noticed that temperature fields with the unit K (Kelvin) were always just read-only sensors, while the standard °C where correctly created as numbers. 

I've "fixed" it by editing my mqtt-hassio.cfg and changing this:

```
type_switch-w-number =
    number,temperature, = temp|,°C$
    number,power_factor, = power*%%
```

to this

```
type_switch-w-number =
    number,temperature, = temp|,°C$
    number,temperature, = temp|,K$
    number,power_factor, = power*%%
```

I've not really understood the syntax of this cfg file, so this might not be the "correct" way. But it did work - the fields showed up as numbers in HA now.

### Actual behavior

Fields of unit type K are not writable in HA

### Expected behavior

Fields of unit type K are writable in HA

### ebusd version

23.2

### ebusd arguments

-

### Operating system

other

### CPU architecture

x64

### Dockerized

latest

### Hardware interface

adapter 5 via WiFi

### Related integration

MQTT Home Assistant via mqtt-hassio.cfg

### Logs

N/A

**Comment by john30** [comment]
not a bug, but was just not forseen that someone would like to adjust temp diff settings via HA, as temp sensors usually should read in °C
