### ISSUE TITLE
eBus adapter configuration will be ignored partly

### ISSUE THREAD

**Issue by frankkaktus** [john30/ebusd#998]
### Description

I've configed my new V5 eBus adapter via the web interface for 
- WiFi network (SSID/passphrase)
- static IP address
- new hostname 
- credentials for httpd
 
WiFi configuration works fine, but IP & hostname & credentials will be ignored. 
![cmd](https://github.com/john30/ebusd/assets/29260869/eaba8422-768f-4583-b72b-dd416aedcf9b)
![config](https://github.com/john30/ebusd/assets/29260869/825d4103-47e3-4797-b110-6e95e778b4bc)

### Actual behavior

IP is set via DHCP protocol and hostname stays at ebus-[MAC]. No password request at opening the web interface.
![config](https://github.com/john30/ebusd/assets/29260869/8960e192-73ab-4d6a-8173-92dbde259fd5)

### Expected behavior

IP configuration should be set to configured values as well the hostname should be set to the configured one.

### ebusd version

23.2

### ebusd arguments

see description

### Operating system

Debian 12 (Bookworm) / Ubuntu 22-23 / Raspberry Pi OS 12 (including lite)

### CPU architecture

arm64

### Dockerized

None

### Hardware interface

adapter 5 via WiFi

### Related integration

other

### Logs

no log

**Comment by john30** [comment]
wrong repo, thus closed

anyway, should be fixed with the [new version just released](https://adapter.ebusd.eu/v5/ChangeLog#20230903)
